### ISSUE TITLE
Custom maps causing Sabre to slow down

### ISSUE THREAD

**Issue by h45e** [the-expanse/SideQuest#101]
Hi,
I have found out that some songs, dont know which one when I patch it over from Sidequest to Quest it causes BS's cubes to jitter making the game unplayable. The only way to fix is to format Quest and reinstall. Restoring backup still has issue (even the master)

**Comment by shaneharris** [comment]
can you test this on the latest version?
things have moved so quickly as of late. With regard to the songs making things glitch etc, that could be corrupt songs or it could be a limitation of having lots of songs. All that is covered by the patcher binaries which are not maintained by SideQuest. You could raise an issue here - https://github.com/trishume/QuestSaberPatch
