### ISSUE TITLE
Default Texture Size

### ISSUE THREAD

**Issue by NickiS1305** [the-expanse/SideQuest#103]
"Default Texture Size Settings" without change, doesnt work.

**Comment by shaneharris** [comment]
Without change?

**Comment by NickiS1305** [comment]
I tried all buttons, but no one works. SideQuest gave me the Feedback "Texture Size set to 1536!!" for example, but it doesnt work inside the Oculus Quest. QuestASM.bat is the only way it works

**Comment by shaneharris** [comment]
@NickiS1305 thanks for this, i will do some more testing here.

**Comment by shaneharris** [comment]
@NickiS1305 indeed i just discovered these never worked. turns out it was an issue the the adb library i was using. I have patched the adb library and this now seems to work ok. It will be out in the next update!

**Comment by Blizzard3001** [comment]
it doesn't work for me in 0.4.2 either
