### ISSUE TITLE
Enable "add all songs to pack" button (Beat Saber feature request)

### ISSUE THREAD

**Issue by Fatalution** [the-expanse/SideQuest#104]
I have almost 300 songs right now and I have no other way of dragging them to my Quest than doing it by hand, one-by-one. Please add the ability to transfer all songs from the list on the right to the list of custom packs on the left

**Comment by avluis** [comment]
Would love it if the Custom Tracks was an auto updating pack that just adds all custom tracks automatically (for now) until something better is figured out

**Comment by shaneharris** [comment]
i think this can already be achieved, although it could be easier. 

By default the `Custom Songs` pack gets all existing songs added, and it also gets newly downloaded songs added by default too. This means a reset packs button would achieve the above functionality in one go. 

does that work?

**Comment by avluis** [comment]
Would the reset packs option reset all packs? It would work for some, but not for those that only want a single pack reset --- maybe if we get an option to create a pack; designate it as the 'default pack' and lock it from being deleted.

**Comment by shaneharris** [comment]
@avluis so the default pack that is there at the start auto adds new songs to that pack. That pack can be deleted and you loose that function, but you can get it back with the reset packs option. 

We also have a bulk multiselect option coming soon too.
