### ISSUE TITLE
Add the ability to sort the songs in the packs (Beat Saber feature request)

### ISSUE THREAD

**Issue by Fatalution** [the-expanse/SideQuest#105]
Currently there is no way to sort the songs in the custom maps packs. You can only sort the songs in the SideQuest, yet it doesn't matter since mistakes can happen while dragging songs top the left by hand. Given the large number of songs (200-300), it's almost impossible to do it correctly by hand.

**Comment by CeTanu-AUT** [comment]
Not sure If you want the same Thing but i would like a feature so you can create packs with certain properties (genre, difficulty..) also to sort them alphabetically by their in game name

**Comment by kalanihelekunihi** [comment]
Agreed on sorting, even if it is Alphabetical only on sync.
Should hooks be added for an extra "extra" folder, it would further be nice if we could create these folders to serve as custom playlists / packs.

**Comment by shaneharris** [comment]
this is in the latest version and will release soon.
