### ISSUE TITLE
Support Beat Saber 1.1.0

### ISSUE THREAD

**Issue by shanness** [the-expanse/SideQuest#106]
Seems there is a new version out.  I was getting weird zip errors, so did as I was told, and deleted and re-installed Beat Saber, and got told "WRONG BEAT SABER VERSION: 1.1.0"

So just letting you know there is a new version, so people can watch this ticket until it's fixed :)

**Comment by Shifter2600** [comment]
Same issue here as well

**Comment by Elementisland** [comment]
Same issue here, I only just bought the game to try these custom songs out and got the "WRONG BEAT SABER VERSION: 1.1.0" error.

**Comment by shaneharris** [comment]
new version coming soon!

**Comment by LAP87** [comment]
same here

**Comment by shanness** [comment]
Thanks for the new version @shaneharris, I can confirm it's working.
