### ISSUE TITLE
use existing ADB from PATH or add it instead of creating a program specific install

### ISSUE THREAD

**Issue by josephsmendoza** [the-expanse/SideQuest#107]
This program, along with a few others I've used, seems hard-coded to search for adb in a program-specific folder without first checking if it has been installed system-wide, such as with the 15-second adb installer
https://forum.xda-developers.com/showthread.php?t=2588979

**Comment by ATechAdventurer** [comment]
@josephsmendoza This is not within the scope of this project. We use [https://github.com/openstf/adbkit](https://github.com/openstf/adbkit) to handle all our cross platform adb client needs. Changing this to support existing ADB installations at specific paths would require changing how adbkit functions.

**Comment by josephsmendoza** [comment]
Actually, you have linked to an ADB client. You must be installing ADB to AppData/Roaming/SideQuest/platform-tools yourself because adbkit already has this functionality.

> Please note that although it may happen at some point, this project is NOT an implementation of the ADB server. The target host (where the devices are connected) must still have ADB installed and either already running (e.g. via adb start-server) or available in $PATH. An attempt will be made to start the server locally via the aforementioned command if the initial connection fails. This is the only case where we fall back to the adb binary.

**Comment by josephsmendoza** [comment]
Actually, if you'd like I can take care of this and #99 by creating an SFX installer which will detect pre-installed adb and install it when missing such that your code need not deal with it at all

**Comment by josephsmendoza** [comment]
I went ahead and built that solution, which is posted [here](https://github.com/josephsmendoza/SideQuest-Installer/releases). The `.exe` file availible there can be opened as a 7zip file to update the SideQuest install inside, no need for me to make a new version every time there's an update.

**Comment by josephsmendoza** [comment]
Closed wrong issue

**Comment by shaneharris** [comment]
closing this to continue discussion over at #127
