### ISSUE TITLE
Allow to click More without a device connected 

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#11]
The more button is hidden without a device connected, this is not needed really

**Comment by cmdrflexo** [comment]
you could gray out the INSTALL button and make it clear why and what needs to be done with a bit of text

![image](https://user-images.githubusercontent.com/4148613/58344060-b7d9c180-7e22-11e9-85f9-babe707a7e10.png)

**Comment by shaneharris** [comment]
I have enabled the more button in the latest release, havent grayed out the button yet though

**Comment by shaneharris** [comment]
we now show "reinstall" if the app is already installed.
