### ISSUE TITLE
THX !!

### ISSUE THREAD

**Issue by DOC1973** [the-expanse/SideQuest#111]
Just want to say THANK YOU for doing such a great job and delivering updates so fast.

But one more question I have........ when will it be possible to use custom saber via SideQuest?

Best regards

**Comment by shaneharris** [comment]
hey thanks for your issue we appreciate your kind words! custom sabers are being worked on and in testing some have already been loaded in. This means its only a matter of time to smooth the process out and get them into SideQuest. 

Thanks!
