### ISSUE TITLE
Bug: SideQuest bsaber song URLs will not trigger download in app

### ISSUE THREAD

**Issue by drewbaumann** [the-expanse/SideQuest#114]
It appears that the SideQuest Chrome Ext. (or other app using the SideQuest url format) fails to open the corresponding action within SideQuest.

@ATechAdventurer and I were able to replicate this issue on the build for macOS.

Note that this gif is from my forked version of the SideQuest Chrome extension to support beatsaver.com

![Screen Recording 2019-06-11 at 02 14 PM](https://user-images.githubusercontent.com/337808/59308113-0d9ccf00-8c55-11e9-84ed-72813882322b.gif)

**Comment by shaneharris** [comment]
is this still the case after the bsaber.com update?

**Comment by drewbaumann** [comment]
@shaneharris yes it is. To replicate grab the [SideQuest Chome Extension](https://github.com/ATechAdventurer/SideQuest-Chrome-Extension) and try using the beatsaber download button on a song at bsaber.com or beatsaver.com.

**Comment by shaneharris** [comment]
yeh i tested it out on windows - 
![image](https://user-images.githubusercontent.com/6830845/59375488-2afd9600-8d46-11e9-9cf6-511208826b1d.png)

**Comment by drewbaumann** [comment]
@shaneharris it must be a macOS and possibly linux bug then.

**Comment by shaneharris** [comment]
ok cool and it did work before? is it work testing again after the migration? or have you already done that?

**Comment by drewbaumann** [comment]
> ok cool and it did work before? is it work testing again after the migration? or have you already done that?

I tried with both versions. @ATechAdventurer might be able to answer when this was last known to work.

**Comment by shaneharris** [comment]
we should test this again with the new angular version.

**Comment by drewbaumann** [comment]
I can test it out once we get the full build. I need to fix the button on the extension since they updated beatsaver.com again.

**Comment by drewbaumann** [comment]
I just tried it using `yarn start` without success. Not sure if it makes a difference once it is built.

**Comment by drewbaumann** [comment]
@shaneharris Tried on 0.4.0 and I am still getting this issue. It brings up the app, but doesn't seem to take action sadly. If you want feel free to test with this branch: https://github.com/drewbaumann/SideQuest-Chrome-Extension/tree/db-fix-beatsaver

Actually this issue should exist on the production version of the app. This branch is simply to restore beatsaver.com compatibility.

**Comment by shaneharris** [comment]
Is this still an issue? Sorry i cant test this i dont have either linux or mac handy. Im not sure if this matters all that much now that we intercept the custom proto in the in app browser. Thoughts?

**Comment by shaneharris** [comment]
closing as wont do
