### ISSUE TITLE
Mac doesn't connect to headset

### ISSUE THREAD

**Issue by htjak** [the-expanse/SideQuest#116]
I've rtried to connect to my headset from my Mac but it won't connect. When I plug the usb cable to my Note 9 it turns green and connects so I know the cable is fine. My Oculus quest is in developer mode. I don't get the "Allow USB Debugging" message when I connect it.

**Comment by shaneharris** [comment]
Hi @htjak if the usb cable is fine the only other solution im aware of for this is to factory reset your headset. I hope that helps!
