### ISSUE TITLE
0.3.2 on Mac: Error reading songs directory: /Users/username/Library/Application Support/SideQuest/bsaber/.DS_Store, Error:Error: ENOTDIR: not a directory, scandir '/Users/

### ISSUE THREAD

**Issue by SteveW25561** [the-expanse/SideQuest#117]
on Version 0.3.2 on Mac I get:

Error reading songs directory: /Users/username/Library/Application Support/SideQuest/bsaber/.DS_Store, Error:Error: ENOTDIR: not a directory, scandir '/Users/

I think it's not liking the Mac .DS_Store folder which is normally invisible and ignored.

**Comment by benshippee** [comment]
Solved this by deleting the .DS_Store file
