### ISSUE TITLE
Error on Mac: System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by jdemart07** [the-expanse/SideQuest#118]
Error Im getting when trying to sync my songs after downloading them:

System.IO.DirectoryNotFoundException: Could not find a part of the path '/private/var/folders/0m/tkd1k2pd2h7f4x7l5pnf1hmc0000gn/T/AppTranslocation/A5FC756C-987C-4916-8B2B-60EDED228E55/d/SideQuest.app/Contents/Resources/app/desktop-app/default-pack-cover.png'. at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) at etc..

Anyone know a fix?

**Comment by Namiriu** [comment]
Not at home but you should check the SideQuest Discord, there's ton of fix for this known problem. Hope you find it !  Have a good day

**Comment by shaneharris** [comment]
there is a new update with an autofix solution for this error! grab version 0.3.3
