### ISSUE TITLE
Error, Song is empty: ...

### ISSUE THREAD

**Issue by PBlake97** [the-expanse/SideQuest#119]
Tried downloading songs after the update, and still met with a download loop. I have a recurring statues error at the bottom of my screen "Error, Song is empty: " then specifies where in my computer but I'm not sure how to fix it.

**Comment by olemartinorg** [comment]
Have you tried deleting that song from the Beast Saber website inside of SideQuest? Or have you recently done anything to that song inside SideQuest or on disk?

**Comment by shaneharris** [comment]
there is a new update! it might be worth grabbing the latest!

**Comment by shaneharris** [comment]
hey im going to close this for now! feel free to open a new one if need be or catch us on discord - https://discord.gg/Y9dCMyF

Download the latest - https://github.com/the-expanse/SideQuest/releases
