### ISSUE TITLE
OpenStoreVR Error

### ISSUE THREAD

**Issue by elhenro** [the-expanse/SideQuest#12]
Hey,
When trying to install "The Expanse", first app, app launcher already installed, i get the following error message and the installation stops, which also happens for other apps: 

```
OpenStoreVR

Error: /data/local/tmp/_stream.apk could not be installed [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl46971588.tmp/base.apk: AndroidManifest.xml]
```

Edit: Installing ALVR works, if that helps..

**Comment by shaneharris** [comment]
Hi thanks for this!

I discovered a problem in the repo for this one which i fixed pretty quickly but you must have got in there just before. The repo needs to be removed and readded to fix the issue.

In the repo section remove and re-add this one: http://showmewhatyougot.x10host.com/vr-games/

Thanks for the report! Ill leave this open for a few days for anyone else.

Cheers!

S

**Comment by elhenro** [comment]
After readding the repos installation ran without errors, but not sure if it executed directly. i cannot start the expanse game yet (loading forever)

**Comment by shaneharris** [comment]
I have discovered an issue with launching The Expanse from the app launcher, i'm currently investigating but int he mean time you should be able to get it going from the unknown sources list. 

I have fixed some of the missing apps in the repos also and ill be posting on discord about how to update those.

Cheers,

S
