### ISSUE TITLE
Unable to sync songs

### ISSUE THREAD

**Issue by helenkgj** [the-expanse/SideQuest#121]
I have followed the directions to redownload patcher and back up/ re install my beat saber versions multiple times. The beat saber custom levels page continues to give me the red "wrong beat saber version " bar at the top and does not allow me to sync the songs I have downloaded. I have tried on all of the backed up versions I have, 1.0.2 and 1.1.0.

**Comment by shaneharris** [comment]
hi @helenkgj i have just released a new version very recently ( like an hour ). have you tried that?

**Comment by shaneharris** [comment]
hey helen, i think this is caused by the old version and an update will solve the problem. If it doesnt fix it for you feel free to open another issue or join us on discord for some more help - https://discord.gg/Y9dCMyF

Download the latest - https://github.com/the-expanse/SideQuest/releases
