### ISSUE TITLE
Weird Glitch With SideQuest 0.3.3

### ISSUE THREAD

**Issue by ChrisDoesStuff2** [the-expanse/SideQuest#122]
So this is really weird, it says it's connected and for about 5 seconds everything works fine, but then if I go into installed apps for example, it doesn't open, then all my custom songs have disappeared in the browser, and if I disconnect headset it still says it's connected, any ideas?

**Comment by shaneharris** [comment]
sounds like a dodgy usb cable! it pols the status every 5 seconds so it only updates every 5 seconds. 

It might be worth running `adb devices` to see if you have an offline device or something
