### ISSUE TITLE
FULL SCREEN

### ISSUE THREAD

**Issue by DASFREAQ** [the-expanse/SideQuest#125]
Not sure if this is the right place, but how about adding full screen capability?  Love your hard work, keep it up!!!!!

**Comment by shaneharris** [comment]
full screen? you can double click the title bar to go full screen, does that help?

**Comment by DASFREAQ** [comment]
Aww crap.  I’m old skool.  Was looking for the little - and box on the upper right.   :)

I will give it a try later. 

Again.  Awesome job on the program.

**Comment by shaneharris** [comment]
there is a maximise / minimize option in the latest version coming soon!
