### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by hughesnetworking** [the-expanse/SideQuest#126]
I can change the color of the sabers but if I try to change their transparency (which is an option in the tool) that setting doesn't transfer. Is this known?

**Comment by shaneharris** [comment]
this should be possible, ill investigate with the patcher guys on what the story is here. I assume it just depends on the shader used by the sabers

**Comment by shaneharris** [comment]
it looks like the transparency is ignored by beat saber. For this reason I have removed the alpha selection in the latest version releasing soon.
