### ISSUE TITLE
bug in Adding a Pack. 

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#130]
I did notice a bug in Adding a Pack. 
To reproduce:
1. Open SideQuest - 2. Open Beastsaber - 3. Select My Downloads - 4. Select Add Pack - 5. Create a new pack with name or name/photo, select Save Pack. - 6. Select the Add Pack again and it defaults to the previously created pack. Any changes made here overwrite the previous pack. 

As a workaround select the option to Save Pack when presented with the previous pack information, then select Add Pack. It then sanitizes the fields.

**Comment by shaneharris** [comment]
this will be fixed in the latest version

**Comment by shaneharris** [comment]
this is now fixed in the new version releasing soon.

**Comment by calebmeyer** [comment]
What version is this fix going into? I'm seeing this issue on version 0.4.1 (windows 10, installed via .exe)
