### ISSUE TITLE
Show more track information for the songs

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#131]
The basis for it would be to help keep track of where Beastsaber levels originate from and provide some insight in cases where there are multiple copies of a song whether it be versions by the same Mapper or different Mappers. 

Could work via a (Go to Page button) from the My Downloads list to redirect to the respective songs page that song was added from or if that would cause too much trouble maybe as an alternative pull the details of the info.json into a properties tab or equivilent for an easy to read format that can be accessed.

**Comment by Mystic7AuDJa** [comment]
Hey Shane thanks again for posting this. 

With the previous request depending on if you go the route of pulling from the info.dat's it could easily open up the ability to sort by the artist, mapper, BPM, and difficulty (possibly with a dropdown to sort by easy, normal, etc)  as options if you wanted to expand the sorting capabilities.
