### ISSUE TITLE
Certain Songs Skipped for an Unknown Reason

### ISSUE THREAD

**Issue by ryanpamplin** [the-expanse/SideQuest#132]
Skipped: 
  570_Mr Blue Sky - Electric Light Orchestra:Missing file referenced by level: /Users/ryanpamplin/Library/Application Support/SideQuest/bsaber/570/song.egg
  141_Gangnam Style - PSY:Missing file referenced by level: /Users/ryanpamplin/Library/Application Support/SideQuest/bsaber/141/song.egg
  217_Beat it - Michael Jackson:Missing file referenced by level: /Users/ryanpamplin/Library/Application Support/SideQuest/bsaber/217/Beat it.egg
  a66_Toxic - Britney Spears:Missing file referenced by level: /Users/ryanpamplin/Library/Application Support/SideQuest/bsaber/a66/song.egg

Not sure why these were skipped.

P.S.
Thank you for your great work! I support you on Patreon - And so should everyone else!

**Comment by Mystic7AuDJa** [comment]
Hey Ryan, can you check the  /Users/ryanpamplin/Library/Application Support/SideQuest/bsaber/a66/ and see if the songs are title'd song.ogg?

**Comment by cqdan** [comment]
same problems here

**Comment by ryanpamplin** [comment]
The songs are .ogg, but changing them to .egg doesn’t seem to fix the problem.

**Comment by Tomadock** [comment]
Found a fix for this.  I deleted and reinstalled SideQuest, deleted the custom level packs, and re-added all of the songs back to a custom pack and everything is working fine again.
