### ISSUE TITLE
'Task Manager' / Ability to close sideloaded apps

### ISSUE THREAD

**Issue by 0xdevalias** [the-expanse/SideQuest#135]
Currently it seems that sideloaded apps that run in oculus tv may not actually quit, but keep running in the background. This seems to persist even after restarting the headset, and i've noticed (presumably because of it) that some legitimate apps running on my quest seem to lag now.

It seems as though it's possible to list/kill running apps via `adb`:
- https://stackoverflow.com/questions/3117095/stopping-an-android-app-from-console
- https://developer.android.com/studio/command-line/adb#am

I can see all running tasks with a command such as `adb shell ps`, or filter with something like `adb shell ps | grep u0_` which seems to show most running apps (but some system looking apps as well). Or refining it even more: `adb shell ps | grep -v com.oculus | grep u0_`

I can then seem to kill them with commands such as:
```
adb shell am force-stop com.instagram.android
adb shell am force-stop com.facebook.katana
adb shell am force-stop com.facebook.orca
```

It would be cool to have a 'task manager' in SideQuest, ideally that would just show me my sideloaded apps and let me quit them (or filter for them?) I probably don't want/need to be able to kill system apps this way (let power users stick to `adb` if they need to)

**Comment by shaneharris** [comment]
I could probably add a generic button to "force close" on the installed app screen, should work or fail silently if the app isn't running i would think?

**Comment by 0xdevalias** [comment]
Given you can also list running apps, it would be even better UX to only show the button if it’s running. Potentially that is just checked when you first load that page + a manual refresh button.

I can’t remember if/what is returned when that command is executed, so if it doesn’t return anything useful/wait till it was closed, probably just firing a refresh after a second or 2 would be the best UX.

**Comment by shaneharris** [comment]
We now have force close in a new version coming soon
