### ISSUE TITLE
Use ReactJS / similar?

### ISSUE THREAD

**Issue by 0xdevalias** [the-expanse/SideQuest#136]
So I was casually browsing the project and noticed that everything seems to be done in raw JS, in a rather huge file:
- https://github.com/the-expanse/SideQuest/blob/master/desktop-app/js/app.js

This is pretty confronting for someone who might be pondering contributing.

I was wondering, have you thought of using https://reactjs.org/ or similar to better structure things?

**Comment by shaneharris** [comment]
Im actually in the middle of an angular conversion!! thanks!
