### ISSUE TITLE
Minimize 

### ISSUE THREAD

**Issue by ChibiBlaziken** [the-expanse/SideQuest#137]
if it is possible to get a minimize button i would be quite grateful, every time i want to just minimize SQ i end up closing it entirely, sometimes losing what i was doing, then confused why it closed, thanks for all everyone's hard work you are amazing.

**Comment by shaneharris** [comment]
Minimize and maximize coming in the next version!

**Comment by ChibiBlaziken** [comment]
You guys are are aweinspiringly amazingly outstandingly awesome

**Comment by shaneharris** [comment]
thank you!
