### ISSUE TITLE
Allow playing songs from Custom Levels screen

### ISSUE THREAD

**Issue by cryptk** [the-expanse/SideQuest#138]
I have quite a few songs and while going through the My Levels list to sort them into packs, I come across songs that I am not sure what pack to sort them into... currently, I have to look up the song in the Custom Levels Folder (which can be a pain because the folders are numeric ID's rather than song names) and play the song file to listen to it a bit... It would be really nice if there was a play/stop button that could be used to play the audio file from the Custom Levels screen.

**Comment by shaneharris** [comment]
The song manager is now removed in favour of beaton
