### ISSUE TITLE
Add option to reset saber colors

### ISSUE THREAD

**Issue by cryptk** [the-expanse/SideQuest#140]
Being able to customize the saber colors is great, but for newer players, it can be convenient to teach them on the "stock" colors... Currently, to revert the saber colors to stock, I have to hand edit the JSON file to remove the custom color settings and then re-launch SideQuest and proceed as normal...

It would be great if the color picker for the sabers had a button that could be clicked to revert the color selector to the stock color.

**Comment by shaneharris** [comment]
This is in the next release coming soon! thank you!
