### ISSUE TITLE
Differentiate 'officially installed' vs sideloaded apps

### ISSUE THREAD

**Issue by 0xdevalias** [the-expanse/SideQuest#142]
Would it be possible to see what has been 'officially installed' via the oculus store/natively on the headset, vs what has been sideloaded?

Currently I find the 'installed apps' section hard to navigate/reason about, as it feels kind of 'cluttered' between everything on my headset.

I'm not sure how hard it would be, but being able to see icons based on if it came from the store/is somehow 'officially signed', if it was sideloaded, as well as more details about it (eg. can you extract/display an icon/name details/etc from it, along with just listing the com.foo.bar package id?)

**Comment by srvrguy** [comment]
Without a whole lot more code to basically copy every single application to the computer to extract an icon or other details, it's pretty much impossible to show that data. Likewise, there isn't really a good way to differentiate between an application that is sideloaded versus installed from the Oculus store.

**Comment by avluis** [comment]
It's also worth mentioning that the current crop of apps don't follow any naming conventions that would help differentiate from sideloaded apps (something that can be blamed on Oculus as they should have guidelines in place for this)
Unless all Oculus store apps have a forced drm or attribute flag in their manifest file only other way I could see to implement this would be with a whitelist of the Oculus Store apps or by querying the Oculus Store itself via some API -- all of this is work that could be undone if Oculus decides to change things on their end so not really worth it.

**Comment by 0xdevalias** [comment]
Or potentially take the other angle and mark sideloaded apps at the point of sideloading? Maybe not perfect, but would give some indication?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by srvrguy** [comment]
Wouldn't work for applications sideloaded via other means such as adb directly or using a different tool. Also, you could only "mark" them locally, so even using the same tool at a different computer or having to clear the SideQuest data directory would destroy that record.

**Comment by 0xdevalias** [comment]
Thus my 'maybe not perfect' comment. Sure, you couldn't have it magically deal with things sideloaded by other means, but don't let perfect be the enemy of good. As for handling another computer/clearing the SideQuest data directory, you could pretty easily store a small metadata file on the device (eg. json file) that contains that mapping, and then SideQuest could read/restore from that if need be.

**Comment by avluis** [comment]
Problem with that approach is that now we have a feature that would only work sometimes and could potentially get confusing for users out there.

The best thing I could see out of this is to keep a whitelist of apks that should never be tampered with so SideQuest would issue several warnings before the user attempts to modify/delete said files.

**Comment by shaneharris** [comment]
hey @avluis thanks! We do operate a blacklist currently on both the desktop sidequest and the app launcher on the device. Apps starting with `com.oculus.*` are ignored from the list.

**Comment by shaneharris** [comment]
#159 

Wow ok so i was having a similar conversation over at the above issue. I think we might have a reasonable solution that would be modified to accommodate the above points but as is its a good starting point. It scans the store apps for matching package names and back fills the names and icons. It also merges in a known list from the new repos repo ( lol ) https://the-expanse.github.io/SideQuestRepos/app-index.json.

Im also thinking of doing an app settings screen with backup options, permissions options, and other app actions like clear data and force close. I think this could cover a lot of the requirement.

**Comment by 0xdevalias** [comment]
> Without a whole lot more code to basically copy every single application to the computer to extract an icon or other details, it's pretty much impossible to show that data

I just had another thought with this, and the current 'backup apk' feature. If we have already backed up an apk, then we wouldn't have to deal with the 'copy every single application to the computer' part of it. So it would just be about the code to parse/extract from the apk itself.

This was from a quick google (so unsure if this would be the best lib for it or not), so there is definitely stuff out there:
- https://github.com/openstf/adbkit-apkreader

**Comment by shaneharris** [comment]
@0xdevalias im afraid this just isnt worth while. The reading operation will take a lot of time for each app. please see #159 for how the latest implementation will look. 


Thanks!

**Comment by 0xdevalias** [comment]
Looks like a good start/‘cache’. Maybe this technique or similar could be used to extract/provide details for the non-store items.

Also, i’m curious, did you run it and know it will take a long time, or are you just assuming it will?
