### ISSUE TITLE
Not sure what I'm doing wrong.

### ISSUE THREAD

**Issue by Sam1Cohen** [the-expanse/SideQuest#143]
I downloaded some apk files and dragged them into the screen and got the installing message.
When I go to the system I can't find the games, I looked in the sidequest section and didn't see them there.
Is there another step I need to do?
All other items I picked from the system lists have installed perfectly.

**Comment by ANewDawn** [comment]
Sometimes apks which have errors don't get picked up by sidequest as displays apk installed.

Test the apk using the ADB install method in command line see if it picks up any errors

**Comment by shaneharris** [comment]
working on this in the latest version!

**Comment by shaneharris** [comment]
this should behave much better in the newest version releasing soon.
