### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by retorquere** [the-expanse/SideQuest#145]
I am interested in helping out by submitting PRs, but I'd need to know how to build SQ first. Are there build instructions anywhere? I tried `yarn install && yarn start` but that didn't work.

**Comment by srvrguy** [comment]
That's basically it. `yarn start` will launch the application from the unpacked source files. If you want to build a package then `yarn dist` by itself will build the package for the platform on which you're running, or using the `w`, `l`, and `m` switches will let you build a package for Windows, Linux, and macOS respectively. Those switches can be combined to build for more than one platform at once.

**Comment by retorquere** [comment]
I did this just now (on macos):

```
$ git clone git@github.com:retorquere/SideQuest.git
$ cd SideQuest
$ yarn install
$ yarn start
```

All work but the last, which nets me

```
yarn run v1.16.0
$ concurrently "electron ." "cd desktop-app && ng serve"
[1] /bin/sh: ng: command not found
[1] cd desktop-app && ng serve exited with code 127
[0] electron . exited with code 0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exit status: 1 [19:02] emile @ limonia: ~/SideQuest [master]: Up-to-date
```

**Comment by retorquere** [comment]
Does `yarn start` create `~/SideQuest`? I don't think it was there before. This won't interfere with regular SQ running right?

**Comment by srvrguy** [comment]
It looks like the source root package.json needs to be updated. For now, cd into desktop-app and run "yarn install" there also. You will also need to install @angularjs/cli globally for the ng command.

I'm not aware that a "SideQuest" directory is created like that.

**Comment by retorquere** [comment]
> It looks like the source root package.json needs to be updated. For now, cd into desktop-app and run "yarn install" there also. You will also need to install @angularjs/cli globally for the ng command.

Would it be possible to install `@angularjs/cli` locally? `npm run` automatically adds binary scripts to the path for locally-installed packages.

When I try to run `yarn add '@angularjs/cli'` it says 

```
"https://registry.yarnpkg.com/@angularjs%2fcli: Not found".
```

> I'm not aware that a "SideQuest" directory is created like that.

My bad -- I had checkout out SQ in my homedir rather than in my usual dev dir.

**Comment by retorquere** [comment]
Could it be `@angular/cli`?

**Comment by retorquere** [comment]
When I do `yarn add @angular/cli` and then `yarn start`, I get only this:
![Screenshot 2019-06-16 at 20 51 37](https://user-images.githubusercontent.com/132108/59568282-ee4cda00-9078-11e9-83bd-045c164698c9.png)

**Comment by retorquere** [comment]
I also don't understand this part:

```
[1] Your global Angular CLI version (8.0.3) is greater than your local
[1] version (6.2.9). The local Angular CLI version is used.
```

because if I `yarn remove @angular/cli` I get

```
$ yarn start
yarn run v1.16.0
$ concurrently "electron ." "cd desktop-app && ng serve"
[1] /bin/sh: ng: command not found
[1] cd desktop-app && ng serve exited with code 127
[0] 2019-06-16 20:57:37.230 Electron[82841:15935249] *** WARNING: Textured window <AtomNSWindow: 0x7fd1a52255b0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[0] electron . exited with code 0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exit status: 1 [20:57] emile @ limonia: ~/github/SideQuest [master]: Untracked
```

and when I run `yarn add @angular/cli && yarn list | grep angular` I get

```
├─ @angular-devkit/architect@0.800.3
│  ├─ @angular-devkit/core@8.0.3
├─ @angular-devkit/core@8.0.3
├─ @angular-devkit/schematics@8.0.3
│  ├─ @angular-devkit/core@8.0.3
├─ @angular/cli@8.0.3
│  ├─ @angular-devkit/architect@0.800.3
│  ├─ @angular-devkit/core@8.0.3
│  ├─ @angular-devkit/schematics@8.0.3
│  ├─ @schematics/angular@8.0.3
├─ @schematics/angular@8.0.3
│  ├─ @angular-devkit/core@8.0.3
│  └─ @angular-devkit/schematics@8.0.3
│  ├─ @angular-devkit/core@8.0.3
│  ├─ @angular-devkit/schematics@8.0.3
```

so I don't know where it's getting this local `6.2.9` from.

**Comment by retorquere** [comment]
wait, `desktop-app` specifies `"@angular/cli": "~6.2.4"`.

**Comment by srvrguy** [comment]
I believe @shaneharris got display stuff working only recently in 2b88fe36. Some of the tooling is still being worked on, AFAIK.

**Comment by retorquere** [comment]
perfect -- after an `git fetch upstream && git merge upstream/master && yarn add @angular/cli`, `yarn start` works!

Best to work against this master? Or is master more for long-term on this repo and should I work on one of the branches that exist on this repo?

**Comment by shaneharris** [comment]
Just to chime in, master is basically a feature branch right now with stable being the pre-angular branch. 

Things are messy right now i have to apologise, but im working towards a more organised workflow pretty soon. So yeh bleeding edge is in master right now, feel free to have a play but a lot of things arent working yet.

**Comment by retorquere** [comment]
Ah right - I'm looking to do some improvement on the pack list, I reckon a ton is going to change there too? Best wait that one out? Do you have a rough idea for an ETA for a feature-complete alpha-ish state?

**Comment by retorquere** [comment]
I've just fetched the latest master but I'm now getting this when I run `yarn install` in the `desktop-app` directory:

```
$ yarn install
yarn install v1.16.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @angular/http@7.2.15" has incorrect peer dependency "@angular/core@7.2.15".
warning " > @angular/http@7.2.15" has incorrect peer dependency "@angular/platform-browser@7.2.15".
warning " > ngx-materialize@6.1.3" has incorrect peer dependency "@angular/animations@^6.0.0-rc.0 || ^6.0.0".
warning " > ngx-materialize@6.1.3" has incorrect peer dependency "@angular/common@^6.0.0-rc.0 || ^6.0.0".
warning " > ngx-materialize@6.1.3" has incorrect peer dependency "@angular/core@^6.0.0-rc.0 || ^6.0.0".
warning " > ngx-materialize@6.1.3" has incorrect peer dependency "@angular/forms@^6.0.0-rc.0 || ^6.0.0".
warning " > @angular-devkit/build-angular@0.800.3" has incorrect peer dependency "typescript@>=3.1 < 3.5".
warning "@angular-devkit/build-angular > @ngtools/webpack@8.0.3" has incorrect peer dependency "typescript@>=3.4 < 3.5".
warning " > @angular/compiler-cli@8.0.1" has incorrect peer dependency "typescript@>=3.4 <3.5".
```

and when I run `yarn start` I get

```
$ yarn start
yarn run v1.16.0
$ concurrently "wait-on http-get://localhost:4200/ && electron ." "cd desktop-app && ng serve"
[1] ℹ ｢wdm｣: wait until bundle finished: /
[1] 
[1] Date: 2019-06-17T11:15:29.077Z
[1] Hash: a2b32de58ac96c93a68e
[1] Time: 4127ms
[1] chunk {main} main.js, main.js.map (main) 2.12 kB [initial] [rendered]
[1] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 145 kB [initial] [rendered]
[1] chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 462 kB [initial] [rendered]
[1] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
[1] chunk {scripts} scripts.js, scripts.js.map (scripts) 310 kB [entry] [rendered]
[1] chunk {styles} styles.js, styles.js.map (styles) 435 kB [initial] [rendered]
[1] chunk {vendor} vendor.js, vendor.js.map (vendor) 328 kB [initial] [rendered]
[1] 
[1] ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.5.0 but 3.5.2 was found instead.
[1] ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
[1] ℹ ｢wdm｣: Failed to compile.
```

and SQ doesn't start up

**Comment by retorquere** [comment]
I was at some point able to get SQ from master to run by a combination of `npm install` and `yarn install` in the root and in the `desktop-app` directory, but not anymore.

Can someone drop a line here when the build stabilizes? I'm going to concentrate on the `pre-angular` branch for now, that just starts up no issue.

**Comment by retorquere** [comment]
(although @shaneharris, I do know typescript and I'd be happy to help out on the `master` branch)

**Comment by retorquere** [comment]
What currently seems to work for me:

```
# just to make sure I'm starting afresh
$ rm -rf node_modules 
$ rm -rf desktop-app/node_modules 
# actual install
$ npm i --save "@angular/cli"
$ yarn install 
$ cd desktop-app && npm install # even though there's a yarn.lock, only npm install works
```

**Comment by shaneharris** [comment]
hey sorry just catching up to this. do you have anything in mind you would like to work on?

**Comment by retorquere** [comment]
The song pack manager. I have done ideas for improvements in the text being displayed, and there's a few requests in the issue list about displaying what songs a pack is in. Also wireless adb.

**Comment by retorquere** [comment]
I've just fetched upstream and with my procedure above I'm now getting

```
ERROR in src/app/repo.service.ts(58,21): error TS2339: Property '__package' does not exist on type 'JSONApp'.
```

**Comment by shaneharris** [comment]
hey @retorquere things have been in flux on master but it should all be relatively stable now. We will be reworking the build steps today and will document the build instructions in the main app readme at that point.
