### ISSUE TITLE
BSaber Add to SideQuest error

### ISSUE THREAD

**Issue by db-M-db** [the-expanse/SideQuest#146]
There's a JS error when trying to add any song to SideQuest:

Uncaught TypeError: this.app.deleteFolderRecursive is not a function
    at extract (bsaber.js:499)
    at D:\Downloads\SideQuest-win32-x64\SideQuest-win32-x64\resources\app\node_modules\extract-zip\index.js:31
    at D:\Downloads\SideQuest-win32-x64\SideQuest-win32-x64\resources\app\node_modules\yauzl\index.js:32
    at D:\Downloads\SideQuest-win32-x64\SideQuest-win32-x64\resources\app\node_modules\yauzl\index.js:167
    at D:\Downloads\SideQuest-win32-x64\SideQuest-win32-x64\resources\app\node_modules\yauzl\index.js:473
    at D:\Downloads\SideQuest-win32-x64\SideQuest-win32-x64\resources\app\node_modules\fd-slicer\index.js:32
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460)

**Comment by db-M-db** [comment]
Seems like the issue originates from BSaber's zip-files which contain html instead of expected content...
Therefor zipfile can't be extracted and error is raised which triggers the above error

**Comment by PaaBliiTo** [comment]
I am facing the same issue here, did you manage to solve it ?

**Comment by PaaBliiTo** [comment]
Also, found out that you were right about the zip-file being an HTML file instead. When I open the downloaded zip file with a text editor, I find an HTML structure with this body : `<noscript> You need to enable JavaScript to run this app. </noscript> <div id="root"></div>`

**Comment by shaneharris** [comment]
i will look into handling this better in the next version

**Comment by shaneharris** [comment]
the add to sidequest will be replaced with a download interceptor that will grab the downloaded files. This should hopefully negate issues like this in future.
