### ISSUE TITLE
Wireless ADB?

### ISSUE THREAD

**Issue by retorquere** [the-expanse/SideQuest#147]
`adb` can [connect wirelessly](https://stackoverflow.com/questions/14357705/adb-over-wireless) after a one-time setup apparently. Would make it even more convenient to use SideQuest.

**Comment by josephsmendoza** [comment]
#152 has the code for this

**Comment by 0xdevalias** [comment]
@josephsmendoza I don't think #152 is the right thing? That's an issue, not a PR?

**Comment by shaneharris** [comment]
I have spent a lot of time playing with this, and the functionality is in sidequest it just needs to be commented out. 

The unfortunate nature of this feature is that it is quite temperamental and will invite a tonne of support requests I don't want to have to deal with. 

I think this would be best served as a tutorial outside of sidequest.

**Comment by josephsmendoza** [comment]
I'll be working on a 3rd-party solution for this [here](https://github.com/josephsmendoza/adb-wireless.git)
