### ISSUE TITLE
adding my own songs (not from bsaber.com)

### ISSUE THREAD

**Issue by retorquere** [the-expanse/SideQuest#148]
If I want to add my own songs, is it enough to just drop them into a folder in the `bsaber` folder? Does the folder require special naming, is there anything in the json files I need to do to avoid clashes?

**Comment by shaneharris** [comment]
Sorry i missed this one, so sidequest will attempt to convert all your songs for you, you just place them in the bsaber folder and it handles the rest.

**Comment by retorquere** [comment]
So folder name does not matter, correct?

**Comment by shaneharris** [comment]
correct!
