### ISSUE TITLE
issue since update with imagine dragons, cant sync anything

### ISSUE THREAD

**Issue by lynchbeth2018** [the-expanse/SideQuest#149]
I keep getting this error code the last two days. I uninstalled beat saber and reinstalled it, uninstalled and reinstalled side quest. My sidequest wont load anything. 

I had to uninstall beat saber and reinstall it so the update would take place. The update was the last one that also had the Imagine Dragons Music Pack. I bought the music pack and it was there and playable. I hooked up my oculus back to my Mac, I downloaded some new tracks, created a new file and for the first two times It would download my custom music but then delete the Imagine Dragons Music Pack. On the third attempt, I cant sync anything I keep getting the error code listed below. Super frustrated.

Ionic.Zip.ZipException: Cannot read that as a ZipFile --> Ionic.Zip.BadReadException: Bad signature (0x4B500000) at position 0x018892E3 at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding) at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first) at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf) at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf) -- End of inner exception stack trace --- at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf) at Ionic.Zip.ZipFile.Read(String fileName, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress) at LibSaberPatch.Apk..ctor(String path) in /Users/travis/build/trishume/QuestSaberPatch/LibSaberPatch/Apk.cs:line 26 at jsonApp.Program.RunInvocation(Invocation inv) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp2/Program.cs:line 82

**Comment by shaneharris** [comment]
hi can you chat with us on discord about this one? - https://discord.gg/uugG7dS
