### ISSUE TITLE
Permissions Grant system for package list screen

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#151]
allow selection of multiple permissions and then grant each on the selected package.

**Comment by shaneharris** [comment]
Could also clean up that screen - maybe a drop down section with management options & info on the app - maybe size or other metrics ?

**Comment by cmdrflexo** [comment]
i think that putting this, if a necessity to run the app correctly, as close to the place the user installs it is important.
i don't know how that would work with the current drag-drop method, maybe pull up the app's page if you know it needs special permissions. you can detect this from the package file, right?

**Comment by shaneharris** [comment]
we can detect after the app is installed and possibly have an auto-grant permissions on the app listings page. Indeed that doesnt work for the apps installed via drag/drop or otherwise so we could have a fallback in the installed apps screen. I might look at adding a link to the permissions section in the status bar at the bottom.

**Comment by shaneharris** [comment]
this is not needed i think, there has been no need for permissions except for the pavlov alpha. closing as not needed
