### ISSUE TITLE
Can no longer patch after latest beat saber update

### ISSUE THREAD

**Issue by doodlleus** [the-expanse/SideQuest#153]
After installing the latest beat saber update, I can no longer sync songs, even after full redownload
The below error appears in sidequest after selecting to apply the patch

System.ApplicationException: Either the 'levels' or 'packs' key is missing. Note the 'levels' key changed names from 'ensureInstalled' in the new version. at jsonApp.Program.SyncLevels(Apk apk, SerializedAssets mainAssets, Invocation inv, InvocationResult res) at jsonApp.Program.RunInvocation(Invocation inv) in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 92

**Comment by shaneharris** [comment]
Hi! In the backups screen there is a "reset packs" option in the latest version of sidequest
it will fix this issue.
