### ISSUE TITLE
error when syncing beat saber songs on current update. 

### ISSUE THREAD

**Issue by CR1T1CALHITZ** [the-expanse/SideQuest#154]
whenever i try to sync my songs, i get this error " Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException: Could not read block - no data! (position 0x0147223D) at Ionic.Zip.SharedUtilities._ReadFourBytes(Stream s, String message) at Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor(ZipEntry entry) at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first) at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf) at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf) --- End of inner exception stack trace --- at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf) at Ionic.Zip.ZipFile.Read(String fileName, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress) at jsonApp.Program.RunInvocation(Invocation inv) in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 77"  can someone help?

**Comment by shaneharris** [comment]
hi can you chat with us on discord about this one? - https://discord.gg/uugG7dS
