### ISSUE TITLE
Suggestion: Direct folder link

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#156]
I'd like to request that if a song has a problem (for example the .egg/.ogg problem) and sidequest throws an error in the bottom bar for that song, that clicking on that bar will open the file explorer of your system and take you to that song's folder, that way it's easier to get to broken songs and change things in there

Or make a button on the right that takes you to that folder, next to the 'X' and 'Copy' buttons

**Comment by shaneharris** [comment]
not an issue anymore with beaton now handling it all
