### ISSUE TITLE
Drag and Drop APK installation no longer works for me

### ISSUE THREAD

**Issue by Replicore** [the-expanse/SideQuest#158]
Since I downloaded the latest version of Sidequest,    Drag and Drop APK installation no longer works for me. I deleted all files and tried to download it again. It still does not work.This feature still exists? Or it is a bug?

**Comment by shaneharris** [comment]
Yes this feature still exists! what desktop platform are you on? do you see a block symbol when you drag over the window?

**Comment by Myhamof** [comment]
Try hold the apk file over the app longer until the block symbol disappears, this is how its work for me i have to wait a couple seconds until its detect the apk file

**Comment by Replicore** [comment]
My Desktop plattform is Windows 10. If i drag a apk over the window my cursor change to a Ø. Waiting a few seconds does not change anything.

**Comment by david1401** [comment]
apk is not working for me neither. I wait with the file over it and it still does nothing.

**Comment by shaneharris** [comment]
@Replicore this is actually a windows limitation. ive seen it a few time. if your using an admin account then windows blocks the drag and drop facility that electron uses. 

In teh new version there is a button to "pick an app to install" to provide another option, but in the mean time if you can use a non admin account in your pc that will allow you to work around the issue.

**Comment by Replicore** [comment]
@shaneharris
It works without administrator rights. Thanks for the quick help.

A thanks for @Myhamof ,too

**Comment by shaneharris** [comment]
@Replicore I came across some more useful info on this 

If someone needs to run an program without admin privileges you can try this https://superuser.com/a/450503 (in case your account is the administrator and everything you start is elevated by default. This shouldn't be a problem in win 8.0 and newer)

**Comment by smallnation** [comment]
Drop it over the actual Sidequest Logo in the interface.

**Comment by akdes** [comment]
> Drop it over the actual Sidequest Logo in the interface.

works for me, thx ;)
