### ISSUE TITLE
SideQuest Home Screen - sidequestvr.com, event stream, announcements, setup + How to videos, Repos Section 

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#160]
allow apps to publish events to sidequest users. Could just operate via PR for now.

**Comment by retorquere** [comment]
What kind of events? Maybe a RSS feed could suffice.

**Comment by drewbaumann** [comment]
Could you give an example of the type of information that would be relayed and where it would go in the UI?

**Comment by shaneharris** [comment]
this idea has evolved a bit, we are looking at setting up a site on sidequestvr.com and what I want to do is make the in-app browser with a landing page the main app screen. This could allow for several feeds like new releases and app related events ( multiplayer apps are often doing meetups and playing games together ) . It could also serve to house the setup sections or other live status information on things like bsaber.com issues or beat saber app updates.
