### ISSUE TITLE
Level names as "song - artist"

### ISSUE THREAD

**Issue by retorquere** [the-expanse/SideQuest#165]
For all songs I could find, `info.dat` has information that makes it possible to show the actual song titles/artists -- it looks like the current implementation renders the folder name I think?

**Comment by shaneharris** [comment]
A legacy version of sidequest used the folder name, for backwards compatibility and for maintaining the scores we still use the legacy convention on songs that were migrated. They are identified by an empty folder in the song folder with the song name on it. If you delete that folder it reverts to the new method sidequest uses where it does indeed pull all the name / artist from the info.dat.

**Comment by ANewDawn** [comment]
@shaneharris I noticed with legacy songs they don't show as installed while browsing bsaber. Will deleting the empty folder like you mentioned resolve this?

**Comment by srvrguy** [comment]
You also need to adjust the directory name containing the song files to match the song ID on the site. Previous IDs were all numeric, but now they are like "53d3". If you fix the directory name, it should then indicate properly.

**Comment by retorquere** [comment]
@shaneharris ah that looks much better, thanks.

@srvrguy how should I do this adjustment? Or is this just so that SideQuest can detect that a song is installed or not?

**Comment by shaneharris** [comment]
@retorquere yep its just to tell if its installed. When bsaber.com and beatsaver.com migrated their whole song library files went from this format `###-### > SongName > info.dat` with the ###-### being the identifiable song id. When they changed over I wasn't given any conversion mappings between the old and new format so the new format just became `5d2c > info.dat`. I came up with a way to maintain the older structure as the song id and name were used to identify a level in beat saber itself and that meant to avoid loosing scores i had to keep the old songs in the same format. The vestigial folder achieve this and removing them makes the song go to the new format. They still need to have the right song id as the folder name to be detected as installed on the bsaber.com site though. 

Sorry that is a long winded response, im sure you didnt want all that detail.

**Comment by retorquere** [comment]
That's actually a nice level of detail, if I'm going to try to contribute I need to understand the internal workings.
