### ISSUE TITLE
Battery indicator

### ISSUE THREAD

**Issue by przemo-c** [the-expanse/SideQuest#166]
Would be nice to see battery indicator to the side of connection status once connected.
Using output from

`adb shell dumpsys battery`

**Comment by ATechAdventurer** [comment]
That's pretty cool, will definitely look into adding that.

**Comment by ANewDawn** [comment]
If possible controller batteries be nice too

**Comment by ATechAdventurer** [comment]
Battery indication support as of #175, looking into controller battery levels, but no promises.

**Comment by shaneharris** [comment]
closing so the conversation can continue over in #175
