### ISSUE TITLE
APK file association on multiple platforms?

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#167]

**Comment by drewbaumann** [comment]
Looks easy enough https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-fileAssociations

**Comment by shaneharris** [comment]
We need to look at how this is handled on opening the app and while its already open - its similar to the protocol handler and probably requires an extension of that logic. 

I am assuming the associated file is passed as an argument to the app when opened, not sure how it is passed when the app is already open. 

so this is a build configuration. Ill come back to this then

**Comment by shaneharris** [comment]
i think with drag and drop this is possibly overkill.
