### ISSUE TITLE
Error on costum song isntall

### ISSUE THREAD

**Issue by ZEROX7** [the-expanse/SideQuest#170]
LibSaberPatch.SerializedAssets+ParseException: Parsed 40368 bytes but expected 40504 for path ID 55 at LibSaberPatch.SerializedAssets..ctor(Stream stream, Version v) in C:\projects\QuestSaberPatch\LibSaberPatch\SerializedAssets.cs:line 248 at LibSaberPatch.SerializedAssets.FromBytes(Byte[] data, Version v) in C:\projects\QuestSaberPatch\LibSaberPatch\SerializedAssets.cs:line 144 at jsonApp.Program.RunInvocation(Invocation inv) in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 85

**Comment by shaneharris** [comment]
Hi There, 

Can you click "backup new master" and then "reset patched to base" in the backups screen?
