### ISSUE TITLE
 i would like a wizard that walks users through uninstalling and reinstalling beat saber and then runs "backup new master" and "reset patched to base"

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#172]

**Comment by josephsmendoza** [comment]
I have done the uninstaller part over [here](https://github.com/josephsmendoza/SideQuest-Wipe), if you can point me to the "backup new master" / "reset patched to base" code I can update it to include that

**Comment by shaneharris** [comment]
This is already in the new app thanks!
![image](https://cdn.discordapp.com/attachments/588106536052850718/592393477698879504/unknown.png)
