### ISSUE TITLE
Add ability to rename apps and add app icons for launcher

### ISSUE THREAD

**Issue by dnlm** [the-expanse/SideQuest#176]
First things first: well done, SideQuest rocks!

My problem: Some sideloaded apps have really strange and unreadable names and/or lack icons. This makes navigating the apps a pita.

I guess it's difficult or maybe even impossible (without re-signing the app) to really rename an app and inject a custom icon.

Thus it would be a neat solution to be able to provide a custom app name and app icon for the SideQuest launcher only.
This could for example be achieved by adding corresponding buttons to the "Installed Packages" screen and storing the custom name/icon in app-specific folders within a predefined folder that gets looked up by the SideQuest launcher and overrides the default names and/or icons.

**Comment by 0xdevalias** [comment]
(Some similar concepts mentioned in https://github.com/the-expanse/SideQuest/issues/142 too)

**Comment by dnlm** [comment]
> (Some similar concepts mentioned in #142 too)

I just read through it, it's different imho. Though my proposed approach of storing meta data generated by the SideQuest desktop app in a "special folder" on the quest (if possible!) might be a solution for 

> Also, you could only "mark" them locally (https://github.com/the-expanse/SideQuest/issues/142#issuecomment-502385383)

**Comment by 0xdevalias** [comment]
Main point of commonality I was raising:
> I'm not sure how hard it would be, but being able to see icons based on if it came from the store/is somehow 'officially signed', if it was sideloaded, as well as more details about it **(eg. can you extract/display an icon/name details/etc from it, along with just listing the com.foo.bar package id?)**

**Comment by dnlm** [comment]
Maybe I was misreading the other topic but I understood it was about the Installed Packages section within the desktop app while I was referring to the SideQuest launcher app installed on the quest.

To be fair, my initial post doesn't make that clear enough!

I don't really care about the Installed Packages section of the desktop app. Showing the (manually entered) name/icon there would be common sense though, so it might just solve both issues (to an extend).

**Comment by dnlm** [comment]
Dann those fast fingers, I accidentally hit "close and comment" on my mobile ☹️

**Comment by shaneharris** [comment]
The app launcher is tied into the package manager on the device, It pulls the app names ( if available ) from there. There is no communication or logistics that provide for the app launcher to read information from SideQuest. The app launcher does provide the ability to hide certain apps if thats useful, but this requirement is otherwise outside of the scope of SideQuest and is not worth implementing IMHO. 

As regards differentiating apps, please see #159 for the latest implementation coming to the latest version of SideQuest. 

Thanks for your feature request!

**Comment by Dylantje** [comment]
Dear...
I do have a bice quest.. love this
Only i connot find other topics...

Is there perhaps a way for custom names and icon?
