### ISSUE TITLE
Add auto-update to the app

### ISSUE THREAD

**Issue by yamalight** [the-expanse/SideQuest#178]
First of all - awesome job on the amazing app! 👍 
Would love to see auto-update feature integrated since updating manually is a bit of pain 😄 
Since it's Electron-based it shouldn't be too hard to do. Are you open to adding this? If yes - I could send a PR with it over the next week (if it's not already in the pipeline)

**Comment by shaneharris** [comment]
hey @yamalight thanks for the offer! we are working on the build process right now and i think were going with `electron-builder` and `electron-updater` and also getting the apps signed. We are also looking at getting automated builds up with travis/appveyor as soon as the build is tied down.

If you have any thoughts its more than appreciated!

**Comment by yamalight** [comment]
@shaneharris that's exactly the setup I've been using in my projects - and it's been working pretty good. 
let me know if you want any help on this - will be more than happy to send a PR or two :)

**Comment by retorquere** [comment]
I have quite a bit of experience with Travis -- if help is needed here, give me a holler

**Comment by shaneharris** [comment]
Auto Update is now live. Were having some issues with the mac stuff, but we should be able to sort that soon.
