### ISSUE TITLE
showing not connected in sidequest

### ISSUE THREAD

**Issue by donknarn** [the-expanse/SideQuest#179]
I went through the instructions as listed for sidequest and when I plug the Oculus Quest in it does not show connected. There is obviously something I am missing. I followed steps 1 - 5 as listed. What am I missing?

**Comment by shaneharris** [comment]
hey @donknarn it could be the usb cable, do you have another one to try? Also the pattern settings in the oculus app can also cause issues, you might try disabling those? If you still have issues come and chat with me on discord and ill talk you through some stuff - https://discord.gg/pqUz9F7
