### ISSUE TITLE
Add status bar along the top or bottom 

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#18]
maybe you could devote a band across the bottom of the window for status information. a common design feature that lets you see quick info about the last operation done

**Comment by shaneharris** [comment]
https://cdn.discordapp.com/attachments/581519549027844106/581895935202820107/sidequest_statusbar_concept01.png

**Comment by cmdrflexo** [comment]
![sidequest_statusbar_concept01](https://user-images.githubusercontent.com/4148613/58372829-854aca00-7ef1-11e9-9e53-ac245a5d31a7.png)
here's the image. discord cdn links break a lot

**Comment by shaneharris** [comment]
implemented in the bsaber branch
