### ISSUE TITLE
1440p monitor full screen image resize

### ISSUE THREAD

**Issue by Enderzt** [the-expanse/SideQuest#185]
Sort of a weird, very small issue. When full screen it seems the image in the banner isn't large enough when a monitor isn't in 1080p aspect ratio? It creates a weird see through window in the corner of the app when in full screen. I imagine this would be the case for other monitors? 4k or Ultrawides? This is how it looks on my 1440p monitor. Looks fine on my 1080p one. 

![1440p Full Screen](https://user-images.githubusercontent.com/18450435/60062468-4e6dfc80-96c7-11e9-817f-ebc9145d3307.png)

Not really a bug more of a easy fix for the next update?

**Comment by shaneharris** [comment]
Thanks for this i will fix this up! just need a wider image indeed.

**Comment by shaneharris** [comment]
i have increased this to over 4 k wide, it will be in the next release
