### ISSUE TITLE
Replacement text doesn't work on Mac.

### ISSUE THREAD

**Issue by ryanlauderbach** [the-expanse/SideQuest#188]

**Comment by drewbaumann** [comment]
@ryanlauderbach  mind providing more information regarding this bug?

**Comment by ryanlauderbach** [comment]
For Beat Saber, I put in BUTTON_QUIT and I put "bye" in the other box and ran the patcher. When I open Beat Saber the button text doesn't change. I don't think I've tried again with the latest release. I'll try again and see if it still doesn't work.

**Comment by shaneharris** [comment]
This patcher method is no longer supported. Thanks!
