### ISSUE TITLE
Custom Colors not working

### ISSUE THREAD

**Issue by zoomiti** [the-expanse/SideQuest#189]
Every time I attempt to change the colors the apk gets installed with green and cyan sabers. This is also reflected when after I press "sync songs" those very same colors appear on the picker. Those aren't the colors I pick but they are the ones the picker defaults to when I press "sync songs" and even after changing them again those colors are the ones getting installed.

**Comment by alxpez** [comment]
Some color seem to be passing, but others get a "random" fallback

**Comment by shaneharris** [comment]
this does look like a problem with the type coercion resulting in NaNs

**Comment by shaneharris** [comment]
turned out it was a parsing error, I was expecting `rgba(X,X,X,X)` and it was using `rgb(X,X,X)` - the result was that it chopped off the first number of the rgb value - `rgb(255,255,255)` would become `55,255,255`
A fix coming soon!
