### ISSUE TITLE
Music Pack Order is not Retained

### ISSUE THREAD

**Issue by zoomiti** [the-expanse/SideQuest#190]
After adding a new music pack and placing it where I wanted it in the order of my music packs, it instead gets installed at the end of the list of packs. No matter where I order it in sidequest it ends up at the end

**Comment by shaneharris** [comment]
Does the order get retained within SideQuest itself?

**Comment by Xany** [comment]
I can reproduce bug. When pressing "run patcher" the packs order of creation is restored. 
I had another weird bug too: after 9 packs, the following "add pack" where not displayed, so I tried to create 3 in total before giving up. When pressing "run patcher" those 3 invisible packs appeared out of nowhere.

**Comment by yonta** [comment]
I have same trouble in Release SideQuest-0.4.2-win.
After I change orders of packs, the "add pack" makes a pack where no displayed.
Revisit song list, created pack is displayed, and changed orders is discarded.

**Comment by shaneharris** [comment]
This patcher and song manager is now removed. Thanks!
