### ISSUE TITLE
Add ability to filter master song list by playlist

### ISSUE THREAD

**Issue by FungManHin** [the-expanse/SideQuest#193]
Is it possible to filter songs in the master song list (right panel) by the playlist that it was downloaded from?  This way, when recreating playlist packs we can add all the songs that belong in that playlist.  I don’t know anything about the coding involved but I’d imagine it would be a tag associated with the files when downloading.

**Comment by shaneharris** [comment]
@FungManHin the songs do not contain any play list information when being downloaded. there is a request for a playlist downloader which would be easier to achieve.

thanks for your suggestion but ill close this one in favor of #109
