### ISSUE TITLE
Suggestion: More visually appealing and user-friendly device package list

### ISSUE THREAD

**Issue by cmdrflexo** [the-expanse/SideQuest#20]
Having a list of installed packages is great, and the uninstall option is icing on the cake. I think the whole list can be improved a lot if most of the common packages can be shown with proper application names and/or app icons.
One method could be to maintain a database of the most common application names and icons. This is easy to implement and will allow the majority of packages on devices like Go and Quest to get proper names and icons.

Also, as a side note, somewhat related;
![image](https://user-images.githubusercontent.com/4148613/58372880-b1b31600-7ef2-11e9-8796-b4b2c054a1ae.png)
You might want to have a list of packages *not* to show an "UNINSTALL" button next to...or just hide them from the list entirely

**Comment by shaneharris** [comment]
Filter the list based on com.oculus package name

**Comment by shaneharris** [comment]
I now have a filtered list of packages in verison 0.1.1. It also shows alternating colors for each package line and includes the package name on the uninstall warning dialog

![image](https://user-images.githubusercontent.com/6830845/58386586-e1007a80-7ff9-11e9-9ac3-af501b0d7b53.png)
