### ISSUE TITLE
light/dark theme switching possibly stuck in a loop

### ISSUE THREAD

**Issue by nickjohnford** [the-expanse/SideQuest#202]
Platform: MacOS 10.14.5

I noticed that SideQuest was using a lot of CPU.

Looked into the web inspector, and noticed that all the css classes dealing with the theme were "flickering"... looks like the theme is constantly being applied.

**Comment by shaneharris** [comment]
this does look like im dinding to a method in too many places, ive swappped all these out for property binding which should reduce the number of evaluations.

**Comment by shaneharris** [comment]
this is fixed in the latest version.
