### ISSUE TITLE
Application Icon is wonky on macOS

### ISSUE THREAD

**Issue by marcusmoore** [the-expanse/SideQuest#203]
Hello! First off, thanks for making this. It's making life a lot easier for me.

One thing  I noticed is that the icon in the dock and in the application switcher looks fine but the icon in the Applications folder and one used when using Spotlight (or Alfred) shows up like this:

![image](https://user-images.githubusercontent.com/1141514/60224226-6f089480-9836-11e9-8c7b-abff2a586711.png)

**Comment by srvrguy** [comment]
I don't use Alfred, but the icon looks fine in Spotlight. Can you try restarting your computer?

**Comment by illBeRoy** [comment]
![image](https://user-images.githubusercontent.com/6681893/60267541-2662e100-98f3-11e9-9814-e14d912480c2.png)

wonky in spotlight as well ;)

It's an electron app, right? I'll try and see if I can help with finding out the cause :)

**Comment by marcusmoore** [comment]
A little more information: it's fine when I view it on my laptop screen but looks like my original screenshot when being displayed on my 4k monitor.

**Comment by srvrguy** [comment]
The icon will likely be fixed in a new release as I've re-generated the icns file. I'll leave this open for now in case it's still a problem after release.

**Comment by thgh** [comment]
Looks good here!

**Comment by marcusmoore** [comment]
Fixed in [0.4.2](https://github.com/the-expanse/SideQuest/releases/tag/v0.4.2).

Thanks!
