### ISSUE TITLE
Device Settings - indicate stock defaults

### ISSUE THREAD

**Issue by rgreer4** [the-expanse/SideQuest#206]
The device settings page is awesome.

However before changing anything it requires a lot of research, and there is no clear indication that I can tell of what the Quest's hardware stock default is, to revert a change.  Showing some indication of which settings are "stock" would make this section a lot more user friendly (and less scary to experiment with).

**Comment by shaneharris** [comment]
I have added "default" buttons to all options. Indeed it was hard to find and I have had to make some settings the lowest value by default. These options have actually been broken for a while but i fixed them by patching the adb library. this will be out in the next release.

**Comment by shaneharris** [comment]
this is now added in master
