### ISSUE TITLE
Enhancement: Open Specific Song Folder (Possibly related to #201)

### ISSUE THREAD

**Issue by Mystic7AuDJa** [the-expanse/SideQuest#209]
Req:
An option to 'Open Song Folder' either via a button on each song or right click and select so you can easily locate the info.dat and other files of selected song.

Reasoning:
Currently it is not easily possible to see what the names are due to the folders being pure numbers and letters.

Some mappers have their own naming conventions for songs that are just flat incorrect. I.e. in cases of:
  "_songName": "Muse - Uprising",
  "_songSubName": "",
  "_songAuthorName": "Mappername",
  "_levelAuthorName": "",
OR
 "_songName": "Muse",
  "_songSubName": "Uprising",
  "_songAuthorName": "Mappername",
  "_levelAuthorName": "",

This sucks for sorting by alphabet for a couple of reasons:
1. If I'm going by actual song name.
2. If I'm trying to jimmy rig a sort by artist manually.
3. If a sort by songAuthor or levelAuthor is implemented it wouldn't sort correctly.

The ability to direct us to the proper folder where the info.dat resides would be a great workaround until the ability to alter the Info.Dat's within the software is deployed. It would allow us to make the changes needed:
  "_songName": "Uprising",
  "_songSubName": "",
  "_songAuthorName": "Muse",
  "_levelAuthorName": "MapperName",

Alternatively if you intend to build a ui to present the contents of the Info.Dat that can be altered and update the info.dat that would be an ideal end-user solution instead of the band-aid fix I outlined to Open Specific Song Folder.

**Comment by shaneharris** [comment]
this is now added in master
