### ISSUE TITLE
UI: User error prevention when unistalling package

### ISSUE THREAD

**Issue by fecheva** [the-expanse/SideQuest#21]
After clicking unistall, a warning appears waiting for confirmation, but the message does not include the name of the package to be deleted. As there is no rule, users may mistakenly click on the previous or the following "uninstall" button to the package they want to delete (visual misalignment). 

This may be prevented by:
- Showing some kind of rule or diferent shadowing for odd and even lines of packages
- Recalling the name of the package to be deleted in the warning and confirmation message.

Thank you and kind regards.

**Comment by shaneharris** [comment]
thanks for these suggestions. I have implemented both of these in the new version 0.1.1. 

Thanks again!
