### ISSUE TITLE
Enhancement: Installed Apps Search

### ISSUE THREAD

**Issue by Mystic7AuDJa** [the-expanse/SideQuest#210]
Req: A search box to power through the contents of your Quest from the Installed Apps (9^3) button

Reasoning: It will be useful in cases where you can't seem to track down a specific app visually.

If possible this could be expanded to the Files section as well for ease of use.

**Comment by shaneharris** [comment]
this is a good idea! the files section couldd also be reasonably easy to achieve, at least searching the current file list.

**Comment by joshuacant** [comment]
An option (or default) to suppress displaying all android, com.android, and com.oculus packages would be real good too. The new full list is a real pain to use.

**Comment by shaneharris** [comment]
This is now in the latest version, not the search but the filtering. leaving this open for the search feature

**Comment by shaneharris** [comment]
the list is much easier to work with now, i don't think a search is needed. 

thanks!
