### ISSUE TITLE
Stuck in loading screen after dropping zip file that is unrecognised.

### ISSUE THREAD

**Issue by fascistutopia** [the-expanse/SideQuest#212]
I have no idea if this is not the proper procedure to add a song, or if it's a problem with Sidequest.

My intent is to add new Beatsaber custom levels.

Running 0.4.1 on Windows 10.
I download custom levels from bsaber.com into my Downloads folder, as zip files.
I drag any number of zip files from my Downloads folder onto the "Beast [sic] Saber Custom Levels" panel of Sidequest.

Then this happens:
1. The app gets a partially transparent white "Drop file(s) here!" overlay.
2. Orange notification bar at the bottom: "Unrecognized file C:/Users/.../[long zip file name]"
3. App is totally unresponsive, except it lets you hit the "X" to close the app.

**Comment by shaneharris** [comment]
@fascistutopia looks like a combination of a bug and a workflow issue. 

you cant drop zip files to get songs im afraid. What you can do though is find and download the songs in the browser included in sidequest - this will auto extract and put them in the right place. Just hit the normal download button on either bsaber.com or beatsaver.com and it will pop up with a saving song dialog. The other option is to unzip the files and put them into the songs folder for sidequest ( find it with "open song folder" )

**Comment by shaneharris** [comment]
this is now fixed, release coming soon.
