### ISSUE TITLE
Beat Saber wants an Update

### ISSUE THREAD

**Issue by Vigo79** [the-expanse/SideQuest#213]
I have a fresh installation of beat saber with Imagines Dragons. 
Then I do a backup with SideQuest. After syncing songs Beat Saber is asking for an update. When I say no, I can play but without Imagine Dragons. If I push Yes then Beat Saber will do an 241MB Update, but breaks after 30mb, installs and when I will open it, then there is this Update again. 
Does someone have this problem too?

Greetings Vigo

**Comment by shaneharris** [comment]
@Vigo79 this is aknown issue, after you patch beat saber always thinks it needs an update but doesnt, it also fails on update as you described and sometimes can be tricky to uninstall. The workaround is to uninstall in sidequest on the apps screen and then update fresh in beat saber - you only need to do this if you want to update beat saber. 

As regards the DLC, sidequest has a "data backup" facility on the app screen to backup DLC files to your PC and then restore them later. 

I hope that helps!
