### ISSUE TITLE
no USB debugging

### ISSUE THREAD

**Issue by profb888** [the-expanse/SideQuest#22]
I got to the point where I connected the USB cable, but nothing pops up on the Quest, not the debugging, not even the Allow option to access it from my PC at all which had always popped up (with this cable). My PC sees the Quest but only as an empty folder. What do I do?
Thanks!

**Comment by ATechAdventurer** [comment]
Are you in developer mode on your headset?

**Comment by ATechAdventurer** [comment]
Try opening a terminal/cmd and running 
`adb devices`

**Comment by shaneharris** [comment]
we got this fixed! turns out it was the antivirus that deleted adb. I have added instructions in app and on the readme.
