### ISSUE TITLE
Maximise doesnt work on the first click

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#220]
on first click it seems to un-maximize, it should maximize

**Comment by KaanMol** [comment]
That isn't the only problem, there are a lot of problems with the whole top bar. It seems it doesn't maximize at all, instead it makes the frame the same size as the screen. There are more problems with it tho. I will look in to it

**Comment by shaneharris** [comment]
Indeed its not ideal but its the provided behaviour of electron i believe. The above issue has been fixed so ill close this one but feel free to open more for other issues
