### ISSUE TITLE
Add homebrew cask formula

### ISSUE THREAD

**Issue by 0xdevalias** [the-expanse/SideQuest#222]
For macOS, it would be awesome if we could install via homebrew cask:
- https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask

**Comment by srvrguy** [comment]
I can certainly look into doing this as I am an active Homebrew user (but not contributor yet).

**Comment by srvrguy** [comment]
There's now a PR pending at Homebrew/homebrew-cask#65780

**Comment by fforres** [comment]
This is awesome! :D

**Comment by srvrguy** [comment]
SideQuest is now in the Homebrew cask listing.
