### ISSUE TITLE
Can we have a button to cancel on app/game downloading dialog?

### ISSUE THREAD

**Issue by ioneng** [the-expanse/SideQuest#224]
Some apps/games are hosted on very slow servers. Can we have a way to cancel the download before it starts to install?

**Comment by ioneng** [comment]
I close the whole app to cancel the download for now.

**Comment by shaneharris** [comment]
Hi There! we do not have a way to cancel the download in progress, we have moved the downloads to a background queue for now though, so you can continue to use the app while downloading. I hope this solves some of the issues you have been having.
