### ISSUE TITLE
Side menu not appearing, "Back" button only thing displaying when clicking on item.

### ISSUE THREAD

**Issue by jaytmek** [the-expanse/SideQuest#225]
![sidemenu](https://user-images.githubusercontent.com/52449241/60502044-ef0a8080-9cb4-11e9-84b5-f635add28576.png)
![back](https://user-images.githubusercontent.com/52449241/60502045-ef0a8080-9cb4-11e9-8d74-62bbc60019d5.png)

Please see attached photos. I'm not getting the side menu which is shown on all tutorial videos etc. When I click on any items on the home display I just get a "Back" button.

**Comment by shaneharris** [comment]
try adding these repos one by one in the repos screen. 

https://the-expanse.github.io/SideQuestRepos/vr-games/
https://the-expanse.github.io/SideQuestRepos/vr-apps/
https://the-expanse.github.io/SideQuestRepos/android-games/
https://the-expanse.github.io/SideQuestRepos/android-apps/
https://the-expanse.github.io/SideQuestRepos/nsfw/

**Comment by jaytmek** [comment]
Thats done it! Thanks for the quick reply. Was it an error or did I miss a step in the set up?

**Comment by jaytmek** [comment]
![second problem](https://user-images.githubusercontent.com/52449241/60502944-a358d680-9cb6-11e9-835f-c706d2b47123.png)
Sorry, still having issues. The apps show now, however I get as shown in the picture when clicking on them. I still get the "Back" button screen if I click "more". I've tried uninstalling and reinstalling but same issues.

**Comment by jaytmek** [comment]
Scrap that, I reinstalled, then opened and closed the app and its working fine now. Thanks for the help.

**Comment by Matt2468rv** [comment]
I had this issue too. Wonder why it's happening?

**Comment by cryptcow** [comment]
i have the same problem, reinstall dont work ;(

**Comment by Crusage** [comment]
> try adding these repos one by one in the repos screen.
> 
> https://the-expanse.github.io/SideQuestRepos/vr-games/
> https://the-expanse.github.io/SideQuestRepos/vr-apps/
> https://the-expanse.github.io/SideQuestRepos/android-games/
> https://the-expanse.github.io/SideQuestRepos/android-apps/
> https://the-expanse.github.io/SideQuestRepos/nsfw/

You should defintely add a "Reset all Repos" option

**Comment by cryptcow** [comment]
yes i have try it, all thinks i have to do from the user jaytmek, same problem, by clicking a game or a tool i become a blank screen. i have reinstall the old and the new version, same problem. i have installet net und c++ packs . same problem ;(

now i search for apk only files and drag and drop this over sidequest to the quest, its work fine yet. but the sidequest library himself doesnt work in win 10 on my laptop.

**Comment by jaytmek** [comment]
I found that after adding the repos I had to restart my laptop before I could see anything other than the "back" button when I clicked on the games.

**Comment by cryptcow** [comment]
YES! a restart is important after adding the repos by hand..
thank you jaytmek ;)))

**Comment by shaneharris** [comment]
I have a new version of the apps system coming soon with a overhaul of the whole app system with loads of tools for developers to manage their apps etc. int he mean time i have made a change that i think will negate this issue until that is out. This will be in the latest hotfix coming soon.

**Comment by shaneharris** [comment]
The new app listings have been up for a while now, a future release might remove the old repos system altogether. Thanks everyone!
