### ISSUE TITLE
Linux version SideQuest

### ISSUE THREAD

**Issue by Corfromturnhout** [the-expanse/SideQuest#230]
I followed the steps but SideQuest wont install on my Linux machine:

drcor@drcor:~/Downloads/SideQuest-0.4.2$ cd /home/drcor/SideQuest/
drcor@drcor:~/SideQuest$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
Same issue with Git cloning, exact same error message
And true: there is no intall file anywhere in the filestructure.
Same issue with all the other yarn commands in your step by step description
So what is the solution here?
C.

**Comment by srvrguy** [comment]
If you're trying to run the release, then you don't need to do all that, just run the "sidequest" binary from the tarball.

**Comment by shaneharris** [comment]
^^ yes just grab the latest release.
