### ISSUE TITLE
When downloading some beat saber custom songs, SideQuest gives "Error, cant parse info.dat file" on linux

### ISSUE THREAD

**Issue by stringham** [the-expanse/SideQuest#231]
In the cases that I came across that have this error, it is because on linux file names are case sensitive and set the cover image filename to be `cover.jpg` instead of `Cover.jpg`. ([example here](https://bsaber.com/songs/4a6/))

Manually editing the `info.dat` file to have the correct casing fixes the problem, but it would be nice if:

1) SideQuest handled this edge case automatically.
2) SideQuest didn't freeze on the "downloading song" spinner when an error is encountered here. Currently, it requires you to kill the application and restart it.

**Comment by SuiNom** [comment]
> In the cases that I came across that have this error, it is because on linux file names are case sensitive and set the cover image filename to be `cover.jpg` instead of `Cover.jpg`.
> Manually editing the `info.dat` file to have the correct casing fixes the problem, but it would be nice if:

+1 - This almost always seems to be related to Linux case sensitive files names when I've encountered it. 


Thanks @stringham, for this pro tip, but would be nice if SideQuest could compensate, perhaps by forcing all strings to be lowercase when parsing?

**Comment by stringham** [comment]
>perhaps by forcing all strings to be lowercase when parsing?

It would need to do something like `fs.readdirSync` then see if any of the files in the directory match the cover name in a case insensitive comparison.

**Comment by ATechAdventurer** [comment]
I will take a look at this and see if I can fix it.

**Comment by kleijnweb** [comment]
As an aside, I wasn't able to get any songs to list *any* songs in "Beast Saber Custom Levels" until I resolved the name-case issue for the one download.

**Comment by shaneharris** [comment]
Hi there, i guess this isnt in scope anymore as the songs are now read by beaton in the headset. Going to close this one but feel free to re-open
