### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by drewbaumann** [the-expanse/SideQuest#234]
Add support for multiple language support in app.
This can be achieved using I18n and with the help of the community.

We already have interest in a French #57 and Dutch translation #233

**Comment by RedBrumbler** [comment]
Oh sorry didn't see this one, my bad!

**Comment by drewbaumann** [comment]
@redbrumbler I simply wanted to consolidate! No hard feelings 😅

**Comment by Mr-Rixa** [comment]
I can do **Finnish** TR if localization becomes a thing. 😅

**Comment by shaneharris** [comment]
this is awesome, it wouldnt take that long to pull all copy into a language file. I will look at this today at least a starting point in a feature branch

**Comment by swissbongj** [comment]
If helpful, I can gladly contribute a german localisation for sidequest

**Comment by shaneharris** [comment]
this could be much more complicated now, given that a large portion of the sidequest app is now coming from the https://sidequestvr.com website, and most of that text based content is coming from app titles and descriptions. I think this might have become too large of a body of work to be worth it.
