### ISSUE TITLE
Didn't uninstall BS first, now unable to uninstall it.

### ISSUE THREAD

**Issue by avib99** [the-expanse/SideQuest#239]
I didn't unintall BS and went through the Beaton installation. Now i'm unable to uninstall BS. Nothing happens when clicking Uninstall.

**Comment by srvrguy** [comment]
Are you trying to uninstall from the headset or via SideQuest? Patched versions of BeatSaber are known to fail uninstalls via the headset.

**Comment by avib99** [comment]
Thanks ur right, i am doing it in the headset. Now trying via SQ but i can't seem to find how.

**Comment by avib99** [comment]
Problem solved! Thank you! ;)
