### ISSUE TITLE
Add scrcpy to SideQuest

### ISSUE THREAD

**Issue by gabetoth-dgh** [the-expanse/SideQuest#241]
Please add [scrcpy](https://github.com/Genymobile/scrcpy) to SideQuest to allow streaming and recording.

**Comment by shaneharris** [comment]
sorry this is not quite as easy as that, scrcpy unfortunatly adds a java dependencie on all platforms and therefore makes sidequest more cumbersome. Its best to leave scrcpy as an external facility. 

Thank you!
