### ISSUE TITLE
Lag in custom songs when using BeatOn

### ISSUE THREAD

**Issue by Arakon** [the-expanse/SideQuest#243]
https://www.reddit.com/r/OculusQuest/comments/cbyvv2/sidequestbeat_on_lag/

For reference.

Summary:
When playing songs via the BeatOn method, they will randomly lag for a very brief moment. If sound is playing at the time, it will crackle some, too.
It's likely not due to "overload" with too many songs, as I only have a total of ~30 installed or so.

**Comment by shaneharris** [comment]
this could be due to apps running int he background, did you try restarting the device? you could also try using an app to clean memory

**Comment by Arakon** [comment]
Yes, it occassionally happens right after reboot too. Unfortunately it seems completely random, I've found no means to reproduce it actively.

**Comment by shaneharris** [comment]
closing as nothing we can do about this.
