### ISSUE TITLE
Feature Request: ADB pull for screenshots/videos

### ISSUE THREAD

**Issue by Arakon** [the-expanse/SideQuest#244]
Just plain copying the files results in corrupted data, only using adb pull works correctly.
So it'd be nice to have a function within the file browser or even a seperate section to download captures directly from /sdcard/Oculus/VideoShots.

**Comment by shaneharris** [comment]
so the file browser is based on adb, it uses adb pull to copy all files across. Does this produce corrupt files for you?

**Comment by Arakon** [comment]
Eh.. I only just now realized that clicking on a file opens a dialogue to download the files.. I always kept right-clicking on it to try and open a menu option for that.
So yeah.. this feature is already existing and I just happen to be blind.
It works fine that way.
