### ISSUE TITLE
Suggestion: Custom themes

### ISSUE THREAD

**Issue by cmdrflexo** [the-expanse/SideQuest#25]
I'm curious if you've thought about making a dark version of the theme, or even a way to define custom colors/styles.
The app could import CSS or have a simple in-app theme editor.

**Comment by shaneharris** [comment]
Hmm maybe an in app css editor could be a nice solution, then we could roll up several themes! that could be really cool!

**Comment by drewbaumann** [comment]
It would be awesome to implement this to use macOS's system preference https://electronjs.org/docs/tutorial/mojave-dark-mode-guide

**Comment by shaneharris** [comment]
dark mode coming soon!
