### ISSUE TITLE
Apps button has wrong tooltip

### ISSUE THREAD

**Issue by nickjohnford** [the-expanse/SideQuest#251]
Looks like the Apps button in the sidebar has a tooltip left over from before

https://github.com/the-expanse/SideQuest/blob/36d507fc55b1e3f15efc52c44f28c64952664bf8/desktop-app/src/app/side-menu/side-menu.component.html#L58-L75

**Comment by shaneharris** [comment]
thank you for this! there was a few there with the wrong one, ive already fixed it in a feature branch and a hotfix release is imminent!
