### ISSUE TITLE
Add shadowsocks to SideQuest

### ISSUE THREAD

**Issue by terry2418** [the-expanse/SideQuest#253]
Please add shadowsocks to SideQuest. We are Chinese，so we cannot access the oculus directly. We also have many people buy the oculus quest. If add the Shadowsocks in SideQuest will make us access easily.

**Comment by shaneharris** [comment]
I would love to add it in! want to connect with me on discord? - https://discord.gg/2bkwecn

Or if you prefer you can send me this info - 
```
    {
      "categories": [
        "Social VR"
      ],
      "description": "Longer description here - don't repeat the summary line here. ",
      "license": "FREE",
      "name": "The Expanse",
      "summary": "One line summary here",
      "webSite": "https://theexpanse.app",
      "icon": "expanse.jpg",
      "packageName": "app.theexpanse.app",
      "apkUrl":"https://cdn.theexpanse.app/TheExpanse.apk"
    }
```

or just make a pull request into this repo - https://github.com/the-expanse/SideQuestRepos.

**Comment by timmmmmmmmm** [comment]
I didn't test it (I have Shadowsocks on my router), but I expect the problem to be that the Shadowsocks app can't run in the background on the Quest. As far as I know you can only run one active app, so if Shadowsocks works it only works when you're in the app itself. But worth giving it a try!

**Comment by shaneharris** [comment]
Going to close this as we only accept app submissions from the developers who made them now
