### ISSUE TITLE
“SideQuest” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by pupshadow** [the-expanse/SideQuest#256]
hello i keep receiving this after updating to 5.1

“SideQuest” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Safari downloaded this file today at 7:51 PM from 
github-production-release-asset-2e65be.s3.amazonaws.com.

**Comment by cvandyke1217** [comment]
I'm also experiencing this issue.
OSX Mojave - 10.14.5

**Comment by srvrguy** [comment]
It's a known issue. Apple added new requirements to application signing in macOS 10.14.5 and up. We are planning to put the fix in place in the next release. For now, all you need to do is the same thing that other unsigned applications require: right-click on the application and select open, then select open at the dialog that shows up. You only need to do this one time, and then it will be marked as "okay".
