### ISSUE TITLE
5 Step Guide should include 'install sidequest'

### ISSUE THREAD

**Issue by kennardconsulting** [the-expanse/SideQuest#257]
For dummies like me!

Lost about 30 minutes because I just started following the '5 Steps' setup instructions without first downloading the (small?) link at the top of the readme.

Perhaps it could be 6 steps with step 1 being 'Install SideQuest'

**Comment by shaneharris** [comment]
this has been added as the first step, thank you!

**Comment by kennardconsulting** [comment]
Looks good. Might want to rename it the '6 Step Guide' though :)
