### ISSUE TITLE
"Enable BeatOn" not available

### ISSUE THREAD

**Issue by DarkMorox** [the-expanse/SideQuest#264]
Hye.

When i click on the BeatOn icon, i'm stuck on "Connecting" and I can't see the "Enable" option.
I try to manually install the beaton apk as an alternative, no more sucess.
I successfully install other APK, so I don't understand what's wrong.

Anyone has already been stucked on "Connecting" status and can help me ?
(SideQuest-Setup-0.6.0.exe)

Anyway, thanks for this fantastic app, keep on good work.
![BOConnecting](https://user-images.githubusercontent.com/53276038/61821947-ba738a00-ae58-11e9-9ef9-03c45103b1a1.PNG)

**Comment by Zartan57** [comment]
Same thing for me, if you want to use BeatOn you can download the 5.0 version of SideQuest.
The version 5.1 have the same issue than the 6.0

When i go to the debugger, i see BeatOn Crash because he can't read the property of some files.
I have that Error message : 
Uncaught TypeError: Cannot read property '1' of null
    at WinParser._processBody (C:\Users\USER\Documents\Oculus\SideQuest-0.6.0-win\resources\app.asar\node_modules\ping\lib\parser\win.js:56)
    at WinParser.parser.eat (C:\Users\USER\Documents\Oculus\SideQuest-0.6.0-win\resources\app.asar\node_modules\ping\lib\parser\base.js:125)
    at C:\Users\USER\Documents\Oculus\SideQuest-0.6.0-win\resources\app.asar\node_modules\underscore\underscore.js:76
    at Function._.each._.forEach (C:\Users\USER\Documents\Oculus\SideQuest-0.6.0-win\resources\app.asar\node_modules\underscore\underscore.js:186)
    at ChildProcess.<anonymous> (C:\Users\USER\Documents\Oculus\SideQuest-0.6.0-win\resources\app.asar\node_modules\ping\lib\ping-promise.js:76)
    at Object.onceWrapper (events.js:273)
    at ChildProcess.emit (events.js:182)
    at maybeClose (internal/child_process.js:962)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251)

i think you have the same error than me.

If someone can fix that it can help greatly.

**Comment by v0ltage120** [comment]
Same problem here... Im on same wifi.. I can ping my quest... I have uninstall and reinstall Beatsaber... same spinning Connecting...

**Comment by VGer2097** [comment]
Hi ! Until this is fixing, go to Emulamer’s Github, download latest BeatOn release and drag and drop it on SideQuest. This works for me.

**Comment by DarkMorox** [comment]
> Edit : DarkMorox orZartan57 , is your Windows is in other language than English ? (like mine is in french... it seems to be a Language issues

Yes Voltage, my Windows OS is in french too<
I added the English language pack, set Windows in English and .......... it works, thanks to you !

**Comment by shaneharris** [comment]
ok this is really interesting thanks for this info, the app is attempting to ping the wifi ip of the headset at that point and should respond when it returns. There is obviously something wrong with the library i use to ping on non english OS so i will look into removing this or replacing it with something better. 

Thanks for all the info on this I will get this sorted for the next release int he next few days. 

As a workaround in the mean time - search "beaton" in the new mods category to install the latest beat on.

**Comment by shaneharris** [comment]
This should now be fixed int he current version
