### ISSUE TITLE
SideQuest Can't Find Quest when plugged directly into USB-C

### ISSUE THREAD

**Issue by 200Tigersbloxed** [the-expanse/SideQuest#265]
Title says all. I plug in Quest into my USB-C port, Windows 10 finds it, says it's ready "Quest is Ready", I'll startup SideQuest, and it will say disconnected.

**Comment by ATechAdventurer** [comment]
Is your quest in developer mode with USB debugging on?

**Comment by 200Tigersbloxed** [comment]
Developer mode wasn't on, testing it again right now.

**Comment by 200Tigersbloxed** [comment]
I turned on Developer mode, still nothing.

**Comment by 200Tigersbloxed** [comment]
You cant use a USB C to USB C, HDMI, USB. It has to go directly into the port. I also had to turn on  Dev mode and Install Oculus ADB.
