### ISSUE TITLE
Error: BeatOn not installed / enabled. Please enable Beat On and ensure yore on the safe wifi as your headset.

### ISSUE THREAD

**Issue by Cooppatness** [the-expanse/SideQuest#266]
need help, whenever i try to download something i get this error message and (Error: BeatOn not installed / enabled. Please enable Beat On and ensure yore on the safe wifi as your headset.) and i cant seem to figure out how to "enabe / instal" BeatOn.  anyone know what happend

**Comment by VGer2097** [comment]
Hi ! I had the same issue trying to enable it using a shared wifi on my iphone. I think this was the reason why this failed. So, to install BeatOn, i just downloaded it on Emulamer’s Github and drag and drop it on SideQuest... This is my fix until i am back to home.

**Comment by shaneharris** [comment]
Hi there!

You can install beat on in a few easy ways. If you use the new sidequest app listings that is the easiest - open "mods" and search `beaton` and click more info and install latest. 

You can also click the beat on logo on the top bar - its the first icon. It will show a switch that when clicked it will install the latest beat on for you. 

I hope this helps!
