### ISSUE TITLE
"Backup SD card data" missing directory

### ISSUE THREAD

**Issue by Zeldon567** [the-expanse/SideQuest#267]
When I try to click the "Backup SD card data" button for a game I receive an error stating that some directory is missing. Any ideas?

**Comment by shaneharris** [comment]
hi there, i did fix a bug related to this recently are you on the latest version 0.6.2? if you are this looks like a regression. Could you let me know what app it is so i can try to recreate?

**Comment by Zeldon567** [comment]
Moss.

**Comment by Zeldon567** [comment]
Huh. It's working now. When I first tried it it was on a fresh install. Maybe it errored out because there were no files in the given directory to back up? Sorry, new to SideQuest.

**Comment by Zeldon567** [comment]
Yeah, that's probably it. Nevermind.
