### ISSUE TITLE
SONG LIBRARY AFTER SIDE QUEST UPDATE

### ISSUE THREAD

**Issue by robcooper2001** [the-expanse/SideQuest#269]
Couldn't update BeatSabre on device.
Unistalled through Side Quest.
Reinstalled. All good... No custom songs of course.

SideQuest update completed, entire custom songs library GONE!!!

**Comment by robcooper2001** [comment]
How can I get it back?

**Comment by shaneharris** [comment]
Hey there! Apologies your having trouble. we prefer to do support like this via discord - https://discord.gg/MNV8Ge 

You could try in the settings screen of sidequest there is a "open main app folder" button, in there youll find a folder called `bsaber` which is the sidequest song store. You can also find a folder on the device called `/sdcard/BeatOnData/CustomSongs` where beat on stores the same songs you can check that. 

Unfortunatly as these are mods we cannot guarantee anything as a beat saber update ( like the one we just got ) can always break things.

**Comment by robcooper2001** [comment]
Shane,
Aha! Turns out Beat Sabre had an update? I got new content anyway. And Sidequest did an update and then wouldn't work. Also, installing BeatOn made Beat Sabre tell me there was an update!! But it wouldn't update. Now it says SideQuest is not compatible with my current version. I uninstalled and reinstalled several times and SideQuest!!
Is there a SideQuest update for BeatSabre?

**Comment by srvrguy** [comment]
Right now there are some compatibility issues with the new Beat Saber update. The old patching method likely will not be updated, so you'll need to move to using Beat On. The latest version of Beat On is mostly compatible, but it does have a few issues like making the update prompt appear. For now, you can ignore that prompt. An update to Beat On is pending that will resolve that issue.

If you have further use issues, please use our Discord for support. The link is in an above comment.
