### ISSUE TITLE
The application "SideQuest" can't be opened: -47

### ISSUE THREAD

**Issue by CRogers** [the-expanse/SideQuest#27]
Get this error on the OS X version of 0.1.1 after extracting and running `SideQuest`:

<img width="532" alt="Screenshot 2019-05-28 at 20 11 02" src="https://user-images.githubusercontent.com/397795/58505417-cdcde600-8184-11e9-8008-556ec1640071.png">

**Comment by shaneharris** [comment]
hey did you download this version? -  https://github.com/the-expanse/SideQuest/releases/download/0.1.1/SideQuest-mac-x64.tar.gz

**Comment by CRogers** [comment]
Yes, it was that link.

**Comment by shaneharris** [comment]
what version of mac os do you have? i dont own a mac myself but i have asked someone with one to try it out and i will report back

**Comment by CRogers** [comment]
I'm on OS X Mohave. I can find an exact version when I get home.

**Comment by shaneharris** [comment]
i have been looking into this - https://github.com/keeweb/keeweb/issues/264 and this could be related. Its not a lot to go on right now but it could lead to a line of inquiry or two

**Comment by CRogers** [comment]
Is there some way I can run this is a console or get some logs for you?

**Comment by shaneharris** [comment]
im sorry i dont have any new information on this yet, the error is really not descriptive. I will keep looking but that error happens before any log files are created. I dont have access to a mac personally which makes thing more difficult

I will keep looking into this and come back to you if i find anything

**Comment by Swooperz** [comment]
I was able to get this to work. I too received the error listed above but then decided to use the built-in Archive Utility for Mac OS, instead of using Winzip - which is what I used first. Winzip does something funky with the tar file, I guess.

Here are the steps (I'm using Mac OS 10.14.4):
1. Uncompress tar.gz file with Archive Utility (Rt-Click file, Open with Archive Utility)
2. Open target folder and CTRL-Click on the Sidequest app and click Open.
3. Click Open again at the Unidentified Developer warning.
4. That's it.

Hope that helps some of you!
-Alan

**Comment by MaxChu719** [comment]
> I was able to get this to work. I too received the error listed above but then decided to use the built-in Archive Utility for Mac OS, instead of using Winzip - which is what I used first. Winzip does something funky with the tar file, I guess.
> 
> Here are the steps (I'm using Mac OS 10.14.4):
> 
> 1. Uncompress tar.gz file with Archive Utility (Rt-Click file, Open with Archive Utility)
> 2. Open target folder and CTRL-Click on the Sidequest app and click Open.
> 3. Click Open again at the Unidentified Developer warning.
> 4. That's it.
> 
> Hope that helps some of you!
> -Alan

I followed your step and it still doesn't work.

**Comment by fascistutopia** [comment]
Getting the -47 error as well on my 2017 MPB running MacOS Mojave 10.14.5.

Also tried what Swooperz suggested (all suggestions, including the Archive Utility and installing the prior version).  

The prior version does run.  (Cleared with Security, etc.)  Current version still fails to open with -47 error.

**Comment by shaneharris** [comment]
More info from an anonymous donor - 
```
the macOS builds aren't signed with a developer certificate, so you need to go into finder and right click > Open on the app to run them
Many people don't know that secret way around Gatekeeper 
```

**Comment by fascistutopia** [comment]
Found a solution:

1. Removed /Users/<USERNAME>/Library/Application Support/SideQuest
2. Right-clicked SideQuest and selected "Open"

It now runs. It can subsequently be opened by a simple double-click.

**Comment by MaxChu719** [comment]
> Found a solution:
> 
> 1. Removed /Users//Library/Application Support/SideQuest
> 2. Right-clicked SideQuest and selected "Open"
> 
> It now runs. It can subsequently be opened by a simple double-click.

It works! Thanks!

**Comment by shaneharris** [comment]
@CRogers does that also work for you?

**Comment by shaneharris** [comment]
closing for now, reopen if need be!
