### ISSUE TITLE
Pavlov obb file not dropping

### ISSUE THREAD

**Issue by JibreelK** [the-expanse/SideQuest#272]
My Pavlov obb file will not drop into the "Drop here" message. I have tried several times and nothing happened. The apk file drops fine though. Thank you.

**Comment by shaneharris** [comment]
this is confirmed a bug, the ui does not show that the obb is transferring but it is actually sending. I will have this fixed in the next version, 

Thanks

**Comment by JibreelK** [comment]
> this is confirmed a bug, the ui does not show that the obb is transferring but it is actually sending. I will have this fixed in the next version,
> 
> Thanks

Okay. Thank you, Shane.
