### ISSUE TITLE
Custom Colors in BeatOn v0.1.1.2 and Beat Saber 1.2.0

### ISSUE THREAD

**Issue by Vasago** [the-expanse/SideQuest#275]
Hello,
due to disabling old method with patching in version BeatOn v0.1.1.2 and Beat Saber 1.2.0 and choosing custom colors how can we change the colors now in BeatOn, please?

Thank you.

**Comment by shaneharris** [comment]
Hi There, 

Beat On has a color option on the mods screen. DO you have the latest version of BeatOn? Search "beat on" in mods and click more info > install latest

**Comment by Vasago** [comment]
Oh I did not know about this option - wow now it works perfectly and even better than before thank you. Is there anything else I should know to update? :)

You can close this one.
