### ISSUE TITLE
Feature request: full and incremental backups

### ISSUE THREAD

**Issue by kitchung** [the-expanse/SideQuest#280]
Hi all,

It'll be nice to have a 1-click option to backup my apps, at which it'll ask to backup APKs, Data, or both. 

It'll also be nice to have incremental backups of APKs and Data when it detects differences or time-based (you haven't backed up in X days).

**Comment by shaneharris** [comment]
Nice idea! i guess incremental could be possible by comparing file stats. This would be a medium undertaking i think and its not on the immediate roadmap. Were open to PRs though if you want to take a shot!

**Comment by shaneharris** [comment]
closing this as not in the roadmap
