### ISSUE TITLE
Support Symbolic link to Beat Saber PCVR CustomSongs folder

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [the-expanse/SideQuest#281]
I don't need or want every song mgmt tool to require its own separate copy of my library.

It would help save space and ensure a consistent library for users that ALSO have PCVR version of BeatSaber.

Please provide an enable-able option to have the SQ beatsaber song folder be a simple symbolic link to the users existing Beat Saber PCVR CustomSongs folder. Lets the users choose the folder to be linked.  Because you won't know exactly where it is.

This will vary for Windows, Linux and Mac.  But it should be possible on all platforms.

**You would want to test AND DECLARE compatibility** to ensure that one library management tool doesn't impact another (like causing renaming of folders or failing to access them).

**Comment by shaneharris** [comment]
Hi There! Sidequest no longer houses a beat saber library and the songs are now sent to BeatOn. It of course stores all the songs on the device so this might not be possible im afraid. 

Thanks very much for your time and consideration!

**Comment by zxsdklfhskyrvk** [comment]
So, can you explain what the bsaber folder in SideQuest is doing with all my music?
