### ISSUE TITLE
Ui issues

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#283]
Any hope of getting light theme to be more like it was with top and side bar being light as well?

Also mods are lumped all toghether and you have to click small "open" on the side to open the descirption to get an idea of what the mod is for.

Also the content area doesn't respond to mouse back button. And back button doesn't get you back to the same position you were in lists that are expanded by the more button on the bottom.

Looks like feature creep is messing with UI cleanliness.

**Comment by retorquere** [comment]
Similarly, infinite scroll makes this kind of interaction hard to use; if you go to the details of an app/mod by clicking "open", if you return, you go back to the state where only the first "page" of results is loaded, even if previously I had loaded more.

**Comment by shaneharris** [comment]
I have replaced the infinite scroll on the listing pages and instead were now using more traditional pagination. It also provides a perma link for individual pages so the back button issues will also be fixed in the next release in a few days
