### ISSUE TITLE
SideQuest 0.6.6 will not run on OSX 10.15

### ISSUE THREAD

**Issue by martinbogo** [the-expanse/SideQuest#284]
I am getting the following error after unzipping and installing 0.6.6:

"SideQuest" is damaged and can't be opened   You should move it to the Trash.

![Screen Shot 2019-08-15 at 6 02 13 PM](https://user-images.githubusercontent.com/251177/63132496-dfa27680-bf86-11e9-9d0c-7993f9618a90.png)

**Comment by martinbogo** [comment]
If I go back one rev to 0.6.5, I get a different error...

The application "SideQuest" can't be opened.

![Screen Shot 2019-08-15 at 6 03 40 PM](https://user-images.githubusercontent.com/251177/63132552-0fea1500-bf87-11e9-894c-75cfa1c9b89c.png)

**Comment by martinbogo** [comment]
My mac is using Mac OS 10.15 Beta, version 19a652h

**Comment by srvrguy** [comment]
10.15 is a beta, and there are currently lots of issues with it and Electron, the framework we use. Once fixes are in place in the upstream tooling we use, then they will be added here. Until then, Catalina is not currently supported.

Feel free to open a new issue if there continue to be issues once the OS is released.
