### ISSUE TITLE
apk installed only showing up in app launcer in 2d

### ISSUE THREAD

**Issue by tedwaltmuf** [the-expanse/SideQuest#287]
Im trying to install the app "VF 2000" from the google play store and the only way I can launch the app is from the sidequest launcher and its in 2d only. it is a vr app that works normally on samsung gear

**Comment by tomtastico** [comment]
Having same problem with OpenMW Android (OMW), although that's a 2D app.

It doesn't show in Unknown Sources, nor in Oculus TV, only in the SideQuest TV launcher?

**Comment by tedwaltmuf** [comment]
Nope, only on sidequest app launcher

**Comment by shaneharris** [comment]
im afraid this is an oculus limitation and not anything that sidequest can change. Only VR apps appear in the unknown sources list. Try this app launcher for organizing and launching all your apps in one place - https://sidequestvr.com/#/app/199

**Comment by tedwaltmuf** [comment]
It is a great app and is not showing up in the unknown sources
