### ISSUE TITLE
I have 800+ Songs on Beat Saber - Crashing

### ISSUE THREAD

**Issue by ChrisDoesStuff2** [the-expanse/SideQuest#289]
So I've downloaded...a lot...of songs...over 800 for that matter. I can play it for a bit then eventually when previewing songs it starts to glitch out and will eventually crash. Is this an issue when previewing songs and not listening to the whole thing or is it more to do with there being too many songs?

**Comment by shaneharris** [comment]
Hi there! This issue might be better served on https://github.com/emulamer/BeatOn instead. Thanks!
