### ISSUE TITLE
Mention that Beat On is not compatible with latest version.

### ISSUE THREAD

**Issue by thgh** [the-expanse/SideQuest#293]
https://github.com/the-expanse/SideQuest/wiki/Beatsaber-update-%23.%23.%23-is-out,-can-i-install-it%3F

https://www.reddit.com/r/sidequest/comments/cx8o69/the_new_beatsaber_is_out_so_mods_are_out_with_it/

**Comment by shaneharris** [comment]
This is moot now as beat on is supported. Thanks!
