### ISSUE TITLE
Getting this issue when I try to drag folder to Sidequest

### ISSUE THREAD

**Issue by Drtrollmiester** [the-expanse/SideQuest#295]
I get this every time I try to drag the Valve folder for Lambda1VR 
![image](https://user-images.githubusercontent.com/54778550/64081300-f0642380-cccc-11e9-82b4-7364e7b6194f.png)

**Comment by shaneharris** [comment]
Hi There! Sidequest does not support drag and drop folders im afraid. Thanks!

**Comment by Drtrollmiester** [comment]
Then what would be your suggestion for using the Lambda1VR program given that the instructions explicitly state that I need to copy game files?
