### ISSUE TITLE
Look into launching apps from app launcher into VR mode aswell

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#30]
They currently launch all black with just audio and leave you locked in.

**Comment by nmcwilli** [comment]
Just tried this out and noticed the same thing - most of the apps launch all black with just audio and leave you locked in. Pokemon GO does launch, but seems to hang at the login screen. 

I tried out Minos Starfighter VR and that actually does work from the app launcher, but then there is no way to view it in VR mode. 

Facebook Messenger actually seemed to work fine from the app launcher too. 

Sorry, just repeating basically what you said - just wanted to let you know that I'm available to help test things if you'd like. 

I can launch these apps from "Unknown Sources" directly - AltspaceVR and pick-up league hockey.

**Comment by nk33** [comment]
is there a launcher for the Quest so i dont have to go through Unknown Sources everytime....this is tedious and it is sometimes not obvious what the app is so you have to read closely...

**Comment by shaneharris** [comment]
https://xpan.cc/a-199

The above app provides a unity based launcher with support for vr apps and 2d apps. I will probably deprecate the sidequest launcher in favor of the above because it works better.

**Comment by nmcwilli** [comment]
Thanks Shane. The unity based launcher is nice. 

Question though - There are some APK's for VR games that are showing up in the 2D section and therefore I can't launch them in VR mode. Is there any way that you can add a "force launch in VR" functionality? Even if the Unity App Launcher is detecting it as 2D? Perhaps limitations there that I'm not aware of, but any of the APK's I'm sideloading are, for the most part, doing that. 

Also, I tried launching some of the GO/Gear titles that appear, like my sideloaded Crisis Vrigade, but I had some troubles with the button mappings. The games under the GO/Gear section do launch in VR though, which is great! 

All of this is awesome work, just providing some feedback regarding my testing.
