### ISSUE TITLE
AltspaceVR is suspending sideloads

### ISSUE THREAD

**Issue by nickjohnford** [the-expanse/SideQuest#300]
AltspaceVR is supposed to be officially releasing on the Quest on the 12th, and have stated that they are "suspending" sideloading until then.
https://www.reddit.com/r/AltspaceVR/comments/d07mwd/suspending_sideloads/

Recommend that it is removed from the list of installable applications.

**Comment by mrconter1** [comment]
I tried to do a quick fix, but apparently, the list of installable applications are stored on the server-side.

**Comment by nickjohnford** [comment]
Closing this as AltspaceVR seems to have been removed from SideQuest.
