### ISSUE TITLE
Relocate data folder

### ISSUE THREAD

**Issue by PashaKagan** [the-expanse/SideQuest#302]
For backup purposes, it would be great to be able to choose SQ's data folder.
Hopefully, it would be possible to place the folder freely instead of using AppData. 

Personally, I'd use my Dropbox folder and sync SQ between my PCs.

**Comment by shaneharris** [comment]
@PashaKagan this could be possible, but does present challenges across multiple OS's. What has worked for others though is to create a symbolic link instead the current backups folder and that should allow you to relocate it.

**Comment by srvrguy** [comment]
Symbolic links don't work in Windows. For Windows, you'd want to use NTFS junctions. A tool to create and manages junctions is at https://docs.microsoft.com/en-us/sysinternals/downloads/junction.

What if a preference is added to set the data folders to a user-defined location? If the preference is empty, use the default we have been, but if it is set, then we defer to that location? Obviously, that should only apply to things like backups, not the tools we download or other background data.

**Comment by PashaKagan** [comment]
> What if a preference is added to set the data folders to a user-defined location? 

That would be ideal. Choosing a data folder during installation/settings, instead of just placing it in a pre-defined location by default. Not a developer, but setting a base folder from a config file sounds somewhat doable IMHO.

**Comment by shaneharris** [comment]
This feature is in since version 0.7.1 i believe
