### ISSUE TITLE
Feature Request: Allow for adb command presets

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#303]
make an adb command preset possible so users can input a set of commands and save them in sidequest, for example these commands to record at a better resolution and better quality: 

```
    adb shell "setprop debug.oculus.capture.width 1536"
    adb shell "setprop debug.oculus.capture.height 1536"
    adb shell "setprop debug.oculus.capture.bitrate 160000000"
    adb shell "setprop debug.oculus.foveation.level 0"
    adb shell "setprop debug.oculus.foveation.usev2 1"
```

you could then just run all of them at the click of a button

EDIT: I am referring to the adb commands section with wifi adb and things like that

**Comment by shaneharris** [comment]
This has been added and will be in sidequest 10
