### ISSUE TITLE
Bring back old way of adding custom songs?

### ISSUE THREAD

**Issue by Vasago** [the-expanse/SideQuest#305]
Hi, before the beatOn there was another way of adding custom songs within SideQuest - can you add this way back please when BeatOn is no longer supported now?

**Comment by ryanlauderbach** [comment]
Sadly that would still be against Oculus's new Terms of Service which made them discontinue BeatOn in the first place. Info here: [https://www.reddit.com/r/OculusQuest/comments/dddjb9/beaton_support_ending_illicit_mods_are_now/]

**Comment by Vasago** [comment]
Why not make it as "learning" option for enyone to use with some message the dev is not responsible for it? Just let users decide if they want to use it or not?

**Comment by shaneharris** [comment]
Hi there! i dont think claiming it was for learning would quite cut it from a legal perspective, or else copyright law would have gaping holes in it. Regardless, BMBF exists now.
