### ISSUE TITLE
Add option block auto-update?

### ISSUE THREAD

**Issue by douglasware** [the-expanse/SideQuest#307]
I appreciate the diligence around Beat On, but I do not want the 'upgraded' SideQuest. Is there a way to prevent the automatic update?

**Comment by Vasago** [comment]
Turn off internet during startup of app as a workaround ...

**Comment by lechalet** [comment]
hey, how to install beaton right now ? 
I hope You resolve this quikcly

**Comment by shaneharris** [comment]
Closing in favour of #312
