### ISSUE TITLE
Can't delete Beat Saber

### ISSUE THREAD

**Issue by mruhjacob** [the-expanse/SideQuest#308]
For whatever reason, after many attempts to connect my quest to side quest, it wont connect. I need to delete BeatSaber and now I cant because it wont connect. Any way around this?
<img width="650" alt="Screen Shot 2019-10-05 at 2 14 50 PM" src="https://user-images.githubusercontent.com/56203215/66259034-8a126b00-e77a-11e9-9000-8848a7e7291b.png">

**Comment by Vasago** [comment]
Turn on again developer mode.
