### ISSUE TITLE
No "Authorise Device" dialog in Quest v0.9 using SQ 0.7.2 or SQ 0.6.7 on Linux

### ISSUE THREAD

**Issue by reconlap** [the-expanse/SideQuest#309]
Hi, 
  Guess there was an update to the Quest OS recently, I had to re-enable developer mode to see the "Unsupported Sources" that I had previously installed. Did that and all seemed fine. 
   Then I tried to connect to quest on my Linux xubuntu 18.4 through USB. I get the "Unauthorized: Put your headset on and select always allow ... "
    When I put the headset on there is no "Authorization" Dialog to click. I tested in windows 10 and it connected fine and i got the  "Authorization" Dialog. 

Hope this helps and feel free to ask for any details you might need.

Regards

**Comment by boobin** [comment]
I just started playing with sideloading and i have the same kind of issue. On a fresh factory reset of my headset, i can enable dev mod and connect adb once, but after disconnecting it, i can't get the adb link back.

- disable/enable dev mode doesn't help
- change cable/port doesn't help
- delete adb key doesn't bring the authorization popup back
- in developer mode, i don't get the file transfer popup either, but i get it if i disable dev mode

Ubuntu 19.10

$ adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
1PASH9B7KS9283	no permissions (user in plugdev group; are your udev rules wrong?); see [http://developer.android.com/tools/device.html]

**Comment by boobin** [comment]
Finally the error message is self explanatory, you need to specify a udev rule to get file permission on the device. A good step by step guide can be found here: http://www.janosgyerik.com/adding-udev-rules-for-usb-debugging-android-devices/

**Comment by shaneharris** [comment]
closing as out of scope of sidequest ( also affects adb ) and also a solution exists!
