### ISSUE TITLE
Ability to type/copy/paste into headset

### ISSUE THREAD

**Issue by 0xdevalias** [the-expanse/SideQuest#31]
Currently the Oculus Quest standard keyboard has no concept of copy/paste, nor can you type from the companion app 'into' the headset (like the PS4 app allows). This makes for a terrible user experience when trying to login to services that you use secure passwords/password managers for.

I was doing a little cursory googling last night, and it sounds like you may be able to achieve this through `adb`, which makes me think it would be a neat feature to include here, at least until (if) they ever implement it in a better 'native' way.

- https://stackoverflow.com/questions/37173733/paste-text-on-android-using-adb
- https://stackoverflow.com/questions/25782199/does-adb-shell-input-text-simulate-software-keyboard-input/25910670
- https://android.stackexchange.com/questions/19710/is-it-possible-to-write-to-a-devices-clipboard-using-adb?newreg=0bd8b0c2a8be45c889485ffb9b2a6440

I haven't explored this yet, but those SO's seem to imply that we could send text with:
```
adb shell input text [text]
````

And since 'api 24', should be able to send a 'paste' command with:
```
adb shell input keyevent 279
```

While I was initially looking to copy/paste 'into' the headset, for the 'I need to type a big password' use case, it may be sufficient to just 'send' the string into the UI. Then I can do any password manager copy/pasting on my laptop, and send it in.

I'll explore this a bit later and see if it actually works as I expect/hope and update back here.

**Edit:** Created a SO question/answer for this general problem: https://stackoverflow.com/questions/56386237/is-it-possible-to-copy-paste-type-from-an-app-in-the-oculus-quest-headset/56386580#56386580

**Comment by briancherin** [comment]
I tried the ADB commands with my Quest. Using "adb shell input text [text]", I was able to send a very small string ("hi") successfully into a text field on the Quest, but for a longer string, only the first few characters showed up on the Quest. It seems that the Quest recognizes this as an external form of text input, but the characters are coming in too fast for it to process them all into the UI. I only tried this briefly.

**Comment by shaneharris** [comment]
great idea! ill work on this right away

there might be some other convenient ADB things we can do it would be nice to wrap up in a convenient UI

Thanks!

**Comment by 0xdevalias** [comment]
Just had a quick play with clipper and trying to copy/paste.. didn't work very well for my into the instagram app.

But I can see that `adb shell input text` worked, though as @briancherin mentioned, it drops characters. If we called that from a bash script/similar to 'slow down the typing', that'd probably work.

**Comment by shaneharris** [comment]
ha nice! I did literally the same thing basically!
```javascript
           let inputCharacters = ()=>{
                let character = characters.shift();
                return this.setup.adb.shell(this.setup.deviceSerial, 'input text "'+character+'"')
                    .then(adb.util.readAll)
                    .then(res => {
                        if(characters.length){
                            return inputCharacters();
                        }
                    });
            };
            inputCharacters()
                .then(()=>{
                    // done
                });
```
Well i don't have a timer i wait for each request to respond. seems to work well.

**Comment by shaneharris** [comment]
This is now implemented in the bsaber branch, due to be merged into master soon!

**Comment by 0xdevalias** [comment]
Woo!
