### ISSUE TITLE
Bug: Permission issue displayed as unauthorized connection status

### ISSUE THREAD

**Issue by AlexanderDahmen** [the-expanse/SideQuest#316]
I am using SideQuest on Ubuntu 18.04, connecting to an Oculus Quest headset via USB.
Today, the connection status would show "Unauthorized" and instruct me to allow the connection from the headset.

However, the actual issue was a Linux permission error, revealed by running the ADB command `adb devices`:
```
List of devices attached
[[Serial-No]] no permissions (user in plugdev group; are your udev rules wrong?); see [...]
```

The relevant code related to this bug is located in [adb-client.service.ts:183](https://github.com/the-expanse/SideQuest/blob/982ea69dc332a4c2f47fb93e5ef1a9bf195f6ffe/desktop-app/src/app/adb-client.service.ts#L183), function `async connectedStatus()`:

```typescript
        return this.adbCommand('listDevices')
            .then((devices: any) => devices.filter(device => device.type !== 'offline'))
            .then(devices => {
                if (devices.length === 1) {
                    this.deviceSerial = devices[0].id;

                    // BUG: devices[0].type is undefined after permission error
                    if (devices[0].type === 'device') {
                        return ConnectionStatus.CONNECTED;
                    } else {
                        // --> Default to unauthorized despite error in response
                        return ConnectionStatus.UNAUTHORIZED;
                    }
                } else {
                    if (devices.length > 1) {
                        return ConnectionStatus.TOOMANY;
                    } else {
                        return ConnectionStatus.DISCONNECTED;
                    }
                }
            })
            .then(status => {
                this.updateConnectedStatus(status);
                requestAnimationFrame(this.connectedStatus.bind(this));
            })
            .catch(err => {
                requestAnimationFrame(this.connectedStatus.bind(this));
            });
```

This function does not check for the given permission error, and thus defaults to `ConnectionStatus.UNAUTHORIZED` instead of picking up and showing the permission error.

Thank you and have a nice day,
Alexander Dahmen

**Comment by shaneharris** [comment]
Thanks for this detailed information. I wonder is checking for `device[0].type` being falsey and showing this. It probably is. Not ideal but this issue only affects linux i guess.

**Comment by kmorinCL** [comment]
@AlexanderDahmen did you succeed in connecting your Quest? If yes, how did you do?

**Comment by AlexanderDahmen** [comment]
@kmorinCL
Yes, I did succeed by running SideQuest as sudo.

Relevant XKCD:
![](https://imgs.xkcd.com/comics/sandwich.png)

**Comment by kmorinCL** [comment]
Great, it works, thanks a lot ;)

**Comment by shaneharris** [comment]
OK  sudo is probably a better option here as its more reliable that the hacky option i was considering. I will update the docs.

**Comment by henwill8** [comment]
@AlexanderDahman how did you run it in sudo? Terminal doesnt recognize sidequest as a program so I cant do "sudo sidequest" in the right directory

**Comment by srvrguy** [comment]
If you're on Linux, you just need to run the SideQuest executable. Windows and macOS are whole different things and this issue is not applicable.

A better solution for Linux is to add the correct rule for udev so you don't run applications as root. See the   info over at https://stackoverflow.com/a/53887437 for how to do that. I don't have my Quest handy, so I can't give you the IDs to use, but that link will tell you what to do to find them.

**Comment by henwill8** [comment]
@srvrguy I ran the command with the ID's and ended up with this:
The command I ran: SUBSYSTEM=="usb", ATTR{idVendor}=="2833", ATTR{idProduct}=="0186", MODE="0666", GROUP="plugdev"
The output: ATTR{idVendor}==2833,: command not found

**Comment by srvrguy** [comment]
It's not a command. You need to add rules to a file in the udev directory and then get the rules reloaded and it should work.

**Comment by henwill8** [comment]
@srvrguy Where is the udev directory located at? I used the command to open udev, pasted the rule in but couldn't find a way to save it and it ended up as a swap file. Here is a video of my attempt...
![simplescreenrecorder-2019-12-24_14 46 00](https://user-images.githubusercontent.com/43818215/71425657-ca3c0800-265c-11ea-8e4f-2d33d73ce8df.gif)

**Comment by srvrguy** [comment]
Helping with that is somewhat beyond the scope of this project. You might be best helped by finding a support source for your linux distribution.

**Comment by shaneharris** [comment]
Decided to resolve this finally within sidequest. As part of multi device support this is a relativly easy addition to make.

**Comment by shaneharris** [comment]
added along with multi device support in ver 10, releasing soon.
