### ISSUE TITLE
Adding F-Droid repositories fails with "JSON parse Error"

### ISSUE THREAD

**Issue by Elettrotecnica** [the-expanse/SideQuest#318]
I am not sure this is supposed to work, but as it is claimed to be possible to use F-Droid repositories, I have tried with a few of those mentioned in https://forum.f-droid.org/t/known-repositories/721, in particular:
- https://f-droid.org/repo?fingerprint=43238D512C1E5EB2D6569F4A3AFBF5523418B82E0A3ED1552770ABB9A9C9CCAB
- https://guardianproject.info/fdroid/repo?fingerprint=B7C2EEFD8DAC7806AF67DFCD92EB18126BC08312A7F2D6F3862E46013C7A6135
- https://fdroid.libretro.com/?fingerprint=3F05B24D497515F31FEAB421297C79B19552C5C81186B3750B7C131EF41D733D

All of them fail with  "JSON parse Error"

I am running Debian buster and latest SideQuest 0.7.4

**Comment by shaneharris** [comment]
Hi there! It looks like the fingerprint url parameter is causing issues, the app will simple append `/index-v1.json` to the end of the url which would malform the urls above. For instance `https://guardianproject.info/fdroid/repo?fingerprint=B7C2EEFD8DAC7806AF67DFCD92EB18126BC08312A7F2D6F3862E46013C7A6135` becomes `https://guardianproject.info/fdroid/repo?fingerprint=B7C2EEFD8DAC7806AF67DFCD92EB18126BC08312A7F2D6F3862E46013C7A6135/index-v1.json`. Without that URL property I was able to add the guardian repo but I could not open any of the app listing pages. 

![image](https://user-images.githubusercontent.com/6830845/67760466-4c32fa80-fa39-11e9-9560-fa84555c4bcf.png)

Unfortunately the fdroid support has been deprecated for a while and Im not sure if well be adding any improvements there, its more lightly to be removed in a future release ( im just afraid to do it incase i upset a lot of people ).
