### ISSUE TITLE
Cant install Sideuqest

### ISSUE THREAD

**Issue by Crungy** [the-expanse/SideQuest#326]
When I try and install sidequest I just get an error that says installation aborted setup was not completed successfully. I tried turning off my antivirus to try and fix it but it's not working. Please help

**Comment by ChibiBlaziken** [comment]
https://github.com/the-expanse/SideQuest/wiki/Force-Uninstaller-for-SideQuest

Try running this uninstaller to make sure all residue of the old folders
and files are removed before installing sidequest again
