### ISSUE TITLE
Dragging .obb file into the upload box does nothing

### ISSUE THREAD

**Issue by victorswkyip** [the-expanse/SideQuest#327]
I built a custom app using Unity3D and oculus integration for the Android platform. I enabled split application binary, so I have an .obb file.

When I drag and drop .obb file, there doesn't appear to be any interaction. Nothing installs, and there is no action. 

Anyone else?

**Comment by shaneharris** [comment]
Hmm dragging obb files seems to work ok on this end, what version of SIdeQuest are you using? Are you dragging the file to the top left corner, the SideQuest logo?

**Comment by victorswkyip** [comment]
Instead of dragging and dropping, I clicked the "Install APK file from folder" icon instead and browsed to my .obb. I received an error saying "Invalid OBB"
The OBB was generated from a build in Unity3D.
I'm on a mac, using SideQuest v7.6 on Oculus Quest latest version

After research, I'm lead to believe I need to enable permissions to read the obb expansion file by changing the manifest file, but still have not succeeding in exactly doing that. 

So the issue isnt with Sidequest.

**Comment by shaneharris** [comment]
Ok so in order for SideQuest to be able to put the obb in the correct place it must have specific naming. This is usually the case for almost everything but here is the info:

It must match this regular expression - `/main.[0-9]{1,}.[a-z]{1,}.[A-z]{1,}.[A-z]{1,}.obb/`

Example: `main.1.com.mycompany.myapp.obb`

where the package name is `com.mycompany.myapp`

This must be the issue in this case as it is the only place int he code that produces the error "Invalid OBB" so ill close this, feel free to re-open or create a new issue if need be though!

https://github.com/the-expanse/SideQuest/blob/864630898ba693b9fb510a9367589a0f21b356b1/desktop-app/src/app/adb-client.service.ts#L76-L79
