### ISSUE TITLE
Installations fail on Moverio BT-300

### ISSUE THREAD

**Issue by knosalaa** [the-expanse/SideQuest#328]
Is there specific library that is missing on Moverio device? Can you provide instructions for successful install and execution of .apk's on this device (in title of this project)
Thank you in advance

**Comment by shaneharris** [comment]
Hi there, I actually have never tested it I was just told by a user that it did. It could be a drivers issue though. SideQuest works with any android device as long as the correct ADB drivers are installed and the device is in dev mode

**Comment by knosalaa** [comment]
My device is in development mode, Moverio however has google non-certified version and intel cherry chip. Any chance I could get some info for the user that made it work on his/her device?
Thanks a lot


Sent by Pony Express

**Comment by srvrguy** [comment]
You can use SideQuest to install and manage applications on the headset, but you will not be able to install Oculus Quest applications. Any applications you install via SideQuest will need to be built for your specific device.

The Moverio BT-300 uses an Intel Atom chip, which is a very different CPU (x86 32 bit according to Epson's site). The Oculus Quest is running a Qualcomm Snapdragon CPU (ARM 64-bit). While some basic applications should work fine across both devices (mainly applications targeting only the Android API), more advanced applications will have to target Android x86 specifically.

**Comment by knosalaa** [comment]
Which side of apps should I try Oculus Go, Rift or something else?
Thanks for your help!

Sent by Pony Express

**Comment by shaneharris** [comment]
Ah this means none of the applications on SIdeQuest will actually work, I should update the repo description. SideQuest can be used to load apps onto the device, but only apps intended for the device.
