### ISSUE TITLE
Add native macOS traffic lights

### ISSUE THREAD

**Issue by NewsGuyTor** [the-expanse/SideQuest#331]
SideQuest feels very un-native on macOS due to how its window management features are placed on the wrong side of the window with custom icons. It should implement proper traffic lights instead:
![alt text](https://cdn.dribbble.com/users/8915/screenshots/1698401/dribbb.png)

It's pretty simple to implement:
https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#alternatives-on-mac
https://jaanus.com/electron-window-title/

**Comment by shaneharris** [comment]
Thank you! Given the latest minimal design of the sidequest desktop app im afraid space is very limited. We are not as concerned with the conventions on the mac os operation system as we are with a consistent user experience across all platforms, it is for this reason that we cannot implement an OS specific titlebar. The sidequest title bar is unique to sidequest and does not necessarily conform to any one OS style. 

Thanks!
