### ISSUE TITLE
game sorting reverts to "hot" on page 2

### ISSUE THREAD

**Issue by nickjohnford** [the-expanse/SideQuest#332]
If you switch to "recent" (for example) and then move to page 2, it will go to "hot" page 2 instead of "recent" page 2.

**Comment by scruffynerf** [comment]
By name only works on page 1, page 2 fails to load at all.  App or Web

**Comment by shaneharris** [comment]
thanks for this, i will look into this right away

**Comment by shaneharris** [comment]
These issues should now be resolved, thanks for your help and apologies for any inconvenience!
