### ISSUE TITLE
Please continue creating Win32 apps

### ISSUE THREAD

**Issue by Pfreaky** [the-expanse/SideQuest#333]
Hello,

I am using SideQuest on a Windows10 32bit tablet so I can use SideQuest and ADB OTG, but now I can't use version 8 since the 32bit version is not available anymore. Would you please consider creating a 32bit version so I can keep using my tablet?

Thanks :)

**Comment by shaneharris** [comment]
Hi there, SideQuest now has 64bit dependencies which makes this quite tricky. It can be very taxing to support different architectures across different platforms. I would highly recommend you move towards a 64 bit solution as we will not be able to continue offering a 32bit build any longer. 

That being said I don't like to leave you out in the cold completely, so I have made a 32bit portable build of the upcoming 0.8.4 release which you can download below. Please be aware you will not be able to use the streaming feature as this relies on 64bit dependencies. Your tablet will need to be at least 1280x720 resolution to use this version of sidequest. 

https://cdn.glitch.com/ff45dc69-7b18-474a-8e82-6b8dc134ddd5%2FSideQuest-0.8.4-ia32-win.zip?v=1577379819612
