### ISSUE TITLE
Setup Win 0.8.2 Installation Aborted

### ISSUE THREAD

**Issue by DarknessFX** [the-expanse/SideQuest#335]
Hi, 

The new version 0.8.2 isn't installing on my machine, I select All Users and the default path folder, the Setup stop at 40% where the setup labels changed to "Installation Aborted - Setup was not completed successfully".

I've tried to run it as Admin with the same problem and tried to clean up the %temp% folders too.

0.8 and 0.8.1 installed without problems.

Thanks

**Comment by ChibiBlaziken** [comment]
See here for such issues

https://github.com/the-expanse/SideQuest/wiki/Force-Uninstaller-for-SideQuest

It should get you sorted

**Comment by DarknessFX** [comment]
Thanks, the Uninstaller did work and now the 0.8.2 installed successfully.

**Comment by ChibiBlaziken** [comment]
Glad I could help
