### ISSUE TITLE
Stopped releasing zipped version of SideQuest for Windows?

### ISSUE THREAD

**Issue by kblood** [the-expanse/SideQuest#336]
SideQuest has since the beginning never installed without failing half way through. That still happens, but now its only this buggy installer version of SideQuest that gets released. Can we get a zipped version released again? Since I have stopped expecting the installer issue to ever get fixed at this point. I am on Windows 10 64 bit btw.

**Comment by ChibiBlaziken** [comment]
If your install is failing halfway that means residue files are remaining
in there is a fix for it, you just have to run our Force installer located
in the FAQ page at

https://github.com/the-expanse/SideQuest/wiki/Force-Uninstaller-for-SideQuest

**Comment by kblood** [comment]
That did work, thanks a lot :)
