### ISSUE TITLE
Feature Request: Add expanded backup options via adb

### ISSUE THREAD

**Issue by bverkron** [the-expanse/SideQuest#338]
Many apps / games cannot be backed up or resorted with SideQuest but can via `adb backup` & `adb restore` as described here. https://www.reddit.com/r/OculusQuest/comments/ej46ar/psa_how_to_backup_restore_save_games_that/

Would be great to have an option in SideQuest to facilitate this method so users (especially inexperienced or non-technical ones) don’t have to use the more complicated command line methods.

**Comment by shaneharris** [comment]
This seems to be a deprecated feature so I don't see much sense in adding it - https://www.xda-developers.com/adb-backup-and-restore-depreciated/

We also have a decent backup/restore all option that works well for users.

**Comment by bverkron** [comment]
Fair point on the possible deprecation.

_"We also have a decent backup/restore all option that works well for users."_
For "supported" games it works well, yes. However there are many games that aren't captured with the current backup mechanism. Is there a way to accomplish what adb does without using adb itself?

**Comment by shaneharris** [comment]
@bverkron not afaik. We use adb as the only interface to the device and im unaware of a way to get access to files/packages in another reliable way that makes sense.
