### ISSUE TITLE
How to sideload shared libraries?

### ISSUE THREAD

**Issue by 0xdevalias** [the-expanse/SideQuest#34]
I was looking at the possibility of loading the PS4 remote play app into my Quest, but when I try and do so, I get the following error:

```
Error: /data/local/tmp/_stream.apk could not be installed [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/com.playstation.remoteplay-1: Package com.playstation.remoteplay requires unavailable shared library com.playstation.remoteplayident; failing!]
```

A little googling lead me to a few forums/etc (eg. [this one](https://www.redmondpie.com/how-to-get-ps4-remote-play-on-any-android-phone-or-tablet-tutorial/)  that suggest you need to download a few extra things, and install them too:
- com.playstation.playstationcertified.jar
- com.playstation.remoteplayident.jar
- etc

The general way to do this seems to be to copy the files into `‘/system/etc/permissions/` and similar locations, which google says I should be able to do with `adb push`, but in trying to do so, it tells me it's a read only filesystem:
```
⇒  adb push com.playstation.playstationcertified.xml /system/etc/permissions
adb: error: failed to copy 'com.playstation.playstationcertified.xml' to '/system/etc/permissions/com.playstation.playstationcertified.xml': remote couldn't create file: Read-only file system
com.playstation.playstationcertified.xml: 0 files pushed. 0.1 MB/s (311 bytes in 0.004s)
```

Is there a general way to install these sorts of things without having to resort to rooting? And is that something SideQuest does/can do?

I naively tried `adb root`, but that doesn't work with production builds:
```
⇒  adb root
adbd cannot run as root in production builds
```

**Comment by shaneharris** [comment]
yes it looks like pushing system to the `/system` path would not be possible without a rooted device. I dont think this would be covered int he scope of SideQuest as it is more aimed at users with little or no knowledge about unlocking bootloaders, sideloading firmware and roms and enabling root access. 

Maybe someone else can cover this in a derivative version!

**Comment by 0xdevalias** [comment]
I was more hoping for a 'without rooting' method, but I guess that's probably not possible at this stage.

How do these extra libraries get installed in 'normal' android cases? Is it something a privileged part of the system/play store manages?

**Comment by 0xdevalias** [comment]
Taking a different route, I decided to look into whether there is a way to not have to install the shared libs, but to 'inline' them into an apk instead.

I [had trouble](https://github.com/iBotPeaches/Apktool/issues/1719#issuecomment-497734835) with using `apktool` on the apk that requires the shared libs, but from a little googling, it sounds like if/when that works, we should see a `<uses-library>` element in the `AndroidManifest.xml`:
- https://developer.android.com/guide/topics/manifest/uses-library-element
- https://stackoverflow.com/questions/3164908/how-to-add-system-permission-file-system-library-to-android/11360936
```
<uses-library android:name="com.example.android.tictactoe.library"/>
```

The above SO describes exporting a class to an external library .jar, and adds a permissions `.xml` file in `/system/etc/permissions`, which points to the shared lib location. So that sounds like if we could write those permissions then we could point to wherever (including writable locations like the sdcard) to load our shared library (probably not likely without root/an 'official' install..? But maybe possible through a custom installer?)

But.. since they exported a class to use as a shared lib.. i'm wondering whether we can 're-import' those shared libs to create a 'fat-apk' that doesn't rely on any shared libs. `apktool` can edit/repackage apk's.. so building a copy [that gets around the crash](https://github.com/iBotPeaches/Apktool/issues/1719#issuecomment-481360518) and seeing if we can decompile this apk would be my first step.

Alternatively, and potentially easier to test: Find/create a simple apk that requires an external lib, then attempt to 're-inject' that into the apk itself.

**Comment by 0xdevalias** [comment]
After [patching](https://github.com/iBotPeaches/Apktool/issues/1719#issuecomment-481360518) `apktool`, I could get enough of it to decompile to confirm my theory:
`AndroidManifest.xml:10`
```xml
<uses-library android:name="com.playstation.remoteplayident"/>
```

Hit a different error with it that i'm not sure how to solve/progress with for now, so don't have a 'clean' decompile to attempt to 're-inject' the lib with.. but.. so far.. theories are pointing to possible (without having to root the device)

**Comment by 0xdevalias** [comment]
After reading a bit deeper, apparently you can [install the basic app without controller support](https://wccftech.com/ps4-remote-play-app-android-device/) just with standard sideloading. Though now when I get into the app and attempt to sign in, it uses the browser + deep linking, which isn't supported.. so I guess we kind of get blocked here:
- https://forums.oculusvr.com/developer/discussion/71958/oculus-browser-does-not-open-deep-links-on-oculus-go
- https://developer.android.com/training/app-links
- https://developer.oculus.com/documentation/platform/latest/concepts/dg-deeplinking/

Apparently we can launch intents via `adb`:
- http://www.xgouchet.fr/android/index.php?article42/launch-intents-using-adb

But the authorisation code + associated params is pretty long, so it would probably be impractical without being able to copy it from the headset back out to the PC; which I'm not sure we have any way of doing..?

**Comment by 0xdevalias** [comment]
Now here is a neat accidental find! Chrome DevTools while plugged into my rift:
`chrome://inspect/#devices`
![image](https://user-images.githubusercontent.com/753891/58723291-0c7dcd80-841d-11e9-82ca-879aa3f037ad.png)

This seems to have an inspect window per 'open tab' in my headset
![image](https://user-images.githubusercontent.com/753891/58723347-2f0fe680-841d-11e9-9068-c4418a7da0c8.png)

That probably means that you could also use the Chrome DevTools protocol to programatically access this info, which would then allow you to get the auth URL's, extract the relevant intents, and then trigger them via `adb`.
