### ISSUE TITLE
no chocolatey installation package

### ISSUE THREAD

**Issue by BananaAcid** [the-expanse/SideQuest#340]
Would be helpful to have a [chocolatey installation package](https://chocolatey.org/) for sidequest. Would make installation easier, since a lot of software is reachable through that installer.

**Comment by digitalcoyote** [comment]
I have an AU repo, I'd be willing to look into maintaining a package for this project (no changes to current release process).

**Comment by digitalcoyote** [comment]
I've got a version in the moderator queue (https://chocolatey.org/packages/sidequest) it may take a bit to get it approved. After that, my AU repo should keep it up to date. If the maintainers create and accoung, let me know and I can grant you management permissions for the package (de-list problematic versions, push new updates etc.)

**Comment by shaneharris** [comment]
HI there, Im not sure we want to maintain this on our end, happy to allow you to though. Closing as there is no action currently

**Comment by BananaAcid** [comment]
Btw: "This package ( chocolatey ) was approved by moderator gep13 on 23 Jan 2020."
