### ISSUE TITLE
Can I pay to get an ad-free version?

### ISSUE THREAD

**Issue by retorquere** [the-expanse/SideQuest#343]

**Comment by shaneharris** [comment]
Hi there, if you have ever donated in the past to sidequest then just let me know your sidequest email / name in a DM on discord if you like. 

On the other hand we have a [patreon ](https://www.patreon.com/SideQuestVR) tier for this. 

If you have also contributed to sidequest with content, by helping on discord or by contributing to the codebase I can also get you setup.

**Comment by retorquere** [comment]
I think I may have done a (very) little thing on SQ in the past, but the Patreon tier sounds like just what I want, thanks!

**Comment by shaneharris** [comment]
This constitutes a contribution - https://github.com/the-expanse/SideQuest/pull/163. Let me know your sidequest email.

**Comment by retorquere** [comment]
That's a *really* small contribution... emiliano.heyns@iris-advies.com

**Comment by shaneharris** [comment]
Cool! Sorry i didn't mean for you to post it publicly, i have deleted it to protect your personal info. I have also setup sidequest premium on your account. Thanks again!
