### ISSUE TITLE
Wifi should be available if there is a last known IP

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#344]
Maybe even with an IP entry field if it has changed/never connected before. It should skip the `adb tcpip 5555` part and just attempt the `adb connect <IP_address>` to gain a connection without having to connect the headset. This could still fail if the headset has restarted but could prove useful in a lot of cases.

**Comment by tchesket** [comment]
I don't know for sure, but I believe this may be a limitation of adb itself, and not something that can be worked around.

**Comment by RedBrumbler** [comment]
I believe the adb connect works if the headset is in the adb tcpip state if that makes sense, so this could work from what I know about it

**Comment by shaneharris** [comment]
yeh @RedBrumbler is correct here, you can issue adb connect if the headset has not been restarted or dev mode disabled and tcpip mode is still enabled

**Comment by shaneharris** [comment]
implemented in the next update.
