### ISSUE TITLE
TVAppRepo Won't Open Game

### ISSUE THREAD

**Issue by Code-Babylon** [the-expanse/SideQuest#347]
I installed TVAppRepo to play Fate Grand/Order on my Quest, but whenever I try to play it, the game won't open and I see just the environment around me. I tried uninstalling the game, reinstalling it, adding the file directly to the downloaded apk folder, but the game still won't load.

Am I doing something wrong or can TVAppRepo only run certain apks?

**Comment by shaneharris** [comment]
Hi there, i'm afraid this is outside of the scope of SideQuest, maybe you could raise an issue on their github - https://github.com/ITVlab/TvAppRepo
