### ISSUE TITLE
Repository list in "Manage Page" only loading first 20-30 repos

### ISSUE THREAD

**Issue by jamesalbert** [the-expanse/SideQuest#348]
Noticed this today setting up github releases. Looks like a pagination issue. I can't scroll in this dropdown either. I went into dev console and confirmed it's only loading these repos.

![Screen Shot 2020-01-18 at 5 19 37 PM](https://user-images.githubusercontent.com/1617698/72672979-43d6d400-3a18-11ea-82a5-122f14c51655.png)

**Comment by shaneharris** [comment]
yes indeed it does look like a paging issue, ill need to add a more section down the bottom there. 

As a workaround you can edit one of the options to the repo of your liking and then submit, aslong as it is the same spelling and case it will work ok. 

thanks for reporting!

**Comment by jamesalbert** [comment]
Nice, I just renamed my release repo to "1-<reponame>" 😎

np, thanks for the quick response

**Comment by EloiStree** [comment]
> Nice, I just renamed my release repo to "1-<reponame>" 😎

Yeah don't work with my nomenclature : 
![image](https://user-images.githubusercontent.com/20149493/73704521-a0621080-46f3-11ea-8fa8-7dedea6a048f.png)
Will wait for the fix ^^.
