### ISSUE TITLE
[Suggestion] adb logcat

### ISSUE THREAD

**Issue by jesusatgar** [the-expanse/SideQuest#350]
It would be nice to have a user-friendly logcat interface. Some features could be search by text, filter by Debug, Error and Info messages, and so on.

**Comment by shaneharris** [comment]
Added in the latest version, releasing soon. Here is a preview:

![image](https://user-images.githubusercontent.com/6830845/76164218-099ad080-6145-11ea-9024-3b45e3a77573.png)
