### ISSUE TITLE
[Feature Request] Additional "My App Updates" button

### ISSUE THREAD

**Issue by Bluscream** [the-expanse/SideQuest#351]
One of the key selling points for SQ for me is the ease to use which includes the library and update functions. I always find it a bit fiddling to provide such a great feature but hide it kinda deep in the menus. Instead i would like a additional small button in the toolbar which could also indicate the amount of updates available with a badge. that way it's just one quick look after connecting the quest, that's needed to see if there's anything requiring attention.

Note: I know that there are already too many buttons up there but i would suggest switching out another button for this one as it also serves an additional purpose. I'd probably suggest moving the "Install APK from folder" button into the apps section

**Comment by Bluscream** [comment]
Is it done? ^.^

**Comment by RedBrumbler** [comment]
@Bluscream https://github.com/the-expanse/SideQuestWebsite/pull/10 :)

**Comment by Bluscream** [comment]
Thanks

**Comment by shaneharris** [comment]
@Bluscream it looks like this now - ![i](https://cdn.discordapp.com/attachments/673907211382161479/682902392328683552/unknown.png)

this will be in sidequest 10 releasing soon.
