### ISSUE TITLE
[Feature Improvement Request] File Transfer Status

### ISSUE THREAD

**Issue by PhilipWhiteside** [the-expanse/SideQuest#352]
When transferring large files, such as a movie, SideQuest can be confusing. There is a notification that the file is being transferred. Including a completed task a few seconds later.

However, the file has not transferred across yet. If you change folders in the file explorer and go back, you will see the file side slowly rising each time. Once that matches the original size you know it's done. 

This has resulted in some files not playing properly as I thought it was done, but it simply wasn't. 

Is it possible to add a transfer status, be that a progress bar/percentage?

SideQuest: 0.8.7
OS: Fedora Silverblue
Oculus: Oculus Go 10.0.0.131

**Comment by shaneharris** [comment]
This should be fixed in the latest update ( coming soon ). The new implementation does not give any feedback but it does work reliably.
