### ISSUE TITLE
i cant connect my quest to sidequest

### ISSUE THREAD

**Issue by bouncybob1** [the-expanse/SideQuest#354]
it was working then suddenly it just stopped i tried everything i can think of that includes following countless tutorials i uninstalled sidequest 5 times and nothing can somone please help its so annoying and im just lost so please just help

**Comment by shaneharris** [comment]
Hi there! this issue tracker is more for bugs and feature requests with the sidequest software, not for general support. You can however get support at our discord https://discord.gg/mMJ33pk
