### ISSUE TITLE
Sort options do not persist when sorting in-app 

### ISSUE THREAD

**Issue by tchesket** [the-expanse/SideQuest#358]
As the title suggests, the sorting options on the left side of the page (Recent, Latest, etc) do not persist after pressing the back button when browsing games/apps, which is really annoying because every time you look at something then click the back button, you have to re-sort by whatever you are looking for and lose the page you were on. I hope this makes sense, unfortunately I do not know enough to provide any assistance with fixing this but I thought I would mention the issue.

**Comment by shaneharris** [comment]
Thanks for reporting this. We are aware and have a fix rolling out soon, apologies for the inconvenience in the mean time. Ill update here once it is pushed.

**Comment by tchesket** [comment]
Thank the lord! Well, thank you guys. This has been by far the worst thing about the otherwise amazing program.

**Comment by shaneharris** [comment]
this is now fixed! sorry for the delay!
