### ISSUE TITLE
JavaScript "ENOENT" error when trying to backup specific pre-installed APKs

### ISSUE THREAD

**Issue by Shadowpheonix** [the-expanse/SideQuest#360]
I am running SideQuest v0.8.7 on a Windows 10 PC, and am unable to backup 2 specific pre-installed APKs, which are...
com.oculus.assistant
com.oculus.browser

Attempting to backup either APK results in the backup process crashing with an error like the following...
>>>>>>>>>>
[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: ENOENT: no such file or directory, open 'C:\Users\<MyUserName>\AppData\Roaming\SideQuest\backups\com.oculus.browser\apks\2020-01-31T22-10-52.867Z_7.1.3.191849619
    versionName.apk'
<<<<<<<<<<

When this occurs, the entire backup process halts and nothing more can be backed up until I exit & relaunch SideQuest, which means I cannot just use the Select All option when telling it what to backup.

If this error could be fixed in a way that allows those APKs to also be backed up, great.  If it cannot, then an option to create a "blacklist" of APKs that should never be backed up would also be good.

**Comment by shaneharris** [comment]
thank you for reporting this ill start investigating whats going on here.

**Comment by Bluscream** [comment]
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: ENOENT: no such file or directory, open 'C:\Users\blusc\AppData\Roaming\SideQuest\backups\oculus.platform\apks\2020-02-03T14-50-09.954Z_7.1.1
    versionName.apk'

[OK]
```
![](https://cdn.discordapp.com/attachments/625267367513030656/673870199761534986/image.png)

**Comment by Bluscream** [comment]
You know what? That's probably because `versionName` not being present for certain apps. They might only have a build number @shaneharris

**Comment by shaneharris** [comment]
Yes that does look lightly, which means we could just omit that from the filename as the version code is really enough.
