### ISSUE TITLE
Feature request: bulk listing edit

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#361]
I'm probably the only one with this issue, but it would be great if there was some way to easily edit information about all my listings in a spreadsheet format or something. This has to do with the amount of mods I have and the amount of info I need to update about them each time there's an update, it would be a lot easier if it was a spreadsheet that I could edit

I'm mainly thinking about the tags, since those are the important part for searching for mods, I hope this'll make it in some day!

**Comment by sidequestlegend** [comment]
Im closing this for now while the mods system is still in flux, we can come back to it later if its still an issue.
