### ISSUE TITLE
DPI Scaling

### ISSUE THREAD

**Issue by FolkSong** [the-expanse/SideQuest#366]
With Windows DPI scaling enabled, the Sidequest window is too large for the screen. When I maximize it I can't see anything to the right of "Sidequest Gift Shop". I tried changing the compatibility settings in the exe properties but it doesn't seem to respect them.

Desired behaviour would be for it to override the Windows setting so that the full window fits on the screen.

**Comment by shaneharris** [comment]
Thank you for this, I have added an arbitrary min width to the window ( 1024 ) to accomodate the long list of menu icons at the top, i think a better solution would be to automatically collapse those icons into a drop down menu on smaller window/screen sizes. 

I will experiment with the DPI settings though, as im not sure if that is normal behaviour or not. 

Thanks for reporting!

**Comment by FolkSong** [comment]
Thanks! Just to be clear, the window is large enough to fit everything, the issue is that the window extends beyond the edges of the screen. I can drag it back and forth to see everything. It's not possible to resize it.

**Comment by shaneharris** [comment]
this has been fixed in the latest version coming soon 
![image](https://user-images.githubusercontent.com/6830845/75081026-b2222100-5505-11ea-91c4-79771077e82b.png)
