### ISSUE TITLE
Not catching an error in the case of retrieving the package list when the connection is bad on USB3

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#367]
![i](https://cdn.discordapp.com/attachments/625267367513030656/676042949611618354/Capture.PNG)

**Comment by cesmoak** [comment]
@shaneharris is there a good way to consistently recreate this issue? I've found a few places in the code that could be the source of this, and it's pretty straightforward to handle those locations, but I'm not sure a) the actual source of the issue for this case, and b) not sure if I can easily replicate to confirm the changes fix it. I have a a draft PR ready as a starting point, but it is relatively untested.

**Comment by shaneharris** [comment]
not reliably as it requires that you have a poor usb connection. I have only seen this happen in one of those cases too - normally if you get that far it just works. 

I do know the solution though - 

https://github.com/the-expanse/SideQuest/blob/12305d48b8433870792846756481caff69e41788/desktop-app/src/app/adb-client.service.ts#L180

There is not catching of errors here and if we add a `.catch(e => {/* handle this error */})` then it should resolve this problem. The method for sending adb commands to the main thread does not catch errors and instead passes that responsibility to the calling method as it would have the better contextual awareness of the operation being performed. 

https://github.com/the-expanse/SideQuest/blob/12305d48b8433870792846756481caff69e41788/desktop-app/src/app/adb-client.service.ts#L241
