### ISSUE TITLE
Add a VRtuos shortcut to file explorer

### ISSUE THREAD

**Issue by KureKureciCZ** [the-expanse/SideQuest#369]
Hi, please add this shortcut to the file explorer.
Path: ```\Android\data\com.PavelMarceluch.VRtuos\files\Midis\```
Icon:
![Icon](https://user-images.githubusercontent.com/48494136/74176769-a77ba800-4c38-11ea-9740-5624f4766ce4.png)
Thanks :)

**Comment by RedBrumbler** [comment]
Are there any shortcuts in the file explorer at all?

**Comment by KureKureciCZ** [comment]
> Are there any shortcuts in the file explorer at all?

Yes, for SynthRiders and Song Beater

**Comment by shaneharris** [comment]
Maybe a user configurable shortcuts list makes sense, with defaults in place too.

**Comment by shaneharris** [comment]
![image](https://user-images.githubusercontent.com/6830845/75071168-bd1c8780-54ec-11ea-9358-d023e3817b9a.png)

This is coming in the next release.
