### ISSUE TITLE
Blank Home Screen

### ISSUE THREAD

**Issue by DaverTimer** [the-expanse/SideQuest#370]
When I open sidequest the home screen is blank. I tried pressing the home button, using the web browser and redownloading sidequest, but it is still blank. I am using Mac btw.

**Comment by shaneharris** [comment]
Hi Dave! I have only seen this happen once and the solution was actually pretty simple, close sidequest, delete the folder at `%appdata%/SideQuest` and start sidequest again. Be advised this will also delete any app backups in that folder too if you dont move them out first. When you restart sidequest it will re-create that folder and its contents.

**Comment by DaverTimer** [comment]
Thanks it worked
