### ISSUE TITLE
feature request: Mod listings update

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#372]
So from the people over in the BSMG who do hook and asset mods, these features were requested as to improve QoL for modders and users, and to overall make sidequest a better place for beat saber mods

- Fix json uploader
- Fix beaton references which are still there (mod uploader, tag sorting, URL)
- Seperate Hook mods from Asset mods
- Support for listing multiple versions of mods (namely for hook mods)
- Mass listing editing support (all in one list so versions can easily be updated)

We hope these can be added so that we may have lots of fun playing beat saber with mods!

**Comment by RedBrumbler** [comment]
I guess this was not done in SQ X?

**Comment by shaneharris** [comment]
I will look at this in the next ( and final ) phase of sidequest X

**Comment by sidequestlegend** [comment]
It looks like this wont make it in at launch, but serves as a good starting point to focus energy on after the new mods interface is out.
