### ISSUE TITLE
Error while updating pocket racer.

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#373]
I went to update my apps, and download some new apps and left to go do something

![i](https://cdn.discordapp.com/attachments/625267367513030656/677612136448393235/unknown.png)

**Comment by cesmoak** [comment]
Seems two fixes are in order:
- Catch an error when an invalid URL is requested when updating apps
- Prevent invalid URLs to be submitted for app updates

**Comment by cesmoak** [comment]
Scoping this issue to the first of the two fixes I listed above: handling invalid URLs when installing an APK. I created a new issue for the issue of allowing apps to submit invalid URLs.
