### ISSUE TITLE
Copying discord link dismisses the error making it hard to copy the error

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#376]

**Comment by cesmoak** [comment]
Suggestion: change the initial discord link to a text link "Get Help" which opens a modal with instructions to go to Discord and post the error content there. In the future, this modal could also include "common solutions to this problem" to avoid flooding discord.

**Comment by shaneharris** [comment]
![image](https://user-images.githubusercontent.com/6830845/76168033-60af9e00-6163-11ea-85df-b619a7cf5931.png)
coming in ver 10, releasing soon.
