### ISSUE TITLE
Add BMBF Button if last IP is known

### ISSUE THREAD

**Issue by Bluscream** [the-expanse/SideQuest#377]
```
http://<LAST_IP>:50000
```

![image](https://user-images.githubusercontent.com/3318223/74598358-7227ed80-5070-11ea-8307-90bb6814b9d3.png)

**Comment by shaneharris** [comment]
Linking to BMBF directly is tricky here, the official line is that it falls under illicit modding and according to oculus it could result in a ban, which makes it hard for us to endorse it more than we already do.

**Comment by shaneharris** [comment]
Just an update here, I have added custom browser bookmarks so you can now achieve this with a static IP or a dynamic one that doesn't change often. coming in version 10.

**Comment by Bluscream** [comment]
Awesome, thanks
