### ISSUE TITLE
SideQuest not connecting after update

### ISSUE THREAD

**Issue by Righ7y** [the-expanse/SideQuest#378]
After I updated to version 8.7 of SideQuest, it no longer connects to my Quest. Instead, it just infinitely displays the "Connecting" message, even when disconnected.

**Comment by ChibiBlaziken** [comment]
Have you dis and re enabled Developer mode. Or attempted all the steps in https://github.com/the-expanse/SideQuest/wiki/I-am-having-issues-Connecting-,-what-do-i-do%3F#having-issues
Generally Dev mode toggling and a proper device power off and on fixes that issue

**Comment by shaneharris** [comment]
![image](https://user-images.githubusercontent.com/6830845/74602443-62c09880-50a0-11ea-9726-4f949d90268a.png)

**Comment by shaneharris** [comment]
I thinking im going to alter the download method used to download adb initially. I think it some Very rare odd cases it fails to download with no error or obvious reason.

**Comment by shaneharris** [comment]
this has been fixed in the latest version releasing soon.
