### ISSUE TITLE
“Set FFR ( Fixed Foveated Rendering ) level”--Does it fail after restarting the headset?

### ISSUE THREAD

**Issue by diegobona** [the-expanse/SideQuest#379]

**Comment by srvrguy** [comment]
That setting will only persist until a reboot or a power cycle. If either of those happen, the value is reset to default.

**Comment by shaneharris** [comment]
this is a device limitation which means we cant do anything about it, but we could word it better on that screen so I will keep this issue open for that

**Comment by diegobona** [comment]
thanks.

**Comment by shaneharris** [comment]
The wording has been improved in the next version releasing soon.
