### ISSUE TITLE
ADB driver winsub.inf

### ISSUE THREAD

**Issue by WR-Pro** [the-expanse/SideQuest#381]
When I try to download the adb driver, when i open it, the .inf doesnt appear at the end of winsub and when i right click it the install thing doesnt show up

**Comment by RedBrumbler** [comment]
did you actually unpack the zip file

**Comment by srvrguy** [comment]
Windows, by default, hides file extensions. You won't see the "inf" unless you turned off that default behavior. Also, as RedBrumbler noted, you need to make sure to extract the contents of the zip file or you won't see the install option.

**Comment by shaneharris** [comment]
closing as out of scope of the sidequest app
