### ISSUE TITLE
Red dot v8.7 Disconnected: Connect/Reconnect your headset via USB.

### ISSUE THREAD

**Issue by LazyBlaze** [the-expanse/SideQuest#382]
but its plugged in and charging. so i had the ability to stream my headset on screen, then next day it wont connect anymore. its not the yellow dot saying Connecting its a red dot saying to reconnect. iv tried uninstalling sidequest reinstalling the current patch still same problem. iv tried turning off and on dev mode on my phone and oculus dashboard and re-enabling them both. and rebooting the Quest. please help in any way. thanks

**Comment by LazyBlaze** [comment]
yes i have unplugged it and plugged it back in. the red dot doesnt change. and yes i have loged out and loged back in to the device.

**Comment by LazyBlaze** [comment]
uninstalled beatdrop. then it worked again...

**Comment by shaneharris** [comment]
thanks for this! ill make sure our support teams know!
