### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by Deluxe69fun** [the-expanse/SideQuest#389]
Whenever i go to install the inf. file it reads back The INF file you have selected does not support this method of installation. What Do i do?

**Comment by Deluxe69fun** [comment]
The file also doesnt appear as an INF file. Even after i extract it.

**Comment by shaneharris** [comment]
Hey there, this is really outside of the scope of sidequest so ill close this issue. 

Here are some links that could help tough - 
https://sdq.st/drivers or something like this - https://www.youtube.com/watch?v=jyKrxxXOvQY
