### ISSUE TITLE
Version 0.1.1 shows as 0.0.1

### ISSUE THREAD

**Issue by nickjohnford** [the-expanse/SideQuest#39]
Simple thing to fix to make sure people are not confused which version they are on, package.json still shows the version as 0.0.1

https://github.com/the-expanse/SideQuest/blob/e8c17c9e650b97b8f913820c398efac9fb9dc913/package.json#L3

**Comment by shaneharris** [comment]
Good Call! this has moved so fast, will use that from now on.
