### ISSUE TITLE
SideQuest cannot see device if using 3.1 cable for Link

### ISSUE THREAD

**Issue by Icepick869** [the-expanse/SideQuest#400]
When I connect to my PC with the same cable I use for Link, I get the Link Enable message but SideQuest doesn't see the Quest. I have a work around. Using my phone's 2.0 cable to connect, so Link doesn't see the Quest, but SideQuest does.

With the phone cable I don't need a fix, but if want to work on it and you can't duplicate it I'm game to provide whatever information I can.

**Comment by srvrguy** [comment]
Oculus Link interferes with SideQuest. Make sure it is not running when you want to use SideQuest, and it should work okay.

**Comment by RedBrumbler** [comment]
Yeah link takes priority so there is no way this is a problem sidequest itself can fix, just make sure to not have the oculus software running when trying to use sidequest with your quest

**Comment by shaneharris** [comment]
This is a known issue with ADB and not with sidequest im afraid, we always recommend using usb2 as ADB has problems with some usb3 controllers/ports. Its not something we can fix so im going to close this one
