### ISSUE TITLE
Getting error when trying to connect Quest to wireless mode 

### ISSUE THREAD

**Issue by darktazza** [the-expanse/SideQuest#416]
Hi there, sidequest works perfectly apart from the fact that I can't get the wireless mode to work and 
 I can't I cast to my laptop. I am getting the error - an attempt was made to access a socket in a way forbidden by its access permissions. (10013). Anyway I can fix this?

**Comment by RedBrumbler** [comment]
Have you checked the faq entry?

https://github.com/the-expanse/SideQuest/wiki/Streaming-With-SideQuest#you-can-stream-wireless-windows-only

**Comment by darktazza** [comment]
Yes, I tried locating the ADB file with task manager but its not appearing. I can't find any sort of fix for this issue, can anyone help?

**Comment by shaneharris** [comment]
Hey there, I think i responded to this on reddit. A google search shows that something is using the socket/port that SideQuest is trying to use. I would try another user account or another PC to confirm, but it looks like its something blocking on your PC. 

Here is one of many search results on the issue - https://appuals.com/fix-an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissions/

**Comment by Dylsss** [comment]
I can reproduce this issue by blocking port 5555, this is likely the issue. Try temporarily disabling any firewall software.
