### ISSUE TITLE
An attempt was made to access a socket in a way forbidden error 

### ISSUE THREAD

**Issue by darktazza** [the-expanse/SideQuest#418]
I posted a day or so a go about an issue I have on sidequest but it was closed for some reason and my problem was not resolved. I cannot use the wireless mode and I keep getting the error "cannot connect to 192.168.1.42:5555: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)". I have tried switching users which still didn't work and I do not own another computer I can use. Is there anything I can do? I'm not very tech savvy but I can follow instructions

**Comment by RedBrumbler** [comment]
Did you try all the suggested things in this post? https://github.com/the-expanse/SideQuest/issues/416

**Comment by shaneharris** [comment]
hey @darktazza apologies I closed that issue as this is out of scope of sidequest. this issue tracker is more for issues with hte sidequest software but this is an issue specific to your PC. Feel free to come and chat on [discord](https://discord.gg/Ww4yQ8) to get technical support but this issue tracker is specifically for issues with the sidequest software itself. 

Thanks!

**Comment by shaneharris** [comment]
Do you have NordVPN installed?
