### ISSUE TITLE
list setup instructions in README.md too

### ISSUE THREAD

**Issue by micahstubbs** [the-expanse/SideQuest#42]
It would be cool to list the setup instructions from the HTML page in the README.md as well

https://github.com/the-expanse/SideQuest/blob/master/desktop-app/index.html

This way people who are checking out the project can know if it will work for them before downloading the bundle ☺

**Comment by shaneharris** [comment]
these have now been moved to here- https://sidequestvr.com/#/setup-howto I will link to this on the readme
