### ISSUE TITLE
[Suggestion] SyncSaber by difficulty

### ISSUE THREAD

**Issue by bluegizmo83** [the-expanse/SideQuest#426]
It would be nice if there could be an option in SyncSaber (where you can choose to sync the Top songs, Hot songs, Most Downloaded, etc) to only sync songs that have a specific difficulty option. 

Example: I'm a new player and have no need for songs that have only Expert or Expert+ difficulties right now. I need songs that have Easy and Normal difficulties, but when I sync the Top 30 for example, most songs only have Expert difficulty. So it would be nice to still be able to use all the SyncSaber options but only download and sync songs that actually have Easy or Normal difficulties.

**Comment by RedBrumbler** [comment]
Sidequest does not do bmbf custom songs so this issue is out of place

**Comment by shaneharris** [comment]
This might be better posted to https://github.com/Zingabopp/SyncSaberService

Thanks!
