### ISSUE TITLE
Side load regular APK without it floating

### ISSUE THREAD

**Issue by kurse** [the-expanse/SideQuest#427]
We have our own app with our own engine that handles the whole VR part, and we want to side load it on Oculus without having it floating as a 2D app, as this basically shows us a stereo render floating on the screen (since you're already doing the stereo render once and we are doing it again). We are not using unity or unreal or any other engine but our own, and it works great on Android phones, we want the same to be on Oculus Quest, where our APK basically launches in full screen without any rendering done by your software other than launching the app full screen. Is there a way to do so? Thanks!

**Comment by RedBrumbler** [comment]
sidequest doesn't do anything else besides installing the app, so I doubt sidequest could be of any use in that regard, but maybe shane knows a way to accomplish this

**Comment by kurse** [comment]
Interesting, I thought it ran inside your environment. Any idea on how to make the app full screen then instead of it being rendered in stereo and floating?

**Comment by shaneharris** [comment]
@kurse i think you need to look into the native oculus SDK - if you have a custom engine then you will need to hook it into the oculus SDK or else the app will always show in 2d mode on the device. It may have worked for cardboard but oculus has a specific sdk
