### ISSUE TITLE
Search input feild behaving weird

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#428]
https://streamable.com/s5kpn

This is the behaviour I get when something is in my search field, I select it from right to left and start typing in the field, the letters get added in a weird way making me write words backwards

**Comment by tchesket** [comment]
Press insert on your keyboard then try it again

**Comment by RedBrumbler** [comment]
@tchesket didn't help

**Comment by sidequestlegend** [comment]
this should be somewhat resolved in the latest version releasing soon, it essentially moves that search box to the top right of the window making this less lightly to happen.
