### ISSUE TITLE
Text not visible in Search Bar "Currently Installed Apps"

### ISSUE THREAD

**Issue by SmallSardinian** [the-expanse/SideQuest#429]
On Mac (Dark Mode): the text is dark, so it won't be seen, although the search task is working flawless. When selected, the text becomes visible.
![ezgif com-optimize](https://user-images.githubusercontent.com/61988709/76247852-8363b480-6240-11ea-8272-a31f830ce4c9.gif)

**Comment by shaneharris** [comment]
Thanks, this has been fixed in the latest version releasing today
