### ISSUE TITLE
APKs cant be too big on android - need to test size before install.

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#43]
might want to add a check on final apk file size... if it goes above an Int32 android wont even load it

**Comment by avluis** [comment]
I need to look into this since I'm not up to date on how Beat Saber is patched -- but something to look into is this: [APK Expansion Files/OBB Data Files](https://developer.android.com/google/play/expansion-files)

This can help with offloading the additional data away from the main apk file.

**Comment by shaneharris** [comment]
not really possible for us as we are patching an existing APK, its also more int he scope of the patcher than SideQuest and I dont think they would be interested in that body of work. 

For now this has not come up that often so im closing for now.

**Comment by srvrguy** [comment]
A lot of people lately seem to be running into this, and I think it would be nice to warn when the apk size is getting close to the max and/or even refuse to install the apk if it's oversize. It would cut down on support requests. I petition that this be reopened.
