### ISSUE TITLE
beat saber pausing/quest loading randomly

### ISSUE THREAD

**Issue by damfalcon** [the-expanse/SideQuest#432]
on any of my sideloading songs, partway through my quest will continually blank out, show the loading circles, then resume to the pause screen. anyone else having this problem?

**Comment by RedBrumbler** [comment]
Sidequest is not responsible for custom songs, this issue tracker is not where to ask support for this.

Besides that, perhaps it's the memory issue that the quest has on beat saber, because previewed songs in the menu don't get cleared correctly
