### ISSUE TITLE
ADB not downloading in some cases :(

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#434]
This Appeared at the bottom Error: Command failed: "C:\Users\james\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s undefined kill-server '"C:\Users\james\AppData\Roaming\SideQuest\platform-tools\adb.exe"' is not recognized as an internal or external command,
 operable program or batch file.

**Comment by shaneharris** [comment]
Need to look at bundling ADB with sidequest - possibly only bundle the relevant platform tools for each platform and only the required binaries to run ADB.

**Comment by sidequestlegend** [comment]
bundling in the latest version
