### ISSUE TITLE
failed or uncompleted update attempts still remove records from 'updated-apps' even though update wasn't finished

### ISSUE THREAD

**Issue by korenmic** [the-expanse/SideQuest#441]
1. visit https://sidequestvr.com/#/account/updated-apps
2. select an app from there
3. click update
4. side-quest begins attempting to update
5. exit side-quest to force failing the update attempt
6. check again https://sidequestvr.com/#/account/updated-apps
7. realize that unupdated apps no longer appear there, even though they can still be updated since they were not actually updated at all and they still currently differ from latest version.

**Comment by korenmic** [comment]
by the way - the exit was done at the downloading stage at 0%, not even during installation

**Comment by shaneharris** [comment]
Hey there! Thanks for this. Indeed it is a known issue that an install can fail and it triggers an update to be registered. The website can be so far abstracted from the actual device that it does not know what versions of things are on there and therefore it relies on its own record of what happened. You can however retry the failed downloads within sidequest once you reconnect the headset but i recognise that this is not the perfect solution. Soon we are introducing a "favourites" list which will allow you to keep track of lists of apps in a more persistent way which would also allow you to install those to multiple devices. We may also include an update history allowing you to repeat any group of updates multiple times which could also lend itself to this.

**Comment by korenmic** [comment]
@shaneharris , thank you for responding. I understand.

Do you think it would be reasonable to implement a button named "force resync versions now" hidden in settings perhaps,
which sends via adb to the sidequest profile all the current versions of every side-quest installed app
therefore correctly updating the "updated/non-updated" status of every app, which could fix the issue we are talking about

what do you think?

**Comment by shaneharris** [comment]
Thar sounds like a reasonable idea and should essentially achieve the same thing in most use cases i think - with the added advantage of per app update information. I think this is certainly where we want to be heading towards but there are some hurdles in the way that we need to tackle first.  Right now the desktop application is somewhat stateless and does not really have any awareness of the SideQuest profile as such so there is some work there to create that at the cost of some interoperability ( the website operating on its own with the same user experience as the desktop application ). We have also been reluctant to try to grab all installed applications version info over ADB before - this info is not available via a single ADB command and could require hundreds of commands to grab the version info from some typical application lists over ADB which could be a poor user experience to have to wait for those async commands to complete. This could be solved with an on-device application but that has added considerations in terms of complexity and maintenance going forward. To date we have not enforced proper versioning on developers but that's not to say that we are not well equipped for it structurally.

All in all I think an update history and/or favorite lists might be an easier option to achieve in the short term and as a stepping stone to something more akin to what you are suggesting once we can work out some of those considerations.

Thanks for your thoughts on this. It is much appreciated.

**Comment by sidequestlegend** [comment]
this functionality is completed and in QA stages. coming soon!
