### ISSUE TITLE
Regex for OBB files doesn't accommodate package names with less than 3 parts.

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#442]
Current Regex: `/main.[0-9]{1,}.([a-z]{1,}.[A-z]{1,}.[A-z]{1,}).obb/`

Better Regex: `/main.[0-9]{1,}.([A-z]{1,}.[A-z.]{1,}).obb/`

Or Maybe: `/main.[0-9]{1,}.([A-z.]{1,}).obb/`

**Comment by shaneharris** [comment]
It also does not allow for numbers as part of the package name part of the OBB filename

**Comment by sidequestlegend** [comment]
fixed in the latest version
