### ISSUE TITLE
Add option to choose adb daemon port / respect environment variables

### ISSUE THREAD

**Issue by sn0opy** [the-expanse/SideQuest#443]
I was struggling to get the Quest to show up in Sidequest since I've reconfigured the port my adb daemon is listening on via the global environment variable `ANDROID_ADB_SERVER_PORT`. 

It looks like that Sidequest neither respects that variable nor has any way for an "advanced" user to change that port.

Since I have to change the port to something else due to conflicts with other software, it'd be nice to have this added to Sidequest.

**Comment by shaneharris** [comment]
Thanks for this I will look into if this is possible and try to expose or respect where applicable

**Comment by sidequestlegend** [comment]
Hi there, it looks like the [client library](https://github.com/openstf/adbkit#adbcreateclientoptions) we use has the option to specify the client port for connecting but does not appear to pass that port to the server when it is started. I tried to work around it b  y passing the port with the [new -P](https://stackoverflow.com/a/24238475/10874447) option as part of the `bin` property when creating the client but it would not start the server and no error was produced. 

I may look at forking that library in the future, although it has been inactive for a while and that is a significant maintenance requirement. Most recently we have been moving to interrogating the adb binary directly and parsing the output. Once we have removed the dependency I will come back to this possibility.
