### ISSUE TITLE
SideQuest Mac: Can select, but not delete, multiple files

### ISSUE THREAD

**Issue by darienm** [the-expanse/SideQuest#445]
Mac version 0.10.2. In the file manager, clicking X on a file will present a confirmation dialog for the "item". Works fine. Selecting multiple files (by clicking their names so they highlight) and clicking any X will present a confirmation dialog for the "item(s)" but confirming only deletes the single file whose X was clicked.

**Comment by shaneharris** [comment]
Thanks for this, will have a release out in a few days with some patches.

**Comment by sidequestlegend** [comment]
Looking at this further, it seems its a miscommunication. With multiple selected files you must click the floating action button on the bottom right and select "delete selected". I have separated those buttons in the latest version to make them more prominent.
