### ISSUE TITLE
SideQuest black screen on load

### ISSUE THREAD

**Issue by nicmege** [the-expanse/SideQuest#446]
Hi, I just downloaded and installed the newest version of SideQuest v0.10.2 but when I install it on my Mac running Catalina all I get is a black screen.  I see nothing else! I've tried connecting my Quest, the red dot becomes green but still black screen... Please help!!! 
<img width="1016" alt="Screen Shot 2020-03-21 at 8 39 55 PM" src="https://user-images.githubusercontent.com/62481262/77234056-425e8f00-6bb4-11ea-929d-0e70c6bc9d1c.png">

**Comment by shaneharris** [comment]
Hi there, does this computer have access to the internet?

**Comment by nicmege** [comment]
Yeah it does. Thought the internet connection was an issue too but no...works fine

**Comment by shaneharris** [comment]
can you access the sidequest website - https://sidequestvr.com/#/ ?

**Comment by nicmege** [comment]
No for some reason it just hangs for a while then tells me server problems won't let me connect to the website

**Comment by nicmege** [comment]
For some reason not, I get the same problem as with the side quest page

**Comment by nicmege** [comment]
Ok managed to get it to work, figured out what you were driving at. I changed network and somehow it now works.. I guess maybe the page was blocked by my previous network? Can that be?  Or they’re throttling? I do live in Africa…

**Comment by shaneharris** [comment]
Hey there, there could be issues with github. I had the same thing happen to a few users in spain the other day. I can only hope it resolves itself on its own. I might look into moving the site off github pages soon if this keeps happening. 

Ill close this for now since it is working for you, but open a new one if need be.
