### ISSUE TITLE
Blacklist explanation 

### ISSUE THREAD

**Issue by whytheheckme** [the-expanse/SideQuest#447]
I've started getting the "Harmful Content Detected" message as I use sidequest to sideload APKs after the "Checking APK against blacklist" step with a generic warning that doesn't explain why this particular APK has been added to the blacklist. Is there a way that I'm not aware of to see more insight as to why a particular APK has been added? What is the actual risk?

**Comment by RedBrumbler** [comment]
One of the reasons I can think of is that it could be a pirated app and you don't know what has been done to the code to make it work on accounts that do not own those apps

**Comment by shaneharris** [comment]
I'm sorry, we don't provide details on the risks involved as some of the risks are harder to determine without de-compiling each application and looking for harmful payloads that have been hidden by their very nature. We do provide a list of the risks in warning that pops up, the main risk we can guarantee is that it risks your oculus account, your game library and your potential to be banned from the entire oculus platform. 

Thanks!
