### ISSUE TITLE
Add more descriptive message for INSTALL_FAILED_UPDATE_INCOMPATIBLE or other similar messages 

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#448]
and get it to show a more useful message of "try uninstalling first ( backup if need be )"

Also "Premature end of stream" comes up a lot, could also prettify that error message too.

**Comment by srvrguy** [comment]
I'm concerned that suggesting doing an uninstall and install covers a security measure. The whole point of the signing is to prevent malicious upgrades/installs. Normally, the package signature shouldn't change. If it's changed, that means it was signed by a different certificate which often can indicate the application has been doctored.

If you're going to make it friendly, at least warn that this is a suspicious thing and the user should check first before proceeding with installing the new version.

**Comment by shaneharris** [comment]
Yes agreed, some were suggesting just doing an auto uninstall or even prompting the user to do that which i didn't think was a viable option for the above and other reasons ( game state being lost ) but I think you are right, the security implications should be highlighted here too.

**Comment by RedBrumbler** [comment]
oh didn't even think of that, I initially asked about this too but I did not know about the fact that this also happens when an app has been doctored with

**Comment by sidequestlegend** [comment]
added in latest version

![i](https://cdn.discordapp.com/attachments/667006900130545681/702819721044688896/unknown.png)
