### ISSUE TITLE
vendor reviews their own app

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#450]
I don't think a user should be able to leave a review on their own app (but don't break vendor replies while changing this!)
![afbeelding](https://user-images.githubusercontent.com/51795403/77477338-76d48400-6e1c-11ea-954f-5a50c62691da.png)

**Comment by shaneharris** [comment]
ha ha lol, yeh that is a good point. i dont think this matters all that much because people can see that review is from the vendor and multiple reviews correct the issue quite quickly.

**Comment by RedBrumbler** [comment]
just wanted to make sure you were aware of it :)

**Comment by sidequestlegend** [comment]
this is fixed in the latest version
