### ISSUE TITLE
BMBF is stuck on Loading Configuration... 

### ISSUE THREAD

**Issue by pamela1118** [the-expanse/SideQuest#459]
BMBF won't load after I updated Beat Saber.  Do you know if/when BMBF will update?  Is there a workaround.  I did not confirm the backup before updating.

**Comment by RedBrumbler** [comment]
sidequest is not responsible for bmbf so this issue is out of place.

only workaround is to install a backup of beat saber if you really want to mod it with BMBF

**Comment by pamela1118** [comment]
Thank you for your quick response.
