### ISSUE TITLE
Include correct attribution for Songe Converter

### ISSUE THREAD

**Issue by lolPants** [the-expanse/SideQuest#46]
Songe Converter is being used in your tool.
https://github.com/the-expanse/SideQuest/blob/b6ddd42d7630be1db12aad0428d50a6d95cb30e2/desktop-app/js/bsaber.js#L152

As stated in the [README](https://github.com/lolPants/songe-converter#-license) you must include the license and copyright notice somewhere in your tool.

*(You may also want to check for the latest release version since it's not done yet)*

**Comment by ATechAdventurer** [comment]
Hey @lolPants what is the best way for us to do that. I am personally new to this sort of thing and the creator is probably asleep right now (it's pretty late in his timezone). I can get that fixed ASAP

**Comment by lolPants** [comment]
What a lot of people do is have a `Licenses` or an `Attribution` section somewhere where appropriate credit is given.

Take Discord's page as an example: https://discordapp.com/licenses

As for autoupdating, a request to GitHub's API will do the trick
https://api.github.com/repos/lolPants/songe-converter/releases

**Comment by ATechAdventurer** [comment]
Added To the credit section of [README.md](https://github.com/the-expanse/SideQuest/blob/master/README.md) with repo URL, author name and a link to the license in our licenses folder.

**Comment by lolPants** [comment]
Awesome, thank you!
