### ISSUE TITLE
An antivirus has detected this trojan Trojan.Win32.IRCBot.l3vP

### ISSUE THREAD

**Issue by vivayoes** [the-expanse/SideQuest#462]
The version 0.10.2.dmg for mac has been detected with a trojan inside.
![Captura de pantalla 2020-03-29 a las 13 40 49](https://user-images.githubusercontent.com/62836533/77848724-2c118e00-71c7-11ea-8a9d-4f6454887834.png)

**Comment by shaneharris** [comment]
Hi there, so a few things. This is apparently a windows trojan detected inside the mac app file for 10.2, not the DMG ( i just checked the DMG on https://www.virustotal.com/gui/file/0fd6d6174b05714e79f46e561a70b70aeabd6ee77f2ce4ae497c5298dfe07197/detection and it is fine ). This means that assuming this isn't a false positive ( which i expect it is ) this trojan could not do anything on a mac anyway. 

It seems to me you are scanning a file called SideQuest.app.zip - where did this come from? Did you just zip up the SideQuest.app folder on mac and then upload that?

**Comment by vivayoes** [comment]
Yes, you are right. I scanned the dmg and it's "clean" but uploading the App (just extracting it from the dmg) the web detects the trojan.

I have uploaded the app to VirusTotal just drag and drop and it automatically zip it.
I tried to upload another app using the same steps and VirusTotal doesn't find the Trojan so my mac is not creating the trojan.

**Comment by shaneharris** [comment]
ok seeing this now too - https://www.virustotal.com/gui/file-analysis/NjE5N2EzYTkyOTVlNWY2YzJkNmFmMTQ2MTY0NzNkZjc6MTU4NTQ4NTUwNQ==/detection

it claims this file `SideQuest.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework` is the cause which tells me this is most lightly a false positive

im investigating further

**Comment by vivayoes** [comment]
Thank you for your help. I appreciate it

**Comment by shaneharris** [comment]
OK more info here supporting the false positive result:

The official electron version is also detected the same: 
https://github.com/electron/electron/releases/download/v4.1.5/electron-v4.1.5-darwin-x64.zip

https://www.virustotal.com/gui/file/a8000f23edcf593089b5af15f976d1029d764370ddeeee43278867208c7a83fc/detection

**Comment by vivayoes** [comment]
Thank you for your help!!

**Comment by shaneharris** [comment]
Thank you for reporting!
