### ISSUE TITLE
Access to Synth Riders disappeared in latest update

### ISSUE THREAD

**Issue by gorfreed** [the-expanse/SideQuest#466]
Hello dear SideQuest creator,
Accessing the Synth Riders custom song library has a been a bit of a challenge for some releases now, but with the latest update to SideQuest I am unable to find it. Could you please point out how to get to it? It would be immensely helpful if you could mention changes to this feature (which is one if not the no.1 feature i am using SideQuest for) in your version changelog!
Much appreciated & keep up the great work!
Daniel

**Comment by gorfreed** [comment]
Sorry for the push. Does nobody care for this integration? Seems like I am the only one loading custom songs to this amazing game like this...

**Comment by Crash82** [comment]
You are not the only one... i am new to the whole side quest  and I just bought a quest couple of days ago and bought this game because of the custom music part and I thought I was doing something wrong for the last three hours since I couldn't get it to show up side quest

**Comment by shaneharris** [comment]
Hey guys, you should be able to access synthriders as normal - 
![image](https://user-images.githubusercontent.com/6830845/78593546-b8aef280-783e-11ea-8f3d-eaa3fb8f5fe7.png)

Once you open the website you can then save it to you favorites 

![image](https://user-images.githubusercontent.com/6830845/78593718-f7dd4380-783e-11ea-8f31-7513a9fc2b57.png)
I hope that helps!
