### ISSUE TITLE
SideQuest doesnt connect to my oculus quest

### ISSUE THREAD

**Issue by GhostPKblog** [the-expanse/SideQuest#467]
I followed multiple tutorials on how to do this however when i launch sidequest the option to allow the computer to access files or whatever doesnt show up? i downloaded and installed the ADB file but it  still wont load the alert. someone please help!

**Comment by sidequestlegend** [comment]
hi htere, we like to keep support to the public channels on discord thanks - https://discord.gg/6vaWFd
