### ISSUE TITLE
[Suggestion] Download APKs without Quest connected, install them later

### ISSUE THREAD

**Issue by FolkSong** [the-expanse/SideQuest#470]
Some apps take a long time to download and there's no reason to have the Quest connected the whole time. It would be nice if we could separate the "download" operation from the "install" operation, so APKs could be downloaded at any time, then installed the next time the Quest is connected.

**Comment by FolkSong** [comment]
I realize I can download them through a web browser then manually install them later, but this takes away from the streamlined nature of SideQuest.

**Comment by FolkSong** [comment]
Maybe the more pressing issue is why downloads are so slow through SQ. I just installed the Cubism demo and it took about 5 minutes to download a 50 MB file. Through a normal browser it takes literally 1 second.

**Comment by shaneharris** [comment]
this is some good feedback, the downloads all come directly from the vendors servers so we don't have a lot of say there. as regards it being quicker in the browser, i have not experienced that but i will try to investigate.

**Comment by sidequestlegend** [comment]
Hi there! We have reviewed the complexity involved in caching downloads to your PC first for installing alter and we feel it over complicates things right now without enough value proposition as most people have reasonable internet connections. We feel the task list as it is allows you to background this requirement and allow it to run while you continue to browse and install items and that this is sufficient for most users.
