### ISSUE TITLE
Task missing from task screen

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#471]
Hey, you know that if you copy a large folder over, sometimes it doesn't show up as a running task?
if you jump to tasks
you can see it "processing files"
but if you click CLEAR DONE - that goes away
sometime later you'll get a status bar message that file copy is complete.  It is like it is running on it's own disconnected thread

**Comment by shaneharris** [comment]
https://beatsaberquest.com/bmbf/bmbf/backup-restore-custom-songs-manually/

**Comment by sidequestlegend** [comment]
this has been fixed in the latest update releasing soon
