### ISSUE TITLE
Song Failed: CustomSongPath must be set on the song! 

### ISSUE THREAD

**Issue by zarev** [the-expanse/SideQuest#473]
Hi,
My playlists got messed up and in trying to reload the asset folder I am getting this message for a about 150 songs. In the screen shot below you can see what is in the quest bmbf custom songs folder. All the ones without names do not appear in the game. 
[https://i.imgur.com/R3Q4dux.png](url)

Another issue is that the bookmaks folder is also not getting updated anymore, and same for any other folders I add like Top 10s, Trending etc. 

Please help.

**Comment by shaneharris** [comment]
Hi there, i'm afraid we don't make BMBF and cannot support it here.
