### ISSUE TITLE
Able to open the same folder a lot of times in file browser

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#474]
![afbeelding](https://user-images.githubusercontent.com/51795403/78302384-f78d3180-753a-11ea-9d10-59b8c7940553.png)

![afbeelding](https://user-images.githubusercontent.com/51795403/78302401-ffe56c80-753a-11ea-951f-4e9a14db0626.png)

**Comment by sidequestlegend** [comment]
fixed in latest version
