### ISSUE TITLE
Can't cast

### ISSUE THREAD

**Issue by LocalGingerBoi** [the-expanse/SideQuest#475]
I press the button to cast using ScrCpy but when I press start stream nothing happens.

**Comment by ChibiBlaziken** [comment]
Try here
https://github.com/the-expanse/SideQuest/wiki/Streaming-With-SideQuest
it may have what you need

**Comment by shaneharris** [comment]
hey there! this can be caused by a number of things, if you are still having problems come chat with us on discord for help.
