### ISSUE TITLE
Stuck "Connecting..."

### ISSUE THREAD

**Issue by kindapinksushi** [the-expanse/SideQuest#479]
No matter what I do I've tried resetting the computer and the quest, it continues to say "connecting" I've tried redownloading it, and even tried disconnecting everything from the computer and restarting the software, I just cannot get it to stop "connecting."

**Comment by RedBrumbler** [comment]
![afbeelding](https://user-images.githubusercontent.com/51795403/79219021-c0c7ed00-7e51-11ea-872a-7d31209cebda.png)
