### ISSUE TITLE
Suggestion: Clear search on section change

### ISSUE THREAD

**Issue by drewbaumann** [the-expanse/SideQuest#48]
![Screen Recording 2019-06-03 at 03 45 PM](https://user-images.githubusercontent.com/337808/58839434-b3798980-8616-11e9-892e-452735560dd6.gif)

I noticed that on section navigation the search box doesn't clear. I am not sure if this is intended behavior, but I found it undesirable from a UX perspective.

**Comment by shaneharris** [comment]
this has been fixed in the latest version, but i have temporarily disabled search for now, we dont have enough apps to justify a search yet.
