### ISSUE TITLE
BMBF Quest Issue

### ISSUE THREAD

**Issue by ItzTropicalx** [the-expanse/SideQuest#480]
I was able to download BMBF into my quest, but for some reason, it is stuck on the configuring screen. Any help would be appreciated.

**Comment by lordoftheloidl** [comment]
Same here with our Quest,,, Tried reinstalling Beatsaber and BMBF but nothing seems to work,
Needed to update my Beat Saber to download more custom songs. The Feature just had a malfunction since the update.

Need some Instructions on how to get this Program up and running again.

**Comment by sidequestlegend** [comment]
Hey there, this issue tracker is not for BMBF issues im afraid.
