### ISSUE TITLE
Error: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by tmdesigned** [the-expanse/SideQuest#485]
Upon launching the app, I receive a popup:

```
A JavaScript error occurred in the main process

Uncaught Exception: Error: unable to verify the first certificate 
at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
at TLSSocket.emit (events.js:182:13)
at TLSSocket._finishInit (_tls_wrap.js:631:8)
```

There is an OK button, after which the app loads partially. The images and such load in the background, but it fails to download and extract the ADB. There is no network activity in the background.

This is my first time running the program, so it could be related to my network setup somehow. But the rest of my internet applications work fine.

**Comment by sidequestlegend** [comment]
Hi there, this is caused by an ssl error, it is usually the case when you are using a web filter, vpn or on a dodgy internet connection. This is not something we can fix in sidequest without compromising security. Thanks!
