### ISSUE TITLE
sidequest cast video button missing from menu bar

### ISSUE THREAD

**Issue by drnebula9090** [the-expanse/SideQuest#486]
I have been trying to cast my Oculus Quest to my PC screen.  I love the Sidequest app and at one point there used to be a button in the top menu bar to cast the Quest to the PC.  But it is not there anymore.  I've watched numerous videos on how to do this and they all end by having me click on this button.  Any help appreciated.

Steve

**Comment by Sskarbv** [comment]
I am also having this problem. I have v0.10.2. No cast button.

**Comment by sidequestlegend** [comment]
The Cast button is there for me ok on windows, windows is currently the only supported platform. Are you using a mac?

**Comment by Sskarbv** [comment]
Yes I’m on a Mac. But after some research I’ve found a way to manually make it work. Thanks for your response though!

________________________________

**Comment by drnebula9090** [comment]
I am using a PC – I have gotten it to work but has been hard to replicate.  It seems there is no button and if I plug in the headset and set up the wireless, the button appears.  And then sometimes I get the cast on the TV.  If I remove the cable connecting the computer to the headset, the cast goes away.  It doesn’t seem like it should be this difficult and I thought it was wireless.  Weird.

 

Steve

**Comment by Sskarbv** [comment]
Wait a second. Didn’t I email you for help? Shouldn’t you be the pro lol

________________________________

**Comment by srvrguy** [comment]
GitHub issues are really only intended for reporting bugs with the actual software. If you need support, please connect with the Discord community at https://discord.gg/HNnDPSu
