### ISSUE TITLE
Can't install bsaber patch. Error as below.

### ISSUE THREAD

**Issue by ucsdgemini** [the-expanse/SideQuest#49]
System.IO.InvalidDataException: End of Central Directory record could not be found. at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) at jsonApp.Program.RunInvocation(Invocation inv) in C:\projects\QuestSaberPatch\jsonApp\Program.cs:line 60

**Comment by grukthar** [comment]
This seems to be working for some to fix this issue.

Create a backup
Click the backup button on the top of the sync screen.

Click 'Select new base' and go navigate to that backup 
AppData\Roaming\SideQuest\bsaber-backups

set that run it, let it fail again like it has before and click restore from base. After i did that i tried sync again and it worked

**Comment by ATechAdventurer** [comment]
Some people have reported that installing WinRAR fixes the issue. I am starting to suspect that this issue stems from the extract dependency we use for all zip manipulation.

**Comment by ATechAdventurer** [comment]
Apparently, other users are reporting that if you delete songs that have art that doesn't load it will fix this issue.

**Comment by ucsdgemini** [comment]
For me it seems to be related to songs that download and have a blank coverart. If you delete those it syncs without issue for me now. The problem is many of those are songs I want.

**Comment by fascistutopia** [comment]
This is happening to me, as well.  (Same error message.) Removing songs without cover art didn't solve the problem.

**Comment by shaneharris** [comment]
Please try the latest release!
Thanks!
S

**Comment by YeThor** [comment]
I had an exactly same issue, but grukthar's process just solved the issue. 

Win 10 (64 bit) , beat saber ver1.0.2

**Comment by goldsoundz80** [comment]
I have the same issue on the Mac with the latest release but Grukthar's process also fixed it for me.

**Comment by Cheesypoofy1** [comment]
Thank you Grukthar.  Not sure why but that did the trick.

**Comment by DanjelRicci** [comment]
I really dunno why, but Grukthar's solution worked. Thanks a lot man.

**Comment by avluis** [comment]
Still happening on the latest release -- this issue needs to be reopened and further investigated
