### ISSUE TITLE
No category tabs

### ISSUE THREAD

**Issue by Peyone** [the-expanse/SideQuest#494]
Having gotten my oculus quest at long last, I instantly download Sidequest. I follow tutorials and all is well until I open the app and it doesn't look like anything shown in any of the tutorials. Most prominently the tabs/categories are completely missing and when I press browser, only 4 apps in total are available. Surely I must have done something wrong, but as I carefully checked several tutorials, found them consistent, and followed them to the letter I am unsure what that something is. 

Surely this is not how it is supposed to look once logged in, quest connected, etc? 

![sidequest](https://user-images.githubusercontent.com/64326047/80286872-48eda280-872e-11ea-86e6-fbfc2a48af05.png)

**Comment by RedBrumbler** [comment]
that's because the UI got an update yesterday and that's why all the video tutorials are outdated

**Comment by Peyone** [comment]
Surely no longer having categories and no apps coming up as downloadable cannot be an intended update?

**Comment by RedBrumbler** [comment]
They were moved to the filter menu next to the search bar at the top I believe

**Comment by sidequestlegend** [comment]
these will be fixed very soon
