### ISSUE TITLE
Show YOUR rating and review at the top of the current game page, and listings.

### ISSUE THREAD

**Issue by Rickmanx** [the-expanse/SideQuest#495]
It would be nice to see quickly which games you've rated and reviewed at the top of each game page.  Maybe always have the 1st review listed be yours.  This is if you are logged in of course.

And if you can that pull one off,  how about showing YOUR rating on any game listing?

Otherwise, great job!  This is a monthly donation I'm happy to give :)

**Comment by sidequestlegend** [comment]
added in latest version, releasing soon
