### ISSUE TITLE
Literally doesnt work.

### ISSUE THREAD

**Issue by VWPDagger** [the-expanse/SideQuest#499]
I did everything along the videos, and i have yet to see the usb debugging, yes, i have made sure the unlock pattern is disabled, yes, developer mode is on, and yes i have an organization. SideQuest WILL NOT register my quest.

**Comment by ATechAdventurer** [comment]
From a cursory glance it sounds like your cable is not working, have you verified that your computer is connecting to your quest? On windows, this can be checked using device manager. If your computer isn't detecting the quest it is likely an issue with your cable, USB port, computer, or your quest. But not SideQuest.

**Comment by VWPDagger** [comment]
The cable and computer both read that my quest is connected, if I disabled developer mode on the app and then plug in my quest, I get a pop-up in the quest about letting my computer have access to the files. But no USB debugging.

**Comment by sidequestlegend** [comment]
Hi there! We don't provide that kind of support here im afriad, this issue tracker is for bugs or feature requests. Come chat on discord and we will get it working for you - https://discord.gg/K9QkEE
