### ISSUE TITLE
A few minor aesthetic glitches with messages

### ISSUE THREAD

**Issue by ChibiBlaziken** [the-expanse/SideQuest#500]
When selecting a user in another chat sometimes it won't change over and only highlights the first one

https://cdn.discordapp.com/attachments/615234075778875453/704803593324331078/Screenshot_1614.png

Another issue is when selecting a user that has the "NEW" messages icon it doesn't vanish until you reload the entire page.

**Comment by sidequestlegend** [comment]
I haven't been able to replicate the messages not loading, it could be due to a slow internet connection, I have fixed the issue with the new messages though.
