### ISSUE TITLE
Add more app names to the "installed apps" list

### ISSUE THREAD

**Issue by subworx** [the-expanse/SideQuest#502]
Hi,

is there a way to update the internal apps list used for "installed apps" (within the desktop app) with way more real app names?
When opening the installed apps section, it shows a handful actual names, but most newer apps show up as e.g. "com.hiddenpath.phoenix" (what the heck is that?) instead of "Raccoon Lagoon".

For many apps this isn't a problem as the app name shows up somewhere in the package name, but pretty often this is not the case.

I cannot find a list in this repo, only here -> https://github.com/the-expanse/SideQuestRepos/blob/master/app-index.json, but would love to contribute an updated list.
Please let me know what I can do.
Or is that list the actual one that would require an update?

Regards,
sub

**Comment by RedBrumbler** [comment]
yeah that is the list that is used to identify package names to their app names, you can clone the repo and add entries and then just make a pull request to get them put in, I did that for BMBF cause I was tired of having to find it all the time by it's package name

**Comment by sidequestlegend** [comment]
We are working to provide a better solution to this but right now we are only accepting pull requests on this file to add new ones to the list. https://github.com/the-expanse/SideQuestRepos/blob/master/app-index.json

Thanks!
