### ISSUE TITLE
Birtdate and gdpr

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#506]
This user made a good point about gdpr compliance:
https://www.avepoint.com/blog/protect/gdpr-obligations-notice-choice-purpose-limitation/

![afbeelding](https://user-images.githubusercontent.com/51795403/80722456-ab182000-8aff-11ea-8818-89f67f538971.png)

**Comment by sidequestlegend** [comment]
Hey! THe datepicker on sign up was overhauled in a recent update so this is no longer an issue. I have also added the following adjustment to the privacy policy:


<h6>Verifying your age</h6>
  <p>
    Your date of birth is used to verify that you are old enough to be able to use the SideQuest website - over 13 years of age.
    This data is not used for another other purpose.
  </p>
