### ISSUE TITLE
Corrupted Songs from BSaber

### ISSUE THREAD

**Issue by ATechAdventurer** [the-expanse/SideQuest#51]
It appears that some songs download from beastsaber have the following internal structure:
- ###-####.zip
 - ###-####/
  - Song Name/
   - files

instead of
-###-####.zip
 - Song Name/
  - files

This seems to cause issues when traversing the folder for songs to convert with songe-converter which causes QuestSaberPatch to fail.

**Comment by shaneharris** [comment]
interesting. I wonder what the best way to handle this is, we should maybe flatten and restructure the folders. 
 
I can talk to the bsaber.com guys and see do they want to correct those or whats the plan, they were talking about a conversion to a new format.

**Comment by shaneharris** [comment]
example - 8297-8384

**Comment by shaneharris** [comment]
Please try the latest release!
Thanks!
S
