### ISSUE TITLE
dropdown menu does not go away and you can't make it

### ISSUE THREAD

**Issue by jepp** [the-expanse/SideQuest#513]
The dropdown menu that shows up for the extra icons when the window gets to small doesn't go away. It doesn't go away when you click that dropdown menu again to hide it, when you click elsewhere in SQ, or when you make SQ bigger again and those menu icons show up.

![image](https://user-images.githubusercontent.com/744998/80752503-36d68000-8af1-11ea-867f-40a0522f8d2d.png)

The only thing that seems to make it go away is actually choosing something from that menu.

Edit: I did find that it would go away if I click in the banner area, but not in the larger bottom content area.

**Comment by sidequestlegend** [comment]
thanks for this, this should have been working but i obviously introduced a regression recently. I have fixed this behaviour and also added a backdrop 

![image](https://user-images.githubusercontent.com/6830845/80796607-88d1e100-8b97-11ea-83d8-849784d3e7ec.png)
