### ISSUE TITLE
Make "Get SideQuest" more prominent on the top bar 

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#525]
Possibly look at other ways to highlight it with an alert bar or a modal popup.

**Comment by mgschwan** [comment]
I am not a big fan of modal popups as people tend to ignore them as ads. Maybe some adblocker even block them?

I think it would be a good idea to include the information about installing sidequest into the normal flow of the information. A user who is new to Sidequest will probably look for some information on how to install/downlaod the game.

Here is an example that I think could work

![Screenshot_2020-05-06 SideQuest - Make it your own](https://user-images.githubusercontent.com/381908/81169041-6de8dd80-8f98-11ea-9a9d-b6c29de0f17c.jpg)

**Comment by sidequestlegend** [comment]
thanks for this, i think i can achieve something that fits here

**Comment by sidequestlegend** [comment]
Looking at this I think the best idea is to make the GET SIDEQUEST button more prominent. Chatting with the team we think the information around installing is a bit redundant. 

![image](https://user-images.githubusercontent.com/6830845/81565254-f4cef900-9390-11ea-8092-6788f8a1e2ce.png)

Lets try this for a while and we can revisit if need be.
