### ISSUE TITLE
Is there a public api?

### ISSUE THREAD

**Issue by D4rkC00d3r** [the-expanse/SideQuest#529]
Hi I wanted to port the functionality to a native Android app that would allow it be installed on the Quest. Once installed you could browse the store and download and install from within the headset. This would remove the need for a PC and as the quest is portable would be a great fit.

I have found your endpoints for the store listings but I am unable to query them.

Firstly would you allow me to query the store and essentially port it to Android natively.

Regards

**Comment by RedBrumbler** [comment]
On device versions will not be allowed

Check this issue for the reasoning: https://github.com/the-expanse/SideQuest/issues/409#issuecomment-592418360

**Comment by sidequestlegend** [comment]
Hey there! Other than the issues listing in the above comment, I'm afraid this is specifically against the [Oculus App Policy](https://developer.oculus.com/policy/app-policies/). I draw your attention to the below paragraph.

```
The Oculus Platform is intended to provide quality content designed to operate on Oculus devices. In order to safeguard the integrity of the Oculus Platform and promote a good user experience, apps cannot enable or facilitate any installation, distribution, download or access with respect to any other platform, app or game, or any content package or other add-on, plug-in or extension, except as expressly authorised by Oculus to you in writing.
```

This means we cant support this. We are looking at providing a public API, but it will not include download links.
