### ISSUE TITLE
Add "delete beat saber" option to SideQuest

### ISSUE THREAD

**Issue by ChrisHonniball** [the-expanse/SideQuest#53]
Many users are are experiencing the "I can't delete the game" issue. If possible, add a "delete beat saber" in SideQuest so that we all can then download a fresh copy off of the Oculus store.

**Comment by ATechAdventurer** [comment]
You can already delete beatsaber from SideQuest by pressing the 3 line icon on the top right, but a button like that would be convenient.

**Comment by shaneharris** [comment]
added instructions in the latest release page for this!
