### ISSUE TITLE
Support multiple successive line breaks in App Description

### ISSUE THREAD

**Issue by andrelevi** [the-expanse/SideQuest#530]
Supporting more than one successive line breaks would help a lot with formatting the description, so that we could have more whitespace between lines for better readability. Right now having multiple `<br>` tags like `<br><br>` only results in a line break, not an entire blank line.

**Comment by sidequestlegend** [comment]
this is a good suggestion. This was actually intended to work this way but due to a bug it has not turned out that way. We currently use a discord flavour of markdown but we are considering moving to github markdown. 

I should have this fixed by monday

**Comment by sidequestlegend** [comment]
this has been fixed and will release soon.
