### ISSUE TITLE
SideQuest Installation issue 

### ISSUE THREAD

**Issue by YeetVR** [the-expanse/SideQuest#532]
When trying to complete my installation of SideQuest I can't get it to connect the quest with it. Where it should say connected in top left it just says " Not detected" I am installing using Linux and it's worked before but I installed it due to space needed. I've tried to install it 2 now after I installed it but it's just not working.

**Comment by sidequestlegend** [comment]
HI there! We dont offer technical support here im afraid but you can get help in our discord -https://discord.gg/Htgn2y
