### ISSUE TITLE
Feature Request: Like/Dislike buttons for user reviews

### ISSUE THREAD

**Issue by andrelevi** [the-expanse/SideQuest#535]
Some apps are unfairly given bad reviews, like the recent Archviz app that had a 1/5 star review as its first review, due to it not having any "gameplay", when it was obviously just supposed to be a polished Archviz concept app. I think we should be able to dislike/downvote user reviews like this, and maybe the like-to-dislike ratio can affect the weighting of how the review score is applied to the average rating score.

**Comment by sidequestlegend** [comment]
Thank you for bringing this to our attention, I have removed the review you mentioned. We do moderate the reviews and will remove any review deemed to be not helpful to other users or a technical support issue or just trolling, but an upvote system would also make a lot of sense and take some of that workload off us - it is mounting up as user numbers increase. It would also remove our bias which i think is good too. 

Thanks for this! Stay tuned for updates!

**Comment by sidequestlegend** [comment]
I have decided to postpone this feature until we see what is happening with the new oculus system, don't want to invest in a huge workload if the reviews will be moving more to the oculus tore listing. We are working on some new community driven features releasing soon that will also solve this issue mostly, stay tuned!
