### ISSUE TITLE
Make "search" also search in packages names

### ISSUE THREAD

**Issue by korenmic** [the-expanse/SideQuest#536]
many times I am playing a game I have long time ago installed from sidequest
since its common for games packages' names to have nothing to do with the actual games
when I try to search the game (to give feedback for example or check for updates)
in the sidequestvr web page using the only name I have (the package name)
I usually fail to find it.

the latest example I have is a package called "be.TheSnoopyHouse.LD45" that I downloaded from sidequestvr, I have no idea of the package's game actual name, and so when I try to search the sidequestvr web page for 'the snoopy house' or any of those words or even "be.TheSnoopyHouse.LD45" or "TheSnoopyHouse" I find nothing.

if "search" would also search in packages names, then I would be able to find the page for the game

(that is, until an enforced standard forces all developers to have the correct name in the package names)

**Comment by sidequestlegend** [comment]
good point, i will fix this soon. Thank you!

**Comment by sidequestlegend** [comment]
this is fixed!
