### ISSUE TITLE
Add a warning message if the next install will b/reach 100% storage capacity

### ISSUE THREAD

**Issue by korenmic** [the-expanse/SideQuest#537]
I am nearing my 100% storage capacity, and without even noticing that I keep adding more games
they download in the background quite some time just to tell me that they have failed at the end
when that information was theoretically available beforehand.

with `df -H | grep data/media` you could parse how much space is left
and with the expected package install size (I suppose such information should be available per package, right? even if not, it would be at least the size of the apk+obb files as installers are compressed and not increased, compared to the final size that is, so that is enough data for generating a warning either way)

you could estimate if the free space is enough for the package to be installed, if not you could add a warning and ask the users if they are sure they want to continue with installation attempt even though it is expected to b/reach 100% storage capacity.

it would save users the time of the installation attempts if they are all about to fail anyways.

**Comment by sidequestlegend** [comment]
this could be tricky right now, as each file is downloaded and installed individually we could only do this on a per file basis meaning it should only be as useful as the adb error in failing to install. ill look at #538 and see if that is resolvable and this should then be somewhat redundant

**Comment by korenmic** [comment]
> this could be tricky right now, as each file is downloaded and installed individually we could only do this on a per file basis meaning it should only be as useful as the adb error in failing to install. ill look at #538 and see if that is resolvable and this should then be somewhat redundant

Just saying - actually I do believe the fill up experience I had was mostly because I really had too many legit installations taking up free space and not just because of cleanup errors.

**Comment by sidequestlegend** [comment]
I'm going to close this one as on further investigation its not really possible to know the true install size until its on the device meaning it would result in separate errors that mean the same thing. I think its better to rely on the ADB error here for consistency.
