### ISSUE TITLE
Suggestion: move install APK button to the bottom

### ISSUE THREAD

**Issue by victorpinto** [the-expanse/SideQuest#54]
I was a bit confused why I kept on clicking sync selected and the songs would not appear in the beatsaber app. I realized only after doing it 5 times that the button to install the new apk was at the top of the dialogue. 

maybe moving it to the bottom after it tells you what is presently in the build, as opposed to at the top of said dialogue. 

cheers, thanks for all the hard work, you guys are awesome!

**Comment by ATechAdventurer** [comment]
Thanks for the encouraging words and the suggestion. We will definitely take your suggestion into consideration as we make the program easier to use.

**Comment by shaneharris** [comment]
this is done in the latest version! releasing soon!
