### ISSUE TITLE
Anti-spam on reviews

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#540]
ill be removing the hyperlink function in reviews soon ( unfortunately for some legitimate users ) and adding ip logging to reviews. I will auto disable someones ability to review if they add more than 10 reviews in a 24 hour period from the same user or IP.

**Comment by sidequestlegend** [comment]
Also ban similar text reviews.

**Comment by sidequestlegend** [comment]
Also add a mass delete option for all reviews left in the last 24 hours.

**Comment by RedBrumbler** [comment]
>  I will auto disable someones ability to review
make it disable yeah, could just be someone reviewing lots of apps in one go
