### ISSUE TITLE
Try to build one last 32bit build...

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#547]
... so that users can at least use the new version of sidequest since the major breaking changes recently.

**Comment by sidequestlegend** [comment]
Just need to find a 32bit machine / VM to build on. Will probably have to build locally so it wont be signed but im sure that is fine for those that want it.

**Comment by sidequestlegend** [comment]
Downloading 32bit windows, Ill be attempting this build in a few hours after i get this OS installed into a VM. watch this space...

**Comment by sidequestlegend** [comment]
https://cdn.glitch.com/7f1ba65c-9a32-4aa6-a822-755fe58ea4dd%2FSideQuest-0.10.7-ia32-win.zip?v=1590485295900

Took less time than expected. I have removed the auto update so this wont try to download new versions in 64 bit.

**Comment by deadringer28** [comment]
It's working. Thanks so much for this. I just loaded it connected my Quest installed and played Blanketworks. Thanks so much.

**Comment by sidequestlegend** [comment]
that is great to hear! I have setup this short url that points to this issue for future reference - [sdq.st/32bit](https://sdq.st/32bit)
