### ISSUE TITLE
Mac: icon to add to SideQuest disappears after crash or restart

### ISSUE THREAD

**Issue by SteveW25561** [the-expanse/SideQuest#55]
on my Mac (after fresh install, deleting the application support directory) - Sidequest will load songs using the little SideQuest but then it’ll randomly seem to sit cycling with the “adding to custom songs” window and a blue cycling arrow (nothing else is clickable). 

If I exit Sidequest and restart it, none of the songs on the browser show the "add to Sidequest" icon. (I note the Sidequest icon gets added dynamically when it’s working properly). I have to uninstall completely deleting the Application Support folder to get the icon to add songs again.

This occurs with or without the Oculus Quest attached to the Mac

**Comment by shaneharris** [comment]
Please try the latest release!
Thanks!
S

**Comment by gabewil** [comment]
This is still happening to me on the latest release.
