### ISSUE TITLE
Fist Start Takes Forever to Download

### ISSUE THREAD

**Issue by CHHHHAH** [the-expanse/SideQuest#550]
This is so time wasting to download something that freezes on 0.05 / 0.37 %... any solution?

**Comment by sidequestlegend** [comment]
This is usually caused by an intermittent internet connection, what is Fist Start ? is it a game or a typo?

**Comment by CHHHHAH** [comment]
I solved it by using different connection thank you very much :) have a nice day



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SideQuest"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 下午4:25
收件人: "the-expanse/SideQuest"<SideQuest@noreply.github.com&gt;; 
抄送: "午觉，云飘天上"<961700436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [the-expanse/SideQuest] Fist Start Takes Forever to Download (#550)





 
This is usually caused by an intermittent internet connection, what is Fist Start ? is it a game or a typo?

**Comment by sidequestlegend** [comment]
great!
