### ISSUE TITLE
Sidequest looks Different

### ISSUE THREAD

**Issue by Murphy2021** [the-expanse/SideQuest#551]
My sidequest doesnt look like anyone else and i cant figure out how to update it...please help.

**Comment by srvrguy** [comment]
You can always download the latest version from sidequestvr.com. That's the best bet to get updated.

**Comment by Murphy2021** [comment]
We have been trying to download it but it still looks like the old version
and not the new updated version everyone is using.

**Comment by sidequestlegend** [comment]
Assuming you are on windows - try this download link. 
https://github.com/the-expanse/SideQuest/releases/download/v0.10.7/SideQuest-Setup-0.10.7-x64-win.exe

If you still have problems try to take a screenshot of sidequest, or tell us the version number it has in the top left of the window. 

You may have an older version of sidequest installed somewhere.

**Comment by sidequestlegend** [comment]
Closing this in favour of the new support portal at https://sdq.st/support
