### ISSUE TITLE
v0.10.7 Connecting will not change

### ISSUE THREAD

**Issue by Onion78** [the-expanse/SideQuest#553]

**Comment by Onion78** [comment]
Hi, I recently changed Quest headsets due to a dead pixel. The original Quest allowed SideQuest really easily but the new one will not connect. I have factory reset the headeset several times. I have uninstalled and reinstalled ADB driver ensuring only one is on my machine. I have uninstalled SideQuest and used the uninstall sidequest exe as well. Every time SideQuest loads with the orange circle stating "v0.10v7 Connecting..." and this does not change. I do get an error sometimes at the bottoim of the app stating - 
Error: Command failed: "C:\Users\XXX\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s undefined usb '"C:\Users\XXX\AppData\Roaming\SideQuest\platform-tools\adb.exe"' is not recognized as an internal or external command,
 operable program or batch file.

Can anyone help with this please? I have followed the trouble shooting and FAQ's and nothing has worked so far.

Thanks

**Comment by sidequestlegend** [comment]
Hey there! It looks like ADB is corrupt. If you click the wrench icon at the top and click "open adb folder". Then delete that folder and restart sidequest. It will re-generate the contents of that folder. This is due to an intermittent error in sidequest and will be fixed very soon.

**Comment by sidequestlegend** [comment]
Closing this in favour of the new support portal at https://sdq.st/support
