### ISSUE TITLE
Look at running chrome os in a VM on virtual box to see if there are any obvious blockers there

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#557]

**Comment by srvrguy** [comment]
I'm not sure that's going to work. The "Linux" option on Chromebooks uses hardware virtualization and likely won't work or be supported if ChromeOS is already running as a VM.

**Comment by deadringer28** [comment]
How about the idea of getting sidequest running as a native ChromeOS app?

**Comment by RedBrumbler** [comment]
Does adb still work then on chromeOS? Cause I believe that was the cause for no SQ in chromebooks, adb got broken by an update to the OS

**Comment by deadringer28** [comment]
Any updates on this one?

**Comment by sidequestlegend** [comment]
Apologies I haven't found the time to get this setup yet the last few weeks have been mad. Im not sure exactly when ill be free even yet but as soon as im free ill give this a whirl. I expect a few weeks at the most.

**Comment by deadringer28** [comment]
> Apologies I haven't found the time to get this setup yet the last few weeks have been mad. Im not sure exactly when ill be free even yet but as soon as I'm free ill give this a whirl. I expect a few weeks at the most.

No worries thanks for letting me know it is still in the works as a possibility. I am still in my glory over the 32-bit windows version so thanks again for that

**Comment by sidequestlegend** [comment]
I am going to officially sunset this idea, its too much work to maintain this on chromebooks since things are changing so often.

**Comment by deadringer28** [comment]
That unfortunate but completely understandable. thanks for your consideration. Hopefully, sooner than later we will see the fruits of your labor, realized directly in the Quest, through the efforts that Oculus wants to bring to non store games and experiences. Appreciate all that you do.



________________________________
