### ISSUE TITLE
Persists despite fresh install "System.IO.InvalidDataException: End of Central Directory record could not be found"

### ISSUE THREAD

**Issue by SteveW25561** [the-expanse/SideQuest#56]
The infamous error "End of Central Directory record" still persists despite deleting the whole SideQuest folder in Application Support on the Mac and restarting the Quest.

System.IO.InvalidDataException: End of Central Directory record could not be found. at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) at jsonApp.Program.RunInvocation(Invocation inv) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp/Program.cs:line 60, Error: /data/local/tmp/_stream.apk could not be installed [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1267119490.tmp/base.apk: AndroidManifest.xml]

**Comment by ATechAdventurer** [comment]
Duplicate of #49
