### ISSUE TITLE
Installation Aborted

### ISSUE THREAD

**Issue by MiniSmooth** [the-expanse/SideQuest#566]
When trying to install SideQuest for the first time I got the SetUp file off the download page, i opened it and it started downloading. It the stopped half way as said Installation Aborted, is there a fix to this?
![Annotation 2020-06-06 133611](https://user-images.githubusercontent.com/66519301/83944332-b34c3500-a7fa-11ea-8b18-14e82b7c0d5d.png)

**Comment by RedBrumbler** [comment]
![afbeelding](https://user-images.githubusercontent.com/51795403/83944898-3a9fa580-a807-11ea-9101-8c53df9f397e.png)

[Here's the link it mentions](https://github.com/the-expanse/SideQuestRepos/releases/download/Uninstaller/Uninstall_SideQuest.exe)
