### ISSUE TITLE
Prevent screensaver when streaming to PC

### ISSUE THREAD

**Issue by vaxul** [the-expanse/SideQuest#576]
Like any other media, when streaming the headset to the PC, the screensaver should be disabled. At least in fullscreen mode.

Thank you

**Comment by sidequestlegend** [comment]
This would need to be submitted to the scrcpy repo i think, its outside of the remit of sidequest

https://github.com/Genymobile/scrcpy

**Comment by vaxul** [comment]
I filed an issue there https://github.com/Genymobile/scrcpy/issues/1514

**Comment by vaxul** [comment]
@sidequestlegend an option will be added soon, see https://github.com/Genymobile/scrcpy/pull/1502

**Comment by vaxul** [comment]
It's merged into develop.
https://github.com/Genymobile/scrcpy/commits/dev

**Comment by sidequestlegend** [comment]
Great! Ill keep an eye out for when it makes it to a release
