### ISSUE TITLE
Can't reconnect with wifi, even when IP is unchanged

### ISSUE THREAD

**Issue by vaxul** [the-expanse/SideQuest#577]
Hi, I'm impressed how well the wifi connection mode is working. Thanks for this.

The only thing in the moment, I can't connect to my Quest via wifi at start. The quest has a static local IP address assigned by the router.

Currently I have to first connect the Quest via USB, Afterwards I can connect via wifi mode.

How to trace this issue? Are there any logs to share?

**Comment by sidequestlegend** [comment]
Hi there! Its an ADB security measure that if your headset is restarted then the cable must be connected again to enabled tcpip on the headset. Does this sound like what is happeneing?

**Comment by vaxul** [comment]
Thanks for the response. It's sound exactly like that. I had shutdown the Quest before.

So it's currently not possible.
