### ISSUE TITLE
Do not pre-select a review rating, force the user to set it. 

### ISSUE THREAD

**Issue by sidequestlegend** [the-expanse/SideQuest#581]
This will result in less mistakes and could provide a better representation of the users rating if they have to make a conscious choice.

**Comment by TiagoRechau** [comment]
Hey, I would like to help on this., but was not able to find the code on this repo

**Comment by RedBrumbler** [comment]
That's because sidequest is closed source now

**Comment by sidequestlegend** [comment]
added in the latest version, releasing soon.
