### ISSUE TITLE
installing Virtual Desktop VR Patch  side quest

### ISSUE THREAD

**Issue by gestion419** [the-expanse/SideQuest#582]
I have receive this error
Error: Command failed: "C:\Users\WP\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s undefined push "C:\Users\WP\AppData\Roaming\SideQuest\patch.1.VirtualDesktop.Android.obb" /sdcard/Android/obb/VirtualDesktop.Android/patch.1.VirtualDesktop.Android.obb

**Comment by RedBrumbler** [comment]
![afbeelding](https://user-images.githubusercontent.com/51795403/85730566-0a5a7100-b6fa-11ea-947f-542a85a7cb5f.png)

**Comment by sidequestlegend** [comment]
this now shows a much better error in this case so i will close this.
