### ISSUE TITLE
Scrcpy stream pausing, new --stay-awake parameter available in v1.14

### ISSUE THREAD

**Issue by Ionwerks** [the-expanse/SideQuest#588]
I have an issue with the scrcpy streaming in that it will periodically pause (on the last served frame) until I Alt-Tab away from it and back (whereupon it immediately starts running again). This is while playing Beat Saber, don't know if it happens with any other apps running on the headset. The interval is very screensaver-like (3-5 minutes-ish) though I have no screensaver enabled (Windows 10).

A newer version of scrcpy is now available ([1.14](https://github.com/Genymobile/scrcpy/releases)) which adds a --stay-awake parameter which I thought might fix this issue. I wonder if you might update the download and expose this setting in the UI?

While somebody's looking at this, it'd be great if this dialog saved the last used options and then preset the dialog with the same the next time it's opened.

**Comment by sidequestlegend** [comment]
Thanks for this, ill look at adding the saved preferences ( i thought this was already the case ) and the updated version of scrcpy in the next release.

**Comment by Ionwerks** [comment]
Cheers, it might be that some fields are saved but I do always need to set Fullscreen (the only setting I change).

In an ideal world I think the stream would fullscreen by default but as the window then doesn't have any obvious way to close it I can see why you wouldn't. A titlebar or close widget that drops down when you move the mouse to the top would be ideal but I guess that would have to be added to scrcpy rather than SQ.

**Comment by sidequestlegend** [comment]
added an releasing in the next version soon.
