### ISSUE TITLE
Open API for Private Listing keys

### ISSUE THREAD

**Issue by ownstoppable** [the-expanse/SideQuest#594]
Right now it's quite hard to manage keys on SideQuest portal when their numbers start to increase. Also, when we create a key we can't assign it to someone, so it's hard to track until it gets activated.

Would it be possible if you guys created a public API for these requests?

1. Create new key: https://api.sidequestvr.com/get-app-invite
2. Revoke key: https://api.sidequestvr.com/revoke-app-invite
3. List keys: https://api.sidequestvr.com/get-app-invites

This way people could use your API to manage keys from their systems. For example for my users I could automatically generate a key and assign it on my system, making it easier for me to manage all keys.

All of those requests need a token, and I also noticed that you have a Refresh token request: https://api.sidequestvr.com/refresh

It seems like everything is already in place, but this is not publicly known, and I guess you guys might change it at any time so I didn't want to use it before you guys make it public.

**Comment by sidequestlegend** [comment]
I have been thinking about this problem a lot. After discussing with the team we don't think it's the best idea to expose this as an API on its own without fully fleshing out a complete API for accessing and controlling things on SideQuest. This means there will be a delay until we can get this in place.

In the mean time we have been working on access control for apps, we have some new features and improvements on the existing private listing options which I hope will make it easier to work with until we can get the public API up and running. 

Here is a preview of some new features that were already on the road map we are rolling out in the next update releasing very soon. 
![image](https://user-images.githubusercontent.com/6830845/89546323-61c12600-d7fc-11ea-8424-3da7fd411eb6.png)

### Bulk Key Generation
You can now generate 10 keys at the click of a button. Click multiple times for several batches of keys. 

### Export Invites
You can now also export the full list of invite urls along with the names of the users if they are assigned.

### Access Requests
This is a whole new feature that allows for you to accept users to access your listing. Accepted users will have invite keys generated and automatically accepted by those users thus allowing you to know the user in advance of granting access, and also grant access with out the user needing to visit the app listing first. We will email them to let them know when they are able to access it with a button to open the listing.

Coming very soon!
