### ISSUE TITLE
issuee installing pavlov on my Quest 

### ISSUE THREAD

**Issue by Karlsson2119** [the-expanse/SideQuest#595]
I get this error when trying to install: 
A task failed. Check the tasks screen for more info. Pavlov: Shack - Failed to transfer file: Error: Command failed: "C:\Users\KARL\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1PASH9AMKN0205 push "C:\Users\KARL\AppData\Roaming\SideQuest\main.22.com.vankrupt.pavlov.obb" /sdcard/Android/obb/com.vankrupt.pavlov/main.22.com.vankrupt.pavlov.obb

Hope someone can help 

BR
Nicolai

**Comment by sidequestlegend** [comment]
Hi there, try another usb cable or port. Closing as not an issue with sidequest. If you want to submit a support ticket here is the service desk - https://sdq.st/support.
