### ISSUE TITLE
Unconditional ADB via TCPIP

### ISSUE THREAD

**Issue by Ionwerks** [the-expanse/SideQuest#598]
Hello, me again. I'm a bit of an Android noob so I may have made some incorrect assumptions but I wanted to query the implementation of ADB over Wi-Fi. As far as I can tell the connection will only succeed if the Quest is currently connected via USB (otherwise yielding _"Adb command failed - No device connected!"_). That is to say it will only try to connect over wi-fi if it has first been able to explicitly set the Quest to listen via TCP/IP? This is a tad inconvenient if;

- You've restarted SQ (or your PC) since setting the Quest to wireless ADB (you have to plug the Quest in again rather than just connecting over wi-fi to an already listening Quest.

- You've used some other device to set the Quest to wireless ADB (I sometimes use my phone via an OTG cable).

Conversely, if I've set the headset to wireless ADB with SQ I can then connect to it wirelessly using my phone (provided I exit SQ). Would be handy if it worked the other way around also.

If my assumptions are correct could I suggest that SQ should set the Quest to wireless ADB if it's currently connected over USB but always attempt a wi-fi connection even when the Quest isn't present on USB. My Quest has a DHCP reservation so it's always available at the same address (as last connected to) though perhaps there would be a case for making the IP field editable.

EDIT: Left out one of the primary reasons for desiring the ability to freely switch Wireless-ADB control - apps that allow you to change settings from within the headset; https://www.youtube.com/watch?v=_Xg-hjrcS2k

**Comment by sidequestlegend** [comment]
Hi there! I'm afraid this would generate too many support requests as many network configurations can mess with the reliability of the wireless connection. Wireless ADB has always been temperamental even outside of the scope of SideQuest, so shifting to a wireless first initiative will lightly result in a lot of problems. 

However this could be enabled with a configuration so I have  moved this issue over to the new repo here - https://github.com/SideQuestVR/SideQuest/issues/72
