### ISSUE TITLE
Downloaded songs not showing in library

### ISSUE THREAD

**Issue by Cravendor** [the-expanse/SideQuest#60]
MAC user - Songs I downloaded are not showing in the library.

My first attempt to install the app, everything works fine.
On my second attempt to upload new songs the app crashes. I restart the app and the library was empty. Also the download buttons were missing on the website.
 
I removed the app, remover the side quest folder in library. And did a clean and fresh install.
The download buttons are showing now. But the downloaded songs are not showing.

There were no signs of error in the debug window

**Comment by amydionne** [comment]
Same issue but lost everything as i was told to uninstall beat saber, well it wouldn't uninstall through the library but did through the sidequest app. When I deleted and reinstalled I then got the error through sidequest that it couldn't sync because my beat saber was the wrong version.

**Comment by shaneharris** [comment]
Please try the latest release!
Thanks!
S

**Comment by retorquere** [comment]
The latest release being 0.2.2? I also don't see new songs, could install new song first time. My BS is 1.0.2.

**Comment by wraithguardomega** [comment]
i just tried with the latest release and the latest patcher. it still doesnt like the folder structure of some songs. if its not in a song folder than if i make one and put the files in it, then reopen sidequest it says there no info.dat, even though it seems to have made one once it notices the folder. restart sidequaest again wthout doing anything and it noticed the .dat file fine but then i get another "empty folder" error and have to repeat the process to fix and songs not zipped inside a songname folder.
