### ISSUE TITLE
Sidequest website messaging list would not scroll when using firefox browser 

### ISSUE THREAD

**Issue by LucSkyward** [the-expanse/SideQuest#602]
I'm using firefox browser, the message list on sidequest website can not be scrolled, only can see least 3 new messages

**Comment by sidequestlegend** [comment]
Turns out this is a bug in firefox that has already been fixed upstream - https://bugzilla.mozilla.org/show_bug.cgi?id=1042151

It will land once firefox 81 is released. You can get firefox nightly if you want it now. Should be a few weeks.
