### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE error when attempting to install app

### ISSUE THREAD

**Issue by briantully** [the-expanse/SideQuest#603]
When trying to install an app (Wildzone) I get the following error:

```A task failed. Check the tasks screen for more info. Wildzone: : UNABLE_TO_VERIFY_LEAF_SIGNATURE```

Is this a Sidequest issue or an issue with the app's installer?

**Comment by briantully** [comment]
No, I'm not using a VPN. I'm able to install other games without issue. It's just this one game (Wildzone) that has the issue, leading me to believe either the installer is borked or a SideQuest issue.

**Comment by srvrguy** [comment]
It might also be an expired or misconfigured certificate for the server hosting the application. SQ doesn't actually store the applications itself, they are downloaded from a URL provided by the author of the entry (usually the application developer). SQ is based on Electron, and verifies certificates against an internal CA list. If it can't verify the certificate chain, this type of error will be made. Usually, that error indicates a misconfiguration as the server isn't sending the intermediate certificate and thus can't verify the server's (or the "leaf") certificate.

I suggest contacting the developer of that application and letting them know their apk download seems to have some issues.

**Comment by sidequestlegend** [comment]
Good point, not sure if it has been changed since but that game points to drop box -https://www.dropbox.com/s/2m6nec582muf0n3/Wildzone.apk?dl=1

I have had increasing problems with dropbox recently though. I'm looking at providing some OVH cold storage option soon.
