### ISSUE TITLE
filepath bar overlaps items in file browser list

### ISSUE THREAD

**Issue by RedBrumbler** [the-expanse/SideQuest#604]
![afbeelding](https://user-images.githubusercontent.com/51795403/91098050-0f3b9280-e661-11ea-8199-f55c5b769a8a.png)
if the filepath is long enough and the window is shrunk horizontally the filepath will jump to the next rule but by doing so cover up about the first file entry in the list of files

**Comment by sidequestlegend** [comment]
moved to https://github.com/SideQuestVR/SideQuest/issues/71
