### ISSUE TITLE
Try to open sidequest application, but nothing happens

### ISSUE THREAD

**Issue by ViraInsight** [the-expanse/SideQuest#66]
Sidequest icon comes up in the tool bar, but nothing shows up. Not sure what to do.

**Comment by Purplexgd** [comment]
If you're on Mac, it seems tons of us are having that issue.

**Comment by ViraInsight** [comment]
Im on a Windows PC, but the weird thing is that it was working before, a couple of days ago.

**Comment by ViraInsight** [comment]
i just wanted to get the latest update and this issue started to happen. I even got this emergency fix that uploaded an hour ago

**Comment by shaneharris** [comment]
Please try the latest release!
Thanks!
S

**Comment by ViraInsight** [comment]
I fixed the issue.
I had to put the .EXE folder into my main hard drive. 
It ran after that.
