### ISSUE TITLE
Beat Saber emergency patch not working

### ISSUE THREAD

**Issue by SoonerDoc** [the-expanse/SideQuest#69]

**Comment by SoonerDoc** [comment]
When trying to sync get

Run QuestSaberPatch

Install failed

There was an error installing.  Before you see it would you like to reset your beat saver...

**Comment by sjb933** [comment]
I see the same failure when pressing 'Sync Selected'.  It fails very quickly and the error message is pretty vague:

> FailError: Failure: 'open failed: No such file or directory'

**Comment by shaneharris** [comment]
Please try the latest release!
Thanks!
S

**Comment by relsirc** [comment]
Still getting this error on the latest release

**Comment by SoonerDoc** [comment]
I am also still getting the error.

**Comment by ihainan** [comment]
![image](https://user-images.githubusercontent.com/3169221/59039996-6ca2c280-88a8-11e9-8a5f-5fdca8010373.png)

Same error here.
