### ISSUE TITLE
Error Syncing New Beatsaber 1.01

### ISSUE THREAD

**Issue by amydionne** [the-expanse/SideQuest#71]
System.IO.InvalidDataException: End of Central Directory record could not be found. at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) at jsonApp.Program.RunInvocation(Invocation inv) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp/Program.cs:line 60

I received this error in the new 1.01 release

**Comment by amydionne** [comment]
Got it working, took a few times but its good to go now. Thank you for all your hard work

**Comment by eburf12** [comment]
How did you fix this issue?
