### ISSUE TITLE
APK URL should be shown to reduce potential for distribution of compromised apps

### ISSUE THREAD

**Issue by mikedg1** [the-expanse/SideQuest#72]
By showing the APK source, a user can have some additional confidence that they are downloading from a source that puts some effort into verifying that the APKS have not been tampered with.

If a repository is ever compromised, an APK download can be diverted to a source containing tampered code that could compromise a users accounts. Since SideQuest encourages the sideloading of applications that use accounts of high value, like Hearthstone, this becomes an important feature

**Comment by shaneharris** [comment]
![image](https://cdn.discordapp.com/attachments/588048600295145559/588765954360606731/unknown.png)

I hope that helps!
