### ISSUE TITLE
Beat saber pushed another update 

### ISSUE THREAD

**Issue by amydionne** [the-expanse/SideQuest#73]
Beat Saber pushed another update 1.0.2 not sure if it will have an impact but just a heads up.

**Comment by jj-routerguy** [comment]
I'm seeing wrong Version 1.0.2, and getting this error:

> 
System.IO.InvalidDataException: End of Central Directory record could not be found. at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) at jsonApp.Program.RunInvocation(Invocation inv) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp/Program.cs:line 60, Error: /data/local/tmp/_stream.apk could not be installed [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse 

/data/app/vmdl1602518037.tmp/base.apk: AndroidManifest.xml]

**Comment by amydionne** [comment]
Because you updated you app and this is only compatible I believe with 1.0.1 from yesterday.

**Comment by hughesnetworking** [comment]
> Because you updated you app and this is only compatible I believe with 1.0.1 from yesterday.

Yes I am sure he did, as the instructions for the most recent release explicitly told him to do more then once by stating in no uncertain terms to start with a fresh install from the Oculus store.

**Comment by amydionne** [comment]
True, so yah than people will in fact run into a problem. I don’t know 🤷‍♀️ just trying to help.

**Comment by hughesnetworking** [comment]
Hopefully the solution will be obvious to most people. We just have to wait for the tool we use to be on the same version as the software we use it on. Beat Saber has put out a couple updates right as this tool was getting off the ground unfortunately but if people know enough to be here, and to read these issue threads specifically, then they should be smart enough to understand a simple version mismatch message and to know that all they can do is wait for another update to the tool. 

be patient people.

**Comment by amydionne** [comment]
Agreed.

**Comment by Namiriu** [comment]
Same problem here, just want to install SideQuest but the message "WRONG BEAT SABER VERSION 1.0.2" stay to the screen. Does this mean i can't play Beat Saber until the new update of SideQuest compatible w BS 1.0.2 is out ?

**Comment by hughesnetworking** [comment]
No it doesn't mean that if I just go by what you said. You can play the version you have installed. You just can't mod it or add new songs to it until an updated sidequest is released.

**Comment by Namiriu** [comment]
Okay thanks a lot for the answer.

**Comment by JulianHH** [comment]
Thanks for the update to support 1.0.2, too!

However, the compiled app does not start on mac os 10.14.3 (error -47).

Any ideas?

**Comment by jj-routerguy** [comment]
Just wanted to say it is working now.
**THANKS**

**Comment by shaneharris** [comment]
Thank you! Ill close this then!
