### ISSUE TITLE
Installing SLR Quest installs SLR Go

### ISSUE THREAD

**Issue by shanness** [the-expanse/SideQuest#74]
Title says it all really.  Says Go in the quest, and also in the SideQuest UI (after installing the Quest one).  Notice the tick in the screenshot below.

![image](https://user-images.githubusercontent.com/631580/58977265-b4740c00-880c-11e9-920a-69a0ba4f6427.png)

**Comment by shaneharris** [comment]
They share the same package name unfortunately. It is the right version it only shows up as the go version in sidequest but works fine in your headset. Since we cant change the apps package name easily i have to close this one

Thanks for reporting!

**Comment by shanness** [comment]
Ahh, OK, thanks for that.  I assumed I could trust the listed package names?  This is copied from SideQuest.  I assume the former is not correct?

packageName: com.slr.oculus.quest
packageName: com.slr.oculus.go

**Comment by avluis** [comment]
They have since merged both applications per the install notes here: https://forum.sexlikereal.com/d/213-slr-app-for-oculus-quest-and-go-windows
