### ISSUE TITLE
MacOS - SideQuest can't be opened -47

### ISSUE THREAD

**Issue by mrackers** [the-expanse/SideQuest#75]
Mac OS 10.14.5

**Comment by mrackers** [comment]
I've tried deleting SideQuest from ~/library/Application Support and right-clicking to open. No luck.

**Comment by amydionne** [comment]
I have opened, installed and used this application I did not even have to delete anything from my library. Not sure what you are doing differently.

**Comment by JulianHH** [comment]
Having the exact same issue like OP.

It worked the release before. Something must have changed..

**Comment by CosmicRatio** [comment]
I had this same thing. I deleted the SideQuest folder in my Library & re-downloaded the zip and it works again now.

**Comment by ZRH530** [comment]
I am having same issue. Samer error for me. Can we have somebody elaborate please? I did notice it works if i right click and "show package contents." Then going in contes/macOS/exec.

**Comment by ZRH530** [comment]
For anyone who cares, i got it to work. I unzipped using a 3rd party app this time and it worked. Try that if you have the same problem.

**Comment by shaneharris** [comment]
https://github.com/the-expanse/SideQuest/issues/27#issuecomment-498435162

**Comment by ryanlauderbach** [comment]
Unzipped with a 3rd party app, removed the ApplicationSupport/sidequest folder, and right clicked and selected open and I'm still getting the -47 error.

**Comment by Rookotronic** [comment]
Mac 10.14.5 Downloaded it and unpacked with WinZip into Program folder -> doesn't let me open it via right click. Is my first time trying, so no idea what it looks like when it works

**Comment by Malakai-UK** [comment]
I used the app The Unarchiver to extract mine and it now works, couldn't get it to work with others, kept getting error -47

**Comment by cruddog** [comment]
I had to rename the unzipped folder to 'SideQuest' and it worked for me.

**Comment by shaneharris** [comment]
this is an error related to GateKeeper on mac, right click and click open the first time or copy the tar.gz out of downloads before you extract should solve this.
