### ISSUE TITLE
Add Beatsaver.com Support?

### ISSUE THREAD

**Issue by TheRealDarkOneX** [the-expanse/SideQuest#76]
Any way to add Beatsaver.com support?  I seem to have issues pulling songs sometimes from bsaber.com but beatsaver.com works every time and the site seems faster I think so would be great to add that ability in.

**Comment by ATechAdventurer** [comment]
My SideQuest Chrome and Firefox extensions currently support Bsaber.com and Beatsaver.com.
Chrome-> https://chrome.google.com/webstore/detail/fmifajifkgfamekjpeanjmjjiimfhbjl/publish-delayed?hl=en

Firefox-> https://addons.mozilla.org/en-US/firefox/addon/sidequest-bsaber-extension/

**Comment by JulianHH** [comment]
For chrome:
The requested URL was not found on this server. That’s all we know.

Do you have any alternative?

**Comment by TheRealDarkOneX** [comment]
Worked fine for me yo.  Installed a bunch of songs last night using the Chrome extension to load them into Sidequest from both bsaber.com and beatsaver.com, worked a treat, thanks!

**Comment by JulianHH** [comment]
Hmmm. Maybe it was taken down.

**Comment by ATechAdventurer** [comment]
@JulianHH still up https://chrome.google.com/webstore/detail/sidequest-bsaber-extensio/fmifajifkgfamekjpeanjmjjiimfhbjl

**Comment by JulianHH** [comment]
@ATechAdventurer for whatever reason that link worked now, thanks :)

**Comment by shaneharris** [comment]
Woop woop! Nice one people! @ATechAdventurer we should get this in the readme so everyone can get access to the browser extensions. Ill close this one then.

Thanks!

**Comment by kitze** [comment]
@ATechAdventurer the chrome extension still doesn't show a download button for beatsaver.com
