### ISSUE TITLE
Feature Request: Support for one-click playlist downloading at bsaber.com.

### ISSUE THREAD

**Issue by SecAdept** [the-expanse/SideQuest#77]
I love how you have incorporated one-click downloading for songs on bsaber.com. However, a ton of the hundreds of songs I like are all in the playlists. Rather than clicking each song individually, it would be awesome if you incorporated **playlist** one-click downloads.

**Comment by drewbaumann** [comment]
We probably need to let the dust settle with the beastsaber migration before looking into this. I briefly looked into how playlists work on there and you get a blist file which references IDs of the songs. Unfortunately, playlists are currently pointing to the old IDs (vs the new beatsaver ids). We would likely need to have API integration with the beatsaver API to move forward with this effort, but until beastsaber makes the transition I personally don't think this is worth pursuing.

**Comment by honestbleeps** [comment]
now that the migration is done, I would absolutely love if this were possible!  Those "songs with flow" playlists are fantastic!

**Comment by drewbaumann** [comment]
Got a link so we can reference the format of the file?

> now that the migration is done, I would absolutely love if this were possible! Those "songs with flow" playlists are fantastic!

**Comment by honestbleeps** [comment]
sure! here's an example: https://bsaber.com/songs-with-fantastic-flow-vol-5/

There's a download button on that page.

**Comment by drewbaumann** [comment]
So the tough thing about this is that the bplist is not hard to read, but the song keys it references are to the old beastsaver catalogue. I am not sure if they have an endpoint that can get the new key based off old ones or not.

If anyone has insight please let us know!

**Comment by honestbleeps** [comment]
ahhh okay, that makes sense... I'll see if I can find anything!

**Comment by stychu** [comment]
This feature is a must!!! I would like to help if I gonna be able to. Going to dig this as I need it personally ^^ ;)
@drewbaumann does bsaber have an open API? Where can I find any info?

**Comment by drewbaumann** [comment]
@stychu if I had a PC the next steps I would take are downloading the app that handles playlists and snooping the network traffic to inspect the endpoints they are hitting to get the desired songs. We would need to replicate that behavior.

**Comment by shaneharris** [comment]
i think this functionality might now be in BeatOn, but sidequest no longer has a sone manager so this should really move to beat on if not
