### ISSUE TITLE
Feature Request: Include two versions of sidequest appstarter launcher to open in Oculus TV and Home menu

### ISSUE THREAD

**Issue by ANewDawn** [the-expanse/SideQuest#79]
As discussed in discord. Be nice to have separate versions of appstarter launcher. One opens normally in oculus TV while the other to open in the home menu. 

Edit: The appstarter width is a little narrow while in oculus home menu. If could make wider to same size as oculus library menu.

**Comment by shaneharris** [comment]
unfortunately AFAIK there is no way to change the window resolution. I will add the app starter as a separate one to launch both.

**Comment by ANewDawn** [comment]
@shaneharris many thanks

**Comment by shaneharris** [comment]
this will be in the latest version!

**Comment by ANewDawn** [comment]
@shaneharris 😁👍
