### ISSUE TITLE
Errors within certain apks are not being picked up by sidequest which displays app as installed while it's not

### ISSUE THREAD

**Issue by ANewDawn** [the-expanse/SideQuest#81]
Tried sideloading few gear vr apps on quest. Apk displayed as installed on green bar on sidequest, while they don't appear on headset.

Installing the same apk via adb picked up the errors and displayed failed install message.

See screenshot [https://i.imgur.com/jiTBhsM.jpg](https://i.imgur.com/jiTBhsM.jpg)

Anyway I can get debug log from sidequest to help?

**Comment by shaneharris** [comment]
this should now be fixed in the latest version coming soon!
