### ISSUE TITLE
Enable the Oculus Home 2d app mode for Quest users. 

### ISSUE THREAD

**Issue by shaneharris** [the-expanse/SideQuest#84]
Currently you can sideload https://cdn.theexpanse.app/SideQuestWrapper2.apk to be able to launch apps in a floating screen in Oculus Home instead of Oculus TV. To be able to have both it makes sense to sideload both wrappers and have separate launch items in the unknown sources list, one for TV and one for Home.

Sideloading: https://cdn.theexpanse.app/SideQuestWrapper.apk again will reset back to Oculus TV launcher for anyone reading this in the mean time.

**Comment by ANewDawn** [comment]
@shaneharris thanks for this.

Are you able to increase the width of the floating screen in Oculus Home, preferably to same dimensions as oculus library panel which is nice size.

Thanks again

**Comment by shaneharris** [comment]
dupe of #79
