### ISSUE TITLE
Feature Request: add super sampling options

### ISSUE THREAD

**Issue by fbesse** [the-expanse/SideQuest#86]
It would be great to be able to enable the different resolution options via SideQuest, see: https://reddit.com/r/OculusQuest/comments/bxwkn2/oculus_quest_supersampling_x2_why_you_need_to_try/

**Comment by shaneharris** [comment]
https://app.box.com/s/o2apxuj3pob0rs4b8ruk9sek57gzwz08

**Comment by shaneharris** [comment]
This has been added in the latest version, Texture size, video bit rate, video resolution and forceChroma are all now available.
