### ISSUE TITLE
Beat Saber not working, using cracked apk

### ISSUE THREAD

**Issue by SpookyBear0** [the-expanse/SideQuest#87]
Idk what to do, error code below. (using v1.02)

Edit: it says: wrong beat saber version v1.0.2

System.IO.InvalidDataException: End of Central Directory record could not be found. at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) at jsonApp.Program.RunInvocation(Invocation inv) in C:\projects\QuestSaberPatch\jsonApp\Program.cs:line 60

**Comment by shaneharris** [comment]
sorry i do not support cracked software.
