### ISSUE TITLE
Error message in the bottom (Mac) ENOTDIR

### ISSUE THREAD

**Issue by retorquere** [the-expanse/SideQuest#89]
In the bottom of the app I see a green bar that says 

> Error reading songs directory: /Users/emile/Library/Application Support/SideQuest/bsaber/.DS_Store, Error:Error: ENOTDIR: not a directory, scandir '/Users/emile/Library/Application Support/SideQuest/bsa...
<img width="1601" alt="Screenshot 2019-06-08 at 13 10 13" src="https://user-images.githubusercontent.com/132108/59146467-cdd4ae00-89ee-11e9-9efc-f0a4397a1c6b.png">

**Comment by retorquere** [comment]
Is it safe to remove in its entirety and start over?

**Comment by shaneharris** [comment]
I have fixed this in the latest build! this will be releasing today.

its the `.DS_Store` file causing the issues. I am testing tehm in the new version but in the mean time you can try deleting that file.
