### ISSUE TITLE
Error on Mac 

### ISSUE THREAD

**Issue by meish84** [the-expanse/SideQuest#90]
I’ve fresh  installed beat saber and updated side quest  via the instructions given 

when I try to install songs I get this error 
SystemIO Invailddataexception end of central directory record cannot be found at system IO compression zip 

![A4B170DC-13E2-48BC-B9D7-AE2A6718738C](https://user-images.githubusercontent.com/51508929/59147024-be089a00-89ed-11e9-9cff-908a59d29f07.jpeg)

**Comment by shaneharris** [comment]
Were releasing a fix for this today!
