### ISSUE TITLE
Wonky window size responsiveness on the setup instructions screen

### ISSUE THREAD

**Issue by j4nw** [the-expanse/SideQuest#91]
Spacing between rows with steps isn't responsive. Some overlapping is already present on full screen 1920x1080, and 2560x1440 (below) is completely illegible

![setup](https://user-images.githubusercontent.com/26443707/59148470-ab9c5980-8a09-11e9-8c89-af4271c1104a.png)

**Comment by shaneharris** [comment]
This has been fixed in the latest version. Releasing later today!
