### ISSUE TITLE
Difference between unselect and delete?

### ISSUE THREAD

**Issue by retorquere** [the-expanse/SideQuest#93]
I see I can unselect songs and when I sync, they are removed from the Quest. I also see in the triple-dot menu of the song that I can delete the song from my computer. Will deleting the song also unsync it?

Once unsynced, the songs disappear from the sidequest song list, so it's hard to find them again to delete them from disk. I'm a little confused by the difference between the two.

Stellar work on SQ! I love the quest so much now!

**Comment by shaneharris** [comment]
this has all changed with the latest release which is out in a few hours! it now has custom pack management

**Comment by shaneharris** [comment]
and thanks for your kind comments!
