### ISSUE TITLE
Refactor repo json to revamp install process

### ISSUE THREAD

**Issue by drewbaumann** [the-expanse/SideQuest#97]
As it stands installing an app with SideQuest is pretty straight forward. The user goes to an app page and clicks an install button. Behind the scenes [there is a repo with links to APKs](http://showmewhatyougot.x10host.com/vr-games/index-v1.json) where we then [temporarily download and install to the device](https://github.com/the-expanse/SideQuest/blob/a633e562546d6ff26d240a1c8db9cac958b30d98/desktop-app/js/app.js#L897). This seems like a fine solution for apps that require only the install of the APK for setup, but does not work for the install of more complex installs like the Pavlov alpha.

The good news is I believe we can add support without too much effort.

This is an example of a modified hash we could use for backwards support as well as a more robust option for complex installs:

```json
{
  repo: {
    timestamp: 1502257810365,
    version: 21,
    name: "VR Games",
    icon: "vrgames.png",
    address: "http://showmewhatyougot.x10host.com/vr-games/",
    description: "Some great VR games! Launch these from the unknown sources list for now."
  },
  requests: {
    install: [],
    uninstall: []
  },
  apps: [{
      antiFeatures: [],
      categories: [
        "FPS"
      ],
      suggestedVersionName: "0.1.18",
      suggestedVersionCode: "282",
      description: "We aim at people and shoot",
      issueTracker: "https://theexpanse.app/support/",
      license: "FREE",
      name: "Pavlov Alpha",
      sourceCode: "",
      summary: "Summary",
      webSite: "https://somewebsite.com",
      added: 1502257684722,
      icon: "pavlov.jpg",
      packageName: "com.davevillz.pavlov",
      lastUpdated: 1502257746030
    },
  ],
  packages: {
    com.davevillz.pavlov: [{
      added: 1559229168000,
      apkName: "http://somecdn.com/pavlov.apk",
      autoEnablePermissions: true,
      hash: "",
      hashType: "sha256",
      minSdkVersion: "16",
      nativecode: [
        "armeabi-v7a"
      ],
      obbUrl: "http://somecdn.com/main.1.com.davevillz.pavlov.obb",
      packageName: "com.davevillz.pavlov",
      sig: "",
      size: 55156885,
      srcname: "",
      targetSdkVersion: "22",
      versionCode: 113,
      versionName: "1.13.00",
      uses - permission: [
        [
          "Microphone"
        ]
      ]
    }]
  }
}
```

Note a couple changes here: `autoEnablePermissions` and `obbUrl`.
If a package has an optional `obbUrl` in addition to installing the APK we would push the obb file to the proper path. `autoEnablePermissions` would be a boolean or null (to support backwards compatibility). If `autoEnablePermissions` is `true` we would run a script as the last step in the install process that would enable the permissions defined in the `uses - permission` array.

I believe this would lead to apps like pavlov being easily added to SideQuest and lead to greater adoption of this app by developers with more complex installs and users looking for easy solutions to install said apps.

**Comment by shaneharris** [comment]
this is a great idea and could be useful for a lot of pre-release apps that rely on an extra obb file. 

@ATechAdventurer id love to know your thoughts on this! I know you have been working on the fdroid implementation.

**Comment by ATechAdventurer** [comment]
@drewbaumann I totally agree, I have been thinking that we should sit down and establish a new spec based on the fdroid one. I made a wiki entry where we can figure everything out check it out and feel free to add to the spec. https://github.com/the-expanse/SideQuest/wiki/SideQuest-Repo-Spec

**Comment by drewbaumann** [comment]
@ATechAdventurer Awesome. Will do.

**Comment by drewbaumann** [comment]
Also it doesn't appear that I have an easy way to edit the wiki. Would I be able to be added as a collaborator?

**Comment by ATechAdventurer** [comment]
@drewbaumann I agree with that. I'll check on getting you access to the wiki

**Comment by shaneharris** [comment]
One thing that's important here is that we remain compatible with the fdroid repo spec so I don't think its a great idea to change properties like that without a really good reason and rather add new properties where needed. reinventing the spec is not a good idea, we should try to remain backwards compatible.

**Comment by drewbaumann** [comment]
@shaneharris I agree. I didn't realize that key was part of the spec. I have reviewed it since and agree it does not make sense to deprecate something that we are not in control of and other platforms rely on.

**Comment by dnlm** [comment]
Is this actively being worked on?

If this just needs js coding I could probably be of service.

**Comment by drewbaumann** [comment]
@dnlm it's kind of in limbo atm. I came up with this solution for pavlov due to the unconventional install method, but my understanding is that the next alpha release will be packaged normally. Seeing that other apps have all released APKs and have avoided complex installs like Pavlov I am uncertain if there is still a need for this. Open to thoughts!

**Comment by shaneharris** [comment]
This is no longer a requirement with the new app listings. Thanks!
